/*
 * Automatically generated C config: don't edit
 * Linux kernel version: 2.6.12
 * Sat Jun 18 16:13:07 2005
 */
#define AUTOCONF_INCLUDED
#define CONFIG_64BIT 1
#define CONFIG_MMU 1
#define CONFIG_TIME_INTERPOLATION 1
#define CONFIG_SPARC64_PAGE_SIZE_8KB 1
#undef CONFIG_SPARC64_PAGE_SIZE_64KB
#undef CONFIG_SPARC64_PAGE_SIZE_512KB
#undef CONFIG_SPARC64_PAGE_SIZE_4MB

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1
#define CONFIG_CLEAN_COMPILE 1
#define CONFIG_LOCK_KERNEL 1
#define CONFIG_INIT_ENV_ARG_LIMIT 32

/*
 * General setup
 */
#define CONFIG_LOCALVERSION ""
#define CONFIG_SWAP 1
#define CONFIG_SYSVIPC 1
#define CONFIG_POSIX_MQUEUE 1
#undef CONFIG_BSD_PROCESS_ACCT
#define CONFIG_SYSCTL 1
#undef CONFIG_AUDIT
#define CONFIG_HOTPLUG 1
#define CONFIG_KOBJECT_UEVENT 1
#undef CONFIG_IKCONFIG
#undef CONFIG_CPUSETS
#undef CONFIG_EMBEDDED
#define CONFIG_KALLSYMS 1
#undef CONFIG_KALLSYMS_ALL
#undef CONFIG_KALLSYMS_EXTRA_PASS
#define CONFIG_PRINTK 1
#define CONFIG_BUG 1
#define CONFIG_BASE_FULL 1
#define CONFIG_FUTEX 1
#define CONFIG_EPOLL 1
#define CONFIG_SHMEM 1
#define CONFIG_CC_ALIGN_FUNCTIONS 0
#define CONFIG_CC_ALIGN_LABELS 0
#define CONFIG_CC_ALIGN_LOOPS 0
#define CONFIG_CC_ALIGN_JUMPS 0
#undef CONFIG_TINY_SHMEM
#define CONFIG_BASE_SMALL 0

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#define CONFIG_MODULE_UNLOAD 1
#define CONFIG_MODULE_FORCE_UNLOAD 1
#define CONFIG_OBSOLETE_MODPARM 1
#define CONFIG_MODVERSIONS 1
#define CONFIG_MODULE_SRCVERSION_ALL 1
#define CONFIG_KMOD 1
#define CONFIG_STOP_MACHINE 1
#define CONFIG_SYSVIPC_COMPAT 1

/*
 * General machine setup
 */
#define CONFIG_BBC_I2C_MODULE 1
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#define CONFIG_HW_CONSOLE 1
#define CONFIG_SMP 1
#undef CONFIG_PREEMPT
#define CONFIG_NR_CPUS 4
#define CONFIG_CPU_FREQ 1
#define CONFIG_CPU_FREQ_TABLE_MODULE 1
#undef CONFIG_CPU_FREQ_DEBUG
#define CONFIG_CPU_FREQ_STAT_MODULE 1
#define CONFIG_CPU_FREQ_STAT_DETAILS 1
#define CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE 1
#undef CONFIG_CPU_FREQ_DEFAULT_GOV_USERSPACE
#define CONFIG_CPU_FREQ_GOV_PERFORMANCE 1
#define CONFIG_CPU_FREQ_GOV_POWERSAVE_MODULE 1
#define CONFIG_CPU_FREQ_GOV_USERSPACE_MODULE 1
#define CONFIG_CPU_FREQ_GOV_ONDEMAND_MODULE 1
#undef CONFIG_CPU_FREQ_GOV_CONSERVATIVE
#define CONFIG_US3_FREQ_MODULE 1
#define CONFIG_US2E_FREQ_MODULE 1
#define CONFIG_SPARC64 1
#define CONFIG_RWSEM_XCHGADD_ALGORITHM 1
#define CONFIG_GENERIC_CALIBRATE_DELAY 1
#define CONFIG_HUGETLB_PAGE_SIZE_4MB 1
#undef CONFIG_HUGETLB_PAGE_SIZE_512K
#undef CONFIG_HUGETLB_PAGE_SIZE_64K
#define CONFIG_GENERIC_ISA_DMA 1
#define CONFIG_SBUS 1
#define CONFIG_SBUSCHAR 1
#define CONFIG_SUN_AUXIO 1
#define CONFIG_SUN_IO 1
#define CONFIG_PCI 1
#define CONFIG_PCI_DOMAINS 1
#define CONFIG_RTC 1
#undef CONFIG_PCI_LEGACY_PROC
#undef CONFIG_PCI_NAMES
#undef CONFIG_PCI_DEBUG
#define CONFIG_SUN_OPENPROMFS_MODULE 1
#define CONFIG_SPARC32_COMPAT 1
#define CONFIG_COMPAT 1
#define CONFIG_UID16 1
#define CONFIG_BINFMT_ELF32 1
#undef CONFIG_BINFMT_AOUT32
#define CONFIG_BINFMT_ELF 1
#define CONFIG_BINFMT_MISC_MODULE 1
#define CONFIG_SOLARIS_EMUL_MODULE 1

/*
 * Parallel port support
 */
#define CONFIG_PARPORT_MODULE 1
#define CONFIG_PARPORT_PC_MODULE 1
#define CONFIG_PARPORT_PC_FIFO 1
#undef CONFIG_PARPORT_PC_SUPERIO
#define CONFIG_PARPORT_NOT_PC 1
#undef CONFIG_PARPORT_GSC
#undef CONFIG_PARPORT_SUNBPP
#define CONFIG_PARPORT_1284 1
#define CONFIG_PRINTER_MODULE 1
#define CONFIG_ENVCTRL_MODULE 1
#define CONFIG_DISPLAY7SEG_MODULE 1
#undef CONFIG_CMDLINE_BOOL

/*
 * Generic Driver Options
 */
#define CONFIG_STANDALONE 1
#undef CONFIG_PREVENT_FIRMWARE_BUILD
#define CONFIG_FW_LOADER_MODULE 1
#undef CONFIG_DEBUG_DRIVER

/*
 * Graphics support
 */
#define CONFIG_FB 1
#define CONFIG_FB_CFB_FILLRECT 1
#define CONFIG_FB_CFB_COPYAREA 1
#define CONFIG_FB_CFB_IMAGEBLIT 1
#define CONFIG_FB_SOFT_CURSOR 1
#undef CONFIG_FB_MACMODES
#define CONFIG_FB_MODE_HELPERS 1
#define CONFIG_FB_TILEBLITTING 1
#undef CONFIG_FB_CIRRUS
#define CONFIG_FB_PM2 1
#undef CONFIG_FB_PM2_FIFO_DISCONNECT
#undef CONFIG_FB_ASILIANT
#undef CONFIG_FB_IMSTT
#undef CONFIG_FB_BW2
#undef CONFIG_FB_CG3
#define CONFIG_FB_CG6 1
#undef CONFIG_FB_NVIDIA
#undef CONFIG_FB_RIVA
#undef CONFIG_FB_MATROX
#undef CONFIG_FB_RADEON_OLD
#undef CONFIG_FB_RADEON
#undef CONFIG_FB_ATY128
#define CONFIG_FB_ATY 1
#define CONFIG_FB_ATY_CT 1
#undef CONFIG_FB_ATY_GENERIC_LCD
#undef CONFIG_FB_ATY_XL_INIT
#define CONFIG_FB_ATY_GX 1
#undef CONFIG_FB_SAVAGE
#undef CONFIG_FB_SIS
#undef CONFIG_FB_NEOMAGIC
#undef CONFIG_FB_KYRO
#undef CONFIG_FB_3DFX
#undef CONFIG_FB_VOODOO1
#undef CONFIG_FB_TRIDENT
#define CONFIG_FB_SBUS 1
#define CONFIG_FB_FFB 1
#undef CONFIG_FB_TCX
#undef CONFIG_FB_CG14
#undef CONFIG_FB_P9100
#undef CONFIG_FB_LEO
#undef CONFIG_FB_PCI
#undef CONFIG_FB_S1D13XXX
#undef CONFIG_FB_VIRTUAL

/*
 * Console display driver support
 */
#undef CONFIG_PROM_CONSOLE
#define CONFIG_DUMMY_CONSOLE 1
#define CONFIG_FRAMEBUFFER_CONSOLE 1
#define CONFIG_FONTS 1
#undef CONFIG_FONT_8x8
#undef CONFIG_FONT_8x16
#undef CONFIG_FONT_6x11
#undef CONFIG_FONT_PEARL_8x8
#undef CONFIG_FONT_ACORN_8x8
#define CONFIG_FONT_SUN8x16 1
#undef CONFIG_FONT_SUN12x22

/*
 * Logo configuration
 */
#define CONFIG_LOGO 1
#undef CONFIG_LOGO_LINUX_MONO
#undef CONFIG_LOGO_LINUX_VGA16
#undef CONFIG_LOGO_LINUX_CLUT224
#define CONFIG_LOGO_SUN_CLUT224 1
#undef CONFIG_BACKLIGHT_LCD_SUPPORT

/*
 * Serial drivers
 */

/*
 * Non-8250 serial port support
 */
#define CONFIG_SERIAL_SUNCORE 1
#define CONFIG_SERIAL_SUNZILOG 1
#define CONFIG_SERIAL_SUNZILOG_CONSOLE 1
#define CONFIG_SERIAL_SUNSU 1
#define CONFIG_SERIAL_SUNSU_CONSOLE 1
#define CONFIG_SERIAL_SUNSAB_MODULE 1
#define CONFIG_SERIAL_CORE 1
#define CONFIG_SERIAL_CORE_CONSOLE 1
#undef CONFIG_SERIAL_JSM

/*
 * Misc Linux/SPARC drivers
 */
#define CONFIG_SUN_OPENPROMIO_MODULE 1
#define CONFIG_SUN_MOSTEK_RTC 1
#define CONFIG_OBP_FLASH_MODULE 1
#undef CONFIG_SUN_BPP

/*
 * Memory Technology Devices (MTD)
 */
#undef CONFIG_MTD

/*
 * Block devices
 */
#undef CONFIG_BLK_DEV_FD
#undef CONFIG_PARIDE
#undef CONFIG_BLK_CPQ_DA
#undef CONFIG_BLK_CPQ_CISS_DA
#undef CONFIG_BLK_DEV_DAC960
#undef CONFIG_BLK_DEV_UMEM
#undef CONFIG_BLK_DEV_COW_COMMON
#define CONFIG_BLK_DEV_LOOP_MODULE 1
#define CONFIG_BLK_DEV_CRYPTOLOOP_MODULE 1
#define CONFIG_BLK_DEV_NBD_MODULE 1
#define CONFIG_BLK_DEV_SX8_MODULE 1
#define CONFIG_BLK_DEV_UB_MODULE 1
#undef CONFIG_BLK_DEV_RAM
#define CONFIG_BLK_DEV_RAM_COUNT 16
#define CONFIG_INITRAMFS_SOURCE ""
#define CONFIG_CDROM_PKTCDVD_MODULE 1
#define CONFIG_CDROM_PKTCDVD_BUFFERS 8
#define CONFIG_CDROM_PKTCDVD_WCACHE 1

/*
 * IO Schedulers
 */
#define CONFIG_IOSCHED_NOOP 1
#define CONFIG_IOSCHED_AS 1
#define CONFIG_IOSCHED_DEADLINE 1
#define CONFIG_IOSCHED_CFQ 1
#define CONFIG_ATA_OVER_ETH_MODULE 1

/*
 * ATA/ATAPI/MFM/RLL support
 */
#define CONFIG_IDE 1
#define CONFIG_BLK_DEV_IDE 1

/*
 * Please see Documentation/ide.txt for help/info on IDE drives
 */
#undef CONFIG_BLK_DEV_IDE_SATA
#define CONFIG_BLK_DEV_IDEDISK 1
#undef CONFIG_IDEDISK_MULTI_MODE
#define CONFIG_BLK_DEV_IDECD 1
#define CONFIG_BLK_DEV_IDETAPE_MODULE 1
#undef CONFIG_BLK_DEV_IDEFLOPPY
#undef CONFIG_BLK_DEV_IDESCSI
#undef CONFIG_IDE_TASK_IOCTL

/*
 * IDE chipset support/bugfixes
 */
#define CONFIG_IDE_GENERIC 1
#define CONFIG_BLK_DEV_IDEPCI 1
#undef CONFIG_IDEPCI_SHARE_IRQ
#undef CONFIG_BLK_DEV_OFFBOARD
#undef CONFIG_BLK_DEV_GENERIC
#define CONFIG_BLK_DEV_OPTI621_MODULE 1
#define CONFIG_BLK_DEV_IDEDMA_PCI 1
#undef CONFIG_BLK_DEV_IDEDMA_FORCED
#define CONFIG_IDEDMA_PCI_AUTO 1
#define CONFIG_IDEDMA_ONLYDISK 1
#undef CONFIG_BLK_DEV_AEC62XX
#define CONFIG_BLK_DEV_ALI15X3 1
#undef CONFIG_WDC_ALI15X3
#define CONFIG_BLK_DEV_AMD74XX_MODULE 1
#define CONFIG_BLK_DEV_CMD64X_MODULE 1
#define CONFIG_BLK_DEV_TRIFLEX_MODULE 1
#define CONFIG_BLK_DEV_CY82C693_MODULE 1
#define CONFIG_BLK_DEV_CS5520_MODULE 1
#define CONFIG_BLK_DEV_CS5530_MODULE 1
#define CONFIG_BLK_DEV_HPT34X_MODULE 1
#undef CONFIG_HPT34X_AUTODMA
#define CONFIG_BLK_DEV_HPT366_MODULE 1
#define CONFIG_BLK_DEV_SC1200_MODULE 1
#define CONFIG_BLK_DEV_PIIX_MODULE 1
#define CONFIG_BLK_DEV_NS87415_MODULE 1
#define CONFIG_BLK_DEV_PDC202XX_OLD_MODULE 1
#undef CONFIG_PDC202XX_BURST
#define CONFIG_BLK_DEV_PDC202XX_NEW_MODULE 1
#undef CONFIG_PDC202XX_FORCE
#define CONFIG_BLK_DEV_SVWKS_MODULE 1
#define CONFIG_BLK_DEV_SIIMAGE_MODULE 1
#define CONFIG_BLK_DEV_SLC90E66_MODULE 1
#define CONFIG_BLK_DEV_TRM290_MODULE 1
#define CONFIG_BLK_DEV_VIA82CXXX_MODULE 1
#undef CONFIG_IDE_ARM
#define CONFIG_BLK_DEV_IDEDMA 1
#undef CONFIG_IDEDMA_IVB
#define CONFIG_IDEDMA_AUTO 1
#undef CONFIG_BLK_DEV_HD

/*
 * SCSI device support
 */
#define CONFIG_SCSI 1
#define CONFIG_SCSI_PROC_FS 1

/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#define CONFIG_BLK_DEV_SD 1
#define CONFIG_CHR_DEV_ST_MODULE 1
#define CONFIG_CHR_DEV_OSST_MODULE 1
#define CONFIG_BLK_DEV_SR_MODULE 1
#define CONFIG_BLK_DEV_SR_VENDOR 1
#define CONFIG_CHR_DEV_SG_MODULE 1

/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#define CONFIG_SCSI_MULTI_LUN 1
#define CONFIG_SCSI_CONSTANTS 1
#undef CONFIG_SCSI_LOGGING

/*
 * SCSI Transport Attributes
 */
#define CONFIG_SCSI_SPI_ATTRS 1
#define CONFIG_SCSI_FC_ATTRS_MODULE 1
#define CONFIG_SCSI_ISCSI_ATTRS_MODULE 1

/*
 * SCSI low-level drivers
 */
#define CONFIG_BLK_DEV_3W_XXXX_RAID_MODULE 1
#define CONFIG_SCSI_3W_9XXX_MODULE 1
#define CONFIG_SCSI_ACARD_MODULE 1
#define CONFIG_SCSI_AACRAID_MODULE 1
#undef CONFIG_SCSI_AIC7XXX
#undef CONFIG_SCSI_AIC7XXX_OLD
#define CONFIG_SCSI_AIC79XX_MODULE 1
#define CONFIG_AIC79XX_CMDS_PER_DEVICE 32
#define CONFIG_AIC79XX_RESET_DELAY_MS 15000
#undef CONFIG_AIC79XX_BUILD_FIRMWARE
#undef CONFIG_AIC79XX_ENABLE_RD_STRM
#undef CONFIG_AIC79XX_DEBUG_ENABLE
#define CONFIG_AIC79XX_DEBUG_MASK 0
#undef CONFIG_AIC79XX_REG_PRETTY_PRINT
#undef CONFIG_MEGARAID_NEWGEN
#undef CONFIG_MEGARAID_LEGACY
#define CONFIG_SCSI_SATA 1
#define CONFIG_SCSI_SATA_AHCI_MODULE 1
#define CONFIG_SCSI_SATA_SVW_MODULE 1
#define CONFIG_SCSI_ATA_PIIX_MODULE 1
#define CONFIG_SCSI_SATA_NV_MODULE 1
#define CONFIG_SCSI_SATA_PROMISE_MODULE 1
#define CONFIG_SCSI_SATA_QSTOR_MODULE 1
#define CONFIG_SCSI_SATA_SX4_MODULE 1
#define CONFIG_SCSI_SATA_SIL_MODULE 1
#define CONFIG_SCSI_SATA_SIS_MODULE 1
#define CONFIG_SCSI_SATA_ULI_MODULE 1
#define CONFIG_SCSI_SATA_VIA_MODULE 1
#define CONFIG_SCSI_SATA_VITESSE_MODULE 1
#define CONFIG_SCSI_DMX3191D_MODULE 1
#undef CONFIG_SCSI_FUTURE_DOMAIN
#define CONFIG_SCSI_IPS_MODULE 1
#define CONFIG_SCSI_INITIO_MODULE 1
#define CONFIG_SCSI_INIA100_MODULE 1
#define CONFIG_SCSI_PPA_MODULE 1
#define CONFIG_SCSI_IMM_MODULE 1
#undef CONFIG_SCSI_IZIP_EPP16
#undef CONFIG_SCSI_IZIP_SLOW_CTR
#define CONFIG_SCSI_SYM53C8XX_2 1
#define CONFIG_SCSI_SYM53C8XX_DMA_ADDRESSING_MODE 1
#define CONFIG_SCSI_SYM53C8XX_DEFAULT_TAGS 16
#define CONFIG_SCSI_SYM53C8XX_MAX_TAGS 64
#undef CONFIG_SCSI_SYM53C8XX_IOMAPPED
#undef CONFIG_SCSI_IPR
#define CONFIG_SCSI_QLOGIC_FC 1
#define CONFIG_SCSI_QLOGIC_FC_FIRMWARE 1
#undef CONFIG_SCSI_QLOGIC_1280
#define CONFIG_SCSI_QLOGICPTI_MODULE 1
#define CONFIG_SCSI_QLA2XXX 1
#undef CONFIG_SCSI_QLA21XX
#undef CONFIG_SCSI_QLA22XX
#undef CONFIG_SCSI_QLA2300
#undef CONFIG_SCSI_QLA2322
#undef CONFIG_SCSI_QLA6312
#undef CONFIG_SCSI_LPFC
#define CONFIG_SCSI_DC395x_MODULE 1
#undef CONFIG_SCSI_DC390T
#define CONFIG_SCSI_DEBUG_MODULE 1
#define CONFIG_SCSI_SUNESP 1

/*
 * Fibre Channel support
 */
#define CONFIG_FC4_MODULE 1

/*
 * FC4 drivers
 */
#define CONFIG_FC4_SOC_MODULE 1
#define CONFIG_FC4_SOCAL_MODULE 1

/*
 * FC4 targets
 */
#define CONFIG_SCSI_PLUTO_MODULE 1
#define CONFIG_SCSI_FCAL_MODULE 1

/*
 * Multi-device support (RAID and LVM)
 */
#define CONFIG_MD 1
#define CONFIG_BLK_DEV_MD_MODULE 1
#define CONFIG_MD_LINEAR_MODULE 1
#define CONFIG_MD_RAID0_MODULE 1
#define CONFIG_MD_RAID1_MODULE 1
#define CONFIG_MD_RAID10_MODULE 1
#define CONFIG_MD_RAID5_MODULE 1
#define CONFIG_MD_RAID6_MODULE 1
#define CONFIG_MD_MULTIPATH_MODULE 1
#undef CONFIG_MD_FAULTY
#define CONFIG_BLK_DEV_DM_MODULE 1
#define CONFIG_DM_CRYPT_MODULE 1
#define CONFIG_DM_SNAPSHOT_MODULE 1
#define CONFIG_DM_MIRROR_MODULE 1
#define CONFIG_DM_ZERO_MODULE 1
#undef CONFIG_DM_MULTIPATH

/*
 * Fusion MPT device support
 */
#define CONFIG_FUSION_MODULE 1
#define CONFIG_FUSION_MAX_SGE 40
#define CONFIG_FUSION_CTL_MODULE 1
#define CONFIG_FUSION_LAN_MODULE 1

/*
 * IEEE 1394 (FireWire) support
 */
#define CONFIG_IEEE1394_MODULE 1

/*
 * Subsystem Options
 */
#undef CONFIG_IEEE1394_VERBOSEDEBUG
#define CONFIG_IEEE1394_OUI_DB 1
#define CONFIG_IEEE1394_EXTRA_CONFIG_ROMS 1
#define CONFIG_IEEE1394_CONFIG_ROM_IP1394 1

/*
 * Device Drivers
 */
#define CONFIG_IEEE1394_PCILYNX_MODULE 1
#define CONFIG_IEEE1394_OHCI1394_MODULE 1

/*
 * Protocol Drivers
 */
#define CONFIG_IEEE1394_VIDEO1394_MODULE 1
#define CONFIG_IEEE1394_SBP2_MODULE 1
#undef CONFIG_IEEE1394_SBP2_PHYS_DMA
#define CONFIG_IEEE1394_ETH1394_MODULE 1
#define CONFIG_IEEE1394_DV1394_MODULE 1
#define CONFIG_IEEE1394_RAWIO_MODULE 1
#define CONFIG_IEEE1394_CMP_MODULE 1
#define CONFIG_IEEE1394_AMDTP_MODULE 1

/*
 * Networking support
 */
#define CONFIG_NET 1

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#define CONFIG_PACKET_MMAP 1
#define CONFIG_UNIX 1
#define CONFIG_NET_KEY_MODULE 1
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#undef CONFIG_IP_ADVANCED_ROUTER
#undef CONFIG_IP_PNP
#define CONFIG_NET_IPIP_MODULE 1
#define CONFIG_NET_IPGRE_MODULE 1
#define CONFIG_NET_IPGRE_BROADCAST 1
#define CONFIG_IP_MROUTE 1
#define CONFIG_IP_PIMSM_V1 1
#define CONFIG_IP_PIMSM_V2 1
#define CONFIG_ARPD 1
#define CONFIG_SYN_COOKIES 1
#define CONFIG_INET_AH 1
#define CONFIG_INET_ESP 1
#define CONFIG_INET_IPCOMP 1
#define CONFIG_INET_TUNNEL 1
#define CONFIG_IP_TCPDIAG 1
#undef CONFIG_IP_TCPDIAG_IPV6

/*
 * IP: Virtual Server Configuration
 */
#define CONFIG_IP_VS_MODULE 1
#undef CONFIG_IP_VS_DEBUG
#define CONFIG_IP_VS_TAB_BITS 12

/*
 * IPVS transport protocol load balancing support
 */
#define CONFIG_IP_VS_PROTO_TCP 1
#define CONFIG_IP_VS_PROTO_UDP 1
#define CONFIG_IP_VS_PROTO_ESP 1
#define CONFIG_IP_VS_PROTO_AH 1

/*
 * IPVS scheduler
 */
#define CONFIG_IP_VS_RR_MODULE 1
#define CONFIG_IP_VS_WRR_MODULE 1
#define CONFIG_IP_VS_LC_MODULE 1
#define CONFIG_IP_VS_WLC_MODULE 1
#define CONFIG_IP_VS_LBLC_MODULE 1
#define CONFIG_IP_VS_LBLCR_MODULE 1
#define CONFIG_IP_VS_DH_MODULE 1
#define CONFIG_IP_VS_SH_MODULE 1
#define CONFIG_IP_VS_SED_MODULE 1
#define CONFIG_IP_VS_NQ_MODULE 1

/*
 * IPVS application helper
 */
#define CONFIG_IP_VS_FTP_MODULE 1
#define CONFIG_IPV6_MODULE 1
#define CONFIG_IPV6_PRIVACY 1
#define CONFIG_INET6_AH_MODULE 1
#define CONFIG_INET6_ESP_MODULE 1
#define CONFIG_INET6_IPCOMP_MODULE 1
#define CONFIG_INET6_TUNNEL_MODULE 1
#define CONFIG_IPV6_TUNNEL_MODULE 1
#define CONFIG_NETFILTER 1
#undef CONFIG_NETFILTER_DEBUG
#define CONFIG_BRIDGE_NETFILTER 1

/*
 * IP: Netfilter Configuration
 */
#define CONFIG_IP_NF_CONNTRACK_MODULE 1
#define CONFIG_IP_NF_CT_ACCT 1
#define CONFIG_IP_NF_CONNTRACK_MARK 1
#define CONFIG_IP_NF_CT_PROTO_SCTP_MODULE 1
#define CONFIG_IP_NF_FTP_MODULE 1
#define CONFIG_IP_NF_IRC_MODULE 1
#define CONFIG_IP_NF_TFTP_MODULE 1
#define CONFIG_IP_NF_AMANDA_MODULE 1
#define CONFIG_IP_NF_QUEUE_MODULE 1
#define CONFIG_IP_NF_IPTABLES_MODULE 1
#define CONFIG_IP_NF_MATCH_LIMIT_MODULE 1
#define CONFIG_IP_NF_MATCH_IPRANGE_MODULE 1
#define CONFIG_IP_NF_MATCH_MAC_MODULE 1
#define CONFIG_IP_NF_MATCH_PKTTYPE_MODULE 1
#define CONFIG_IP_NF_MATCH_MARK_MODULE 1
#define CONFIG_IP_NF_MATCH_MULTIPORT_MODULE 1
#define CONFIG_IP_NF_MATCH_TOS_MODULE 1
#define CONFIG_IP_NF_MATCH_RECENT_MODULE 1
#define CONFIG_IP_NF_MATCH_ECN_MODULE 1
#define CONFIG_IP_NF_MATCH_DSCP_MODULE 1
#define CONFIG_IP_NF_MATCH_AH_ESP_MODULE 1
#define CONFIG_IP_NF_MATCH_LENGTH_MODULE 1
#define CONFIG_IP_NF_MATCH_TTL_MODULE 1
#define CONFIG_IP_NF_MATCH_TCPMSS_MODULE 1
#define CONFIG_IP_NF_MATCH_HELPER_MODULE 1
#define CONFIG_IP_NF_MATCH_STATE_MODULE 1
#define CONFIG_IP_NF_MATCH_CONNTRACK_MODULE 1
#define CONFIG_IP_NF_MATCH_OWNER_MODULE 1
#define CONFIG_IP_NF_MATCH_PHYSDEV_MODULE 1
#define CONFIG_IP_NF_MATCH_ADDRTYPE_MODULE 1
#define CONFIG_IP_NF_MATCH_REALM_MODULE 1
#define CONFIG_IP_NF_MATCH_SCTP_MODULE 1
#define CONFIG_IP_NF_MATCH_COMMENT_MODULE 1
#define CONFIG_IP_NF_MATCH_CONNMARK_MODULE 1
#define CONFIG_IP_NF_MATCH_HASHLIMIT_MODULE 1
#define CONFIG_IP_NF_FILTER_MODULE 1
#define CONFIG_IP_NF_TARGET_REJECT_MODULE 1
#define CONFIG_IP_NF_TARGET_LOG_MODULE 1
#define CONFIG_IP_NF_TARGET_ULOG_MODULE 1
#define CONFIG_IP_NF_TARGET_TCPMSS_MODULE 1
#define CONFIG_IP_NF_NAT_MODULE 1
#define CONFIG_IP_NF_NAT_NEEDED 1
#define CONFIG_IP_NF_TARGET_MASQUERADE_MODULE 1
#define CONFIG_IP_NF_TARGET_REDIRECT_MODULE 1
#define CONFIG_IP_NF_TARGET_NETMAP_MODULE 1
#define CONFIG_IP_NF_TARGET_SAME_MODULE 1
#define CONFIG_IP_NF_NAT_SNMP_BASIC_MODULE 1
#define CONFIG_IP_NF_NAT_IRC_MODULE 1
#define CONFIG_IP_NF_NAT_FTP_MODULE 1
#define CONFIG_IP_NF_NAT_TFTP_MODULE 1
#define CONFIG_IP_NF_NAT_AMANDA_MODULE 1
#define CONFIG_IP_NF_MANGLE_MODULE 1
#define CONFIG_IP_NF_TARGET_TOS_MODULE 1
#define CONFIG_IP_NF_TARGET_ECN_MODULE 1
#define CONFIG_IP_NF_TARGET_DSCP_MODULE 1
#define CONFIG_IP_NF_TARGET_MARK_MODULE 1
#define CONFIG_IP_NF_TARGET_CLASSIFY_MODULE 1
#define CONFIG_IP_NF_TARGET_CONNMARK_MODULE 1
#define CONFIG_IP_NF_TARGET_CLUSTERIP_MODULE 1
#define CONFIG_IP_NF_RAW_MODULE 1
#define CONFIG_IP_NF_TARGET_NOTRACK_MODULE 1
#define CONFIG_IP_NF_ARPTABLES_MODULE 1
#define CONFIG_IP_NF_ARPFILTER_MODULE 1
#define CONFIG_IP_NF_ARP_MANGLE_MODULE 1

/*
 * IPv6: Netfilter Configuration (EXPERIMENTAL)
 */
#define CONFIG_IP6_NF_QUEUE_MODULE 1
#define CONFIG_IP6_NF_IPTABLES_MODULE 1
#define CONFIG_IP6_NF_MATCH_LIMIT_MODULE 1
#define CONFIG_IP6_NF_MATCH_MAC_MODULE 1
#define CONFIG_IP6_NF_MATCH_RT_MODULE 1
#define CONFIG_IP6_NF_MATCH_OPTS_MODULE 1
#define CONFIG_IP6_NF_MATCH_FRAG_MODULE 1
#define CONFIG_IP6_NF_MATCH_HL_MODULE 1
#define CONFIG_IP6_NF_MATCH_MULTIPORT_MODULE 1
#define CONFIG_IP6_NF_MATCH_OWNER_MODULE 1
#define CONFIG_IP6_NF_MATCH_MARK_MODULE 1
#define CONFIG_IP6_NF_MATCH_IPV6HEADER_MODULE 1
#define CONFIG_IP6_NF_MATCH_AHESP_MODULE 1
#define CONFIG_IP6_NF_MATCH_LENGTH_MODULE 1
#define CONFIG_IP6_NF_MATCH_EUI64_MODULE 1
#define CONFIG_IP6_NF_MATCH_PHYSDEV_MODULE 1
#define CONFIG_IP6_NF_FILTER_MODULE 1
#define CONFIG_IP6_NF_TARGET_LOG_MODULE 1
#define CONFIG_IP6_NF_MANGLE_MODULE 1
#define CONFIG_IP6_NF_TARGET_MARK_MODULE 1
#define CONFIG_IP6_NF_RAW_MODULE 1

/*
 * DECnet: Netfilter Configuration
 */
#define CONFIG_DECNET_NF_GRABULATOR_MODULE 1

/*
 * Bridge: Netfilter Configuration
 */
#define CONFIG_BRIDGE_NF_EBTABLES_MODULE 1
#define CONFIG_BRIDGE_EBT_BROUTE_MODULE 1
#define CONFIG_BRIDGE_EBT_T_FILTER_MODULE 1
#define CONFIG_BRIDGE_EBT_T_NAT_MODULE 1
#define CONFIG_BRIDGE_EBT_802_3_MODULE 1
#define CONFIG_BRIDGE_EBT_AMONG_MODULE 1
#define CONFIG_BRIDGE_EBT_ARP_MODULE 1
#define CONFIG_BRIDGE_EBT_IP_MODULE 1
#define CONFIG_BRIDGE_EBT_LIMIT_MODULE 1
#define CONFIG_BRIDGE_EBT_MARK_MODULE 1
#define CONFIG_BRIDGE_EBT_PKTTYPE_MODULE 1
#define CONFIG_BRIDGE_EBT_STP_MODULE 1
#define CONFIG_BRIDGE_EBT_VLAN_MODULE 1
#define CONFIG_BRIDGE_EBT_ARPREPLY_MODULE 1
#define CONFIG_BRIDGE_EBT_DNAT_MODULE 1
#define CONFIG_BRIDGE_EBT_MARK_T_MODULE 1
#define CONFIG_BRIDGE_EBT_REDIRECT_MODULE 1
#define CONFIG_BRIDGE_EBT_SNAT_MODULE 1
#define CONFIG_BRIDGE_EBT_LOG_MODULE 1
#define CONFIG_BRIDGE_EBT_ULOG_MODULE 1
#define CONFIG_XFRM 1
#define CONFIG_XFRM_USER_MODULE 1

/*
 * SCTP Configuration (EXPERIMENTAL)
 */
#define CONFIG_IP_SCTP_MODULE 1
#undef CONFIG_SCTP_DBG_MSG
#undef CONFIG_SCTP_DBG_OBJCNT
#undef CONFIG_SCTP_HMAC_NONE
#undef CONFIG_SCTP_HMAC_SHA1
#define CONFIG_SCTP_HMAC_MD5 1
#define CONFIG_ATM 1
#define CONFIG_ATM_CLIP 1
#undef CONFIG_ATM_CLIP_NO_ICMP
#define CONFIG_ATM_LANE_MODULE 1
#define CONFIG_ATM_MPOA_MODULE 1
#define CONFIG_ATM_BR2684_MODULE 1
#define CONFIG_ATM_BR2684_IPFILTER 1
#define CONFIG_BRIDGE_MODULE 1
#define CONFIG_VLAN_8021Q_MODULE 1
#define CONFIG_DECNET_MODULE 1
#define CONFIG_DECNET_ROUTER 1
#define CONFIG_DECNET_ROUTE_FWMARK 1
#define CONFIG_LLC_MODULE 1
#define CONFIG_LLC2_MODULE 1
#define CONFIG_IPX_MODULE 1
#undef CONFIG_IPX_INTERN
#define CONFIG_ATALK_MODULE 1
#undef CONFIG_DEV_APPLETALK
#define CONFIG_X25_MODULE 1
#define CONFIG_LAPB_MODULE 1
#define CONFIG_NET_DIVERT 1
#undef CONFIG_ECONET
#undef CONFIG_WAN_ROUTER

/*
 * QoS and/or fair queueing
 */
#define CONFIG_NET_SCHED 1
#undef CONFIG_NET_SCH_CLK_JIFFIES
#undef CONFIG_NET_SCH_CLK_GETTIMEOFDAY
#define CONFIG_NET_SCH_CLK_CPU 1
#define CONFIG_NET_SCH_CBQ_MODULE 1
#define CONFIG_NET_SCH_HTB_MODULE 1
#define CONFIG_NET_SCH_HFSC_MODULE 1
#define CONFIG_NET_SCH_ATM 1
#define CONFIG_NET_SCH_PRIO_MODULE 1
#define CONFIG_NET_SCH_RED_MODULE 1
#define CONFIG_NET_SCH_SFQ_MODULE 1
#define CONFIG_NET_SCH_TEQL_MODULE 1
#define CONFIG_NET_SCH_TBF_MODULE 1
#define CONFIG_NET_SCH_GRED_MODULE 1
#define CONFIG_NET_SCH_DSMARK_MODULE 1
#define CONFIG_NET_SCH_NETEM_MODULE 1
#define CONFIG_NET_SCH_INGRESS_MODULE 1
#define CONFIG_NET_QOS 1
#define CONFIG_NET_ESTIMATOR 1
#define CONFIG_NET_CLS 1
#define CONFIG_NET_CLS_BASIC_MODULE 1
#define CONFIG_NET_CLS_TCINDEX_MODULE 1
#define CONFIG_NET_CLS_ROUTE4_MODULE 1
#define CONFIG_NET_CLS_ROUTE 1
#define CONFIG_NET_CLS_FW_MODULE 1
#define CONFIG_NET_CLS_U32_MODULE 1
#define CONFIG_CLS_U32_PERF 1
#define CONFIG_NET_CLS_IND 1
#define CONFIG_CLS_U32_MARK 1
#define CONFIG_NET_CLS_RSVP_MODULE 1
#define CONFIG_NET_CLS_RSVP6_MODULE 1
#define CONFIG_NET_EMATCH 1
#define CONFIG_NET_EMATCH_STACK 32
#define CONFIG_NET_EMATCH_CMP_MODULE 1
#define CONFIG_NET_EMATCH_NBYTE_MODULE 1
#define CONFIG_NET_EMATCH_U32_MODULE 1
#define CONFIG_NET_EMATCH_META_MODULE 1
#define CONFIG_NET_CLS_ACT 1
#define CONFIG_NET_ACT_POLICE_MODULE 1
#define CONFIG_NET_ACT_GACT_MODULE 1
#define CONFIG_GACT_PROB 1
#define CONFIG_NET_ACT_MIRRED_MODULE 1
#define CONFIG_NET_ACT_IPT_MODULE 1
#define CONFIG_NET_ACT_PEDIT_MODULE 1
#undef CONFIG_NET_ACT_SIMP

/*
 * Network testing
 */
#define CONFIG_NET_PKTGEN_MODULE 1
#define CONFIG_NETPOLL 1
#undef CONFIG_NETPOLL_RX
#undef CONFIG_NETPOLL_TRAP
#define CONFIG_NET_POLL_CONTROLLER 1
#define CONFIG_HAMRADIO 1

/*
 * Packet Radio protocols
 */
#define CONFIG_AX25_MODULE 1
#define CONFIG_AX25_DAMA_SLAVE 1
#define CONFIG_NETROM_MODULE 1
#define CONFIG_ROSE_MODULE 1

/*
 * AX.25 network device drivers
 */
#undef CONFIG_BPQETHER
#undef CONFIG_BAYCOM_SER_FDX
#undef CONFIG_BAYCOM_SER_HDX
#undef CONFIG_BAYCOM_PAR
#undef CONFIG_YAM
#define CONFIG_IRDA_MODULE 1

/*
 * IrDA protocols
 */
#define CONFIG_IRLAN_MODULE 1
#define CONFIG_IRNET_MODULE 1
#define CONFIG_IRCOMM_MODULE 1
#define CONFIG_IRDA_ULTRA 1

/*
 * IrDA options
 */
#define CONFIG_IRDA_CACHE_LAST_LSAP 1
#define CONFIG_IRDA_FAST_RR 1
#undef CONFIG_IRDA_DEBUG

/*
 * Infrared-port device drivers
 */

/*
 * SIR device drivers
 */
#undef CONFIG_IRTTY_SIR

/*
 * Dongle support
 */

/*
 * Old SIR device drivers
 */

/*
 * Old Serial dongle support
 */

/*
 * FIR device drivers
 */
#undef CONFIG_USB_IRDA
#define CONFIG_SIGMATEL_FIR_MODULE 1
#undef CONFIG_VLSI_FIR
#define CONFIG_BT_MODULE 1
#define CONFIG_BT_L2CAP_MODULE 1
#define CONFIG_BT_SCO_MODULE 1
#define CONFIG_BT_RFCOMM_MODULE 1
#define CONFIG_BT_RFCOMM_TTY 1
#define CONFIG_BT_BNEP_MODULE 1
#define CONFIG_BT_BNEP_MC_FILTER 1
#define CONFIG_BT_BNEP_PROTO_FILTER 1
#define CONFIG_BT_CMTP_MODULE 1
#define CONFIG_BT_HIDP_MODULE 1

/*
 * Bluetooth device drivers
 */
#define CONFIG_BT_HCIUSB_MODULE 1
#define CONFIG_BT_HCIUSB_SCO 1
#define CONFIG_BT_HCIUART_MODULE 1
#define CONFIG_BT_HCIUART_H4 1
#define CONFIG_BT_HCIUART_BCSP 1
#define CONFIG_BT_HCIUART_BCSP_TXCRC 1
#define CONFIG_BT_HCIBCM203X_MODULE 1
#define CONFIG_BT_HCIBPA10X_MODULE 1
#define CONFIG_BT_HCIBFUSB_MODULE 1
#define CONFIG_BT_HCIVHCI_MODULE 1
#define CONFIG_NETDEVICES 1
#define CONFIG_DUMMY_MODULE 1
#define CONFIG_BONDING_MODULE 1
#define CONFIG_EQUALIZER_MODULE 1
#define CONFIG_TUN_MODULE 1

/*
 * ARCnet devices
 */
#undef CONFIG_ARCNET

/*
 * Ethernet (10 or 100Mbit)
 */
#define CONFIG_NET_ETHERNET 1
#define CONFIG_MII_MODULE 1
#define CONFIG_SUNLANCE 1
#define CONFIG_HAPPYMEAL 1
#define CONFIG_SUNBMAC_MODULE 1
#define CONFIG_SUNQE_MODULE 1
#define CONFIG_SUNGEM 1
#define CONFIG_NET_VENDOR_3COM 1
#define CONFIG_VORTEX_MODULE 1
#define CONFIG_TYPHOON_MODULE 1

/*
 * Tulip family network device support
 */
#define CONFIG_NET_TULIP 1
#define CONFIG_DE2104X_MODULE 1
#define CONFIG_TULIP_MODULE 1
#undef CONFIG_TULIP_MWI
#undef CONFIG_TULIP_MMIO
#define CONFIG_TULIP_NAPI 1
#define CONFIG_TULIP_NAPI_HW_MITIGATION 1
#define CONFIG_DE4X5_MODULE 1
#define CONFIG_WINBOND_840_MODULE 1
#undef CONFIG_DM9102
#undef CONFIG_HP100
#define CONFIG_NET_PCI 1
#define CONFIG_PCNET32_MODULE 1
#undef CONFIG_AMD8111_ETH
#define CONFIG_ADAPTEC_STARFIRE_MODULE 1
#define CONFIG_ADAPTEC_STARFIRE_NAPI 1
#define CONFIG_B44_MODULE 1
#define CONFIG_FORCEDETH_MODULE 1
#define CONFIG_DGRS_MODULE 1
#define CONFIG_EEPRO100_MODULE 1
#define CONFIG_E100_MODULE 1
#define CONFIG_FEALNX_MODULE 1
#define CONFIG_NATSEMI_MODULE 1
#define CONFIG_NE2K_PCI_MODULE 1
#undef CONFIG_8139CP
#define CONFIG_8139TOO_MODULE 1
#undef CONFIG_8139TOO_PIO
#undef CONFIG_8139TOO_TUNE_TWISTER
#undef CONFIG_8139TOO_8129
#undef CONFIG_8139_OLD_RX_RESET
#define CONFIG_SIS900_MODULE 1
#define CONFIG_EPIC100_MODULE 1
#define CONFIG_SUNDANCE_MODULE 1
#define CONFIG_SUNDANCE_MMIO 1
#define CONFIG_VIA_RHINE_MODULE 1
#undef CONFIG_VIA_RHINE_MMIO

/*
 * Ethernet (1000 Mbit)
 */
#define CONFIG_ACENIC_MODULE 1
#undef CONFIG_ACENIC_OMIT_TIGON_I
#define CONFIG_DL2K_MODULE 1
#define CONFIG_E1000_MODULE 1
#define CONFIG_E1000_NAPI 1
#define CONFIG_MYRI_SBUS_MODULE 1
#define CONFIG_NS83820_MODULE 1
#define CONFIG_HAMACHI_MODULE 1
#define CONFIG_YELLOWFIN_MODULE 1
#define CONFIG_R8169_MODULE 1
#define CONFIG_R8169_NAPI 1
#define CONFIG_R8169_VLAN 1
#define CONFIG_SK98LIN_MODULE 1
#define CONFIG_VIA_VELOCITY_MODULE 1
#define CONFIG_TIGON3_MODULE 1
#undef CONFIG_BNX2

/*
 * Ethernet (10000 Mbit)
 */
#define CONFIG_IXGB_MODULE 1
#define CONFIG_IXGB_NAPI 1
#define CONFIG_S2IO_MODULE 1
#define CONFIG_S2IO_NAPI 1
#define CONFIG_2BUFF_MODE 1

/*
 * Token Ring devices
 */
#undef CONFIG_TR

/*
 * Wireless LAN (non-hamradio)
 */
#define CONFIG_NET_RADIO 1

/*
 * Obsolete Wireless cards support (pre-802.11)
 */
#undef CONFIG_STRIP

/*
 * Wireless 802.11b ISA/PCI cards support
 */
#define CONFIG_HERMES_MODULE 1
#define CONFIG_PLX_HERMES_MODULE 1
#define CONFIG_TMD_HERMES_MODULE 1
#define CONFIG_PCI_HERMES_MODULE 1
#define CONFIG_ATMEL_MODULE 1
#define CONFIG_PCI_ATMEL_MODULE 1

/*
 * Prism GT/Duette 802.11(a/b/g) PCI/Cardbus support
 */
#define CONFIG_PRISM54_MODULE 1
#define CONFIG_NET_WIRELESS 1

/*
 * Wan interfaces
 */
#undef CONFIG_WAN

/*
 * ATM drivers
 */
#define CONFIG_ATM_TCP_MODULE 1
#undef CONFIG_ATM_LANAI
#undef CONFIG_ATM_ENI
#undef CONFIG_ATM_FIRESTREAM
#undef CONFIG_ATM_ZATM
#undef CONFIG_ATM_IDT77252
#undef CONFIG_ATM_AMBASSADOR
#undef CONFIG_ATM_HORIZON
#define CONFIG_ATM_FORE200E_MAYBE_MODULE 1
#define CONFIG_ATM_FORE200E_PCA 1
#define CONFIG_ATM_FORE200E_PCA_DEFAULT_FW 1
#define CONFIG_ATM_FORE200E_SBA 1
#define CONFIG_ATM_FORE200E_SBA_DEFAULT_FW 1
#define CONFIG_ATM_FORE200E_USE_TASKLET 1
#define CONFIG_ATM_FORE200E_TX_RETRY 16
#define CONFIG_ATM_FORE200E_DEBUG 0
#define CONFIG_ATM_FORE200E_MODULE 1
#define CONFIG_ATM_HE_MODULE 1
#define CONFIG_ATM_HE_USE_SUNI 1
#define CONFIG_FDDI 1
#undef CONFIG_DEFXX
#define CONFIG_SKFP_MODULE 1
#define CONFIG_HIPPI 1
#undef CONFIG_ROADRUNNER
#define CONFIG_PLIP_MODULE 1
#define CONFIG_PPP_MODULE 1
#define CONFIG_PPP_MULTILINK 1
#define CONFIG_PPP_FILTER 1
#define CONFIG_PPP_ASYNC_MODULE 1
#define CONFIG_PPP_SYNC_TTY_MODULE 1
#define CONFIG_PPP_DEFLATE_MODULE 1
#define CONFIG_PPP_BSDCOMP_MODULE 1
#define CONFIG_PPPOE_MODULE 1
#define CONFIG_PPPOATM_MODULE 1
#define CONFIG_SLIP_MODULE 1
#define CONFIG_SLIP_COMPRESSED 1
#define CONFIG_SLIP_SMART 1
#undef CONFIG_SLIP_MODE_SLIP6
#define CONFIG_NET_FC 1
#define CONFIG_SHAPER_MODULE 1
#define CONFIG_NETCONSOLE_MODULE 1

/*
 * ISDN subsystem
 */
#define CONFIG_ISDN_MODULE 1

/*
 * Old ISDN4Linux
 */
#undef CONFIG_ISDN_I4L

/*
 * CAPI subsystem
 */
#define CONFIG_ISDN_CAPI_MODULE 1
#undef CONFIG_ISDN_DRV_AVMB1_VERBOSE_REASON
#undef CONFIG_ISDN_CAPI_MIDDLEWARE
#define CONFIG_ISDN_CAPI_CAPI20_MODULE 1

/*
 * CAPI hardware drivers
 */

/*
 * Active AVM cards
 */
#define CONFIG_CAPI_AVM 1
#define CONFIG_ISDN_DRV_AVMB1_B1PCI_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_B1PCIV4 1
#define CONFIG_ISDN_DRV_AVMB1_B1PCMCIA_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_T1PCI_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_C4_MODULE 1

/*
 * Active Eicon DIVA Server cards
 */
#define CONFIG_CAPI_EICON 1
#define CONFIG_ISDN_DIVAS_MODULE 1
#define CONFIG_ISDN_DIVAS_BRIPCI 1
#define CONFIG_ISDN_DIVAS_PRIPCI 1
#define CONFIG_ISDN_DIVAS_DIVACAPI_MODULE 1
#define CONFIG_ISDN_DIVAS_USERIDI_MODULE 1
#define CONFIG_ISDN_DIVAS_MAINT_MODULE 1

/*
 * Telephony Support
 */
#define CONFIG_PHONE_MODULE 1
#define CONFIG_PHONE_IXJ_MODULE 1

/*
 * Unix98 PTY support
 */
#define CONFIG_UNIX98_PTYS 1
#define CONFIG_UNIX98_PTY_COUNT 256

/*
 * XFree86 DRI support
 */
#define CONFIG_DRM 1
#define CONFIG_DRM_TDFX_MODULE 1
#undef CONFIG_DRM_R128

/*
 * Input device support
 */
#define CONFIG_INPUT 1

/*
 * Userland interfaces
 */
#define CONFIG_INPUT_MOUSEDEV 1
#define CONFIG_INPUT_MOUSEDEV_PSAUX 1
#define CONFIG_INPUT_MOUSEDEV_SCREEN_X 1024
#define CONFIG_INPUT_MOUSEDEV_SCREEN_Y 768
#undef CONFIG_INPUT_JOYDEV
#undef CONFIG_INPUT_TSDEV
#define CONFIG_INPUT_EVDEV 1
#undef CONFIG_INPUT_EVBUG

/*
 * Input Device Drivers
 */
#define CONFIG_INPUT_KEYBOARD 1
#define CONFIG_KEYBOARD_ATKBD 1
#define CONFIG_KEYBOARD_SUNKBD 1
#define CONFIG_KEYBOARD_LKKBD_MODULE 1
#undef CONFIG_KEYBOARD_XTKBD
#undef CONFIG_KEYBOARD_NEWTON
#define CONFIG_INPUT_MOUSE 1
#define CONFIG_MOUSE_PS2 1
#define CONFIG_MOUSE_SERIAL 1
#define CONFIG_MOUSE_VSXXXAA_MODULE 1
#undef CONFIG_INPUT_JOYSTICK
#undef CONFIG_INPUT_TOUCHSCREEN
#define CONFIG_INPUT_MISC 1
#define CONFIG_INPUT_SPARCSPKR 1
#undef CONFIG_INPUT_UINPUT

/*
 * Hardware I/O ports
 */
#define CONFIG_SERIO 1
#define CONFIG_SERIO_I8042 1
#undef CONFIG_SERIO_SERPORT
#undef CONFIG_SERIO_PARKBD
#define CONFIG_SERIO_PCIPS2_MODULE 1
#define CONFIG_SERIO_LIBPS2 1
#define CONFIG_SERIO_RAW_MODULE 1
#define CONFIG_GAMEPORT_MODULE 1
#undef CONFIG_GAMEPORT_NS558
#undef CONFIG_GAMEPORT_L4
#undef CONFIG_GAMEPORT_EMU10K1
#undef CONFIG_GAMEPORT_VORTEX
#undef CONFIG_GAMEPORT_FM801
#define CONFIG_GAMEPORT_CS461X_MODULE 1

/*
 * I2C support
 */
#define CONFIG_I2C 1
#define CONFIG_I2C_CHARDEV_MODULE 1

/*
 * I2C Algorithms
 */
#define CONFIG_I2C_ALGOBIT 1
#define CONFIG_I2C_ALGOPCF_MODULE 1
#define CONFIG_I2C_ALGOPCA_MODULE 1

/*
 * I2C Hardware Bus support
 */
#define CONFIG_I2C_ALI1535_MODULE 1
#define CONFIG_I2C_ALI1563_MODULE 1
#define CONFIG_I2C_ALI15X3_MODULE 1
#define CONFIG_I2C_AMD756_MODULE 1
#undef CONFIG_I2C_AMD756_S4882
#define CONFIG_I2C_AMD8111_MODULE 1
#define CONFIG_I2C_I801_MODULE 1
#define CONFIG_I2C_I810_MODULE 1
#define CONFIG_I2C_PIIX4_MODULE 1
#define CONFIG_I2C_ISA_MODULE 1
#define CONFIG_I2C_NFORCE2_MODULE 1
#define CONFIG_I2C_PARPORT_MODULE 1
#define CONFIG_I2C_PARPORT_LIGHT_MODULE 1
#define CONFIG_I2C_PROSAVAGE_MODULE 1
#define CONFIG_I2C_SAVAGE4_MODULE 1
#define CONFIG_SCx200_ACB_MODULE 1
#define CONFIG_I2C_SIS5595_MODULE 1
#define CONFIG_I2C_SIS630_MODULE 1
#define CONFIG_I2C_SIS96X_MODULE 1
#define CONFIG_I2C_STUB_MODULE 1
#define CONFIG_I2C_VIA_MODULE 1
#define CONFIG_I2C_VIAPRO_MODULE 1
#define CONFIG_I2C_VOODOO3_MODULE 1
#define CONFIG_I2C_PCA_ISA_MODULE 1

/*
 * Hardware Sensors Chip support
 */
#define CONFIG_I2C_SENSOR_MODULE 1
#define CONFIG_SENSORS_ADM1021_MODULE 1
#define CONFIG_SENSORS_ADM1025_MODULE 1
#define CONFIG_SENSORS_ADM1026_MODULE 1
#define CONFIG_SENSORS_ADM1031_MODULE 1
#define CONFIG_SENSORS_ASB100_MODULE 1
#define CONFIG_SENSORS_DS1621_MODULE 1
#define CONFIG_SENSORS_FSCHER_MODULE 1
#define CONFIG_SENSORS_FSCPOS_MODULE 1
#define CONFIG_SENSORS_GL518SM_MODULE 1
#define CONFIG_SENSORS_GL520SM_MODULE 1
#define CONFIG_SENSORS_IT87_MODULE 1
#define CONFIG_SENSORS_LM63_MODULE 1
#define CONFIG_SENSORS_LM75_MODULE 1
#define CONFIG_SENSORS_LM77_MODULE 1
#define CONFIG_SENSORS_LM78_MODULE 1
#define CONFIG_SENSORS_LM80_MODULE 1
#define CONFIG_SENSORS_LM83_MODULE 1
#define CONFIG_SENSORS_LM85_MODULE 1
#define CONFIG_SENSORS_LM87_MODULE 1
#define CONFIG_SENSORS_LM90_MODULE 1
#undef CONFIG_SENSORS_LM92
#define CONFIG_SENSORS_MAX1619_MODULE 1
#define CONFIG_SENSORS_PC87360_MODULE 1
#define CONFIG_SENSORS_SMSC47B397_MODULE 1
#define CONFIG_SENSORS_SIS5595_MODULE 1
#define CONFIG_SENSORS_SMSC47M1_MODULE 1
#define CONFIG_SENSORS_VIA686A_MODULE 1
#define CONFIG_SENSORS_W83781D_MODULE 1
#define CONFIG_SENSORS_W83L785TS_MODULE 1
#define CONFIG_SENSORS_W83627HF_MODULE 1

/*
 * Other I2C Chip support
 */
#undef CONFIG_SENSORS_DS1337
#define CONFIG_SENSORS_EEPROM_MODULE 1
#define CONFIG_SENSORS_PCF8574_MODULE 1
#define CONFIG_SENSORS_PCF8591_MODULE 1
#define CONFIG_SENSORS_RTC8564_MODULE 1
#undef CONFIG_I2C_DEBUG_CORE
#undef CONFIG_I2C_DEBUG_ALGO
#undef CONFIG_I2C_DEBUG_BUS
#undef CONFIG_I2C_DEBUG_CHIP

/*
 * File systems
 */
#define CONFIG_EXT2_FS 1
#define CONFIG_EXT2_FS_XATTR 1
#define CONFIG_EXT2_FS_POSIX_ACL 1
#define CONFIG_EXT2_FS_SECURITY 1
#define CONFIG_EXT3_FS 1
#define CONFIG_EXT3_FS_XATTR 1
#define CONFIG_EXT3_FS_POSIX_ACL 1
#define CONFIG_EXT3_FS_SECURITY 1
#define CONFIG_JBD 1
#undef CONFIG_JBD_DEBUG
#define CONFIG_FS_MBCACHE 1
#undef CONFIG_REISERFS_FS
#define CONFIG_JFS_FS_MODULE 1
#define CONFIG_JFS_POSIX_ACL 1
#define CONFIG_JFS_SECURITY 1
#undef CONFIG_JFS_DEBUG
#undef CONFIG_JFS_STATISTICS
#define CONFIG_FS_POSIX_ACL 1

/*
 * XFS support
 */
#define CONFIG_XFS_FS_MODULE 1
#define CONFIG_XFS_EXPORT 1
#undef CONFIG_XFS_RT
#define CONFIG_XFS_QUOTA 1
#define CONFIG_XFS_SECURITY 1
#define CONFIG_XFS_POSIX_ACL 1
#define CONFIG_MINIX_FS_MODULE 1
#define CONFIG_ROMFS_FS_MODULE 1
#undef CONFIG_QUOTA
#define CONFIG_QUOTACTL 1
#define CONFIG_DNOTIFY 1
#define CONFIG_AUTOFS_FS_MODULE 1
#define CONFIG_AUTOFS4_FS_MODULE 1

/*
 * CD-ROM/DVD Filesystems
 */
#define CONFIG_ISO9660_FS_MODULE 1
#define CONFIG_JOLIET 1
#undef CONFIG_ZISOFS
#define CONFIG_UDF_FS_MODULE 1
#define CONFIG_UDF_NLS 1

/*
 * DOS/FAT/NT Filesystems
 */
#define CONFIG_FAT_FS_MODULE 1
#define CONFIG_MSDOS_FS_MODULE 1
#define CONFIG_VFAT_FS_MODULE 1
#define CONFIG_FAT_DEFAULT_CODEPAGE 437
#define CONFIG_FAT_DEFAULT_IOCHARSET "iso8859-1"
#undef CONFIG_NTFS_FS

/*
 * Pseudo filesystems
 */
#define CONFIG_PROC_FS 1
#define CONFIG_PROC_KCORE 1
#define CONFIG_SYSFS 1
#define CONFIG_DEVFS_FS 1
#define CONFIG_DEVFS_MOUNT 1
#undef CONFIG_DEVFS_DEBUG
#define CONFIG_DEVPTS_FS_XATTR 1
#undef CONFIG_DEVPTS_FS_SECURITY
#define CONFIG_TMPFS 1
#define CONFIG_TMPFS_XATTR 1
#define CONFIG_TMPFS_SECURITY 1
#define CONFIG_HUGETLBFS 1
#define CONFIG_HUGETLB_PAGE 1
#define CONFIG_RAMFS 1

/*
 * Miscellaneous filesystems
 */
#define CONFIG_ADFS_FS_MODULE 1
#undef CONFIG_ADFS_FS_RW
#define CONFIG_AFFS_FS_MODULE 1
#define CONFIG_HFS_FS_MODULE 1
#define CONFIG_HFSPLUS_FS_MODULE 1
#define CONFIG_BEFS_FS_MODULE 1
#undef CONFIG_BEFS_DEBUG
#define CONFIG_BFS_FS_MODULE 1
#define CONFIG_EFS_FS_MODULE 1
#define CONFIG_CRAMFS_MODULE 1
#define CONFIG_VXFS_FS_MODULE 1
#define CONFIG_HPFS_FS_MODULE 1
#define CONFIG_QNX4FS_FS_MODULE 1
#define CONFIG_SYSV_FS_MODULE 1
#define CONFIG_UFS_FS_MODULE 1
#define CONFIG_UFS_FS_WRITE 1

/*
 * Network File Systems
 */
#define CONFIG_NFS_FS_MODULE 1
#define CONFIG_NFS_V3 1
#define CONFIG_NFS_V4 1
#define CONFIG_NFS_DIRECTIO 1
#define CONFIG_NFSD_MODULE 1
#define CONFIG_NFSD_V3 1
#define CONFIG_NFSD_V4 1
#define CONFIG_NFSD_TCP 1
#define CONFIG_LOCKD_MODULE 1
#define CONFIG_LOCKD_V4 1
#define CONFIG_EXPORTFS_MODULE 1
#define CONFIG_SUNRPC_MODULE 1
#define CONFIG_SUNRPC_GSS_MODULE 1
#define CONFIG_RPCSEC_GSS_KRB5_MODULE 1
#define CONFIG_RPCSEC_GSS_SPKM3_MODULE 1
#define CONFIG_SMB_FS_MODULE 1
#undef CONFIG_SMB_NLS_DEFAULT
#define CONFIG_CIFS_MODULE 1
#undef CONFIG_CIFS_STATS
#undef CONFIG_CIFS_XATTR
#undef CONFIG_CIFS_EXPERIMENTAL
#define CONFIG_NCP_FS_MODULE 1
#undef CONFIG_NCPFS_PACKET_SIGNING
#undef CONFIG_NCPFS_IOCTL_LOCKING
#undef CONFIG_NCPFS_STRONG
#undef CONFIG_NCPFS_NFS_NS
#undef CONFIG_NCPFS_OS2_NS
#undef CONFIG_NCPFS_SMALLDOS
#undef CONFIG_NCPFS_NLS
#undef CONFIG_NCPFS_EXTRAS
#define CONFIG_CODA_FS_MODULE 1
#undef CONFIG_CODA_FS_OLD_API
#define CONFIG_AFS_FS_MODULE 1
#define CONFIG_RXRPC_MODULE 1

/*
 * Partition Types
 */
#undef CONFIG_PARTITION_ADVANCED
#define CONFIG_MSDOS_PARTITION 1
#define CONFIG_SUN_PARTITION 1

/*
 * Native Language Support
 */
#define CONFIG_NLS 1
#define CONFIG_NLS_DEFAULT "iso8859-1"
#define CONFIG_NLS_CODEPAGE_437_MODULE 1
#define CONFIG_NLS_CODEPAGE_737_MODULE 1
#define CONFIG_NLS_CODEPAGE_775_MODULE 1
#define CONFIG_NLS_CODEPAGE_850_MODULE 1
#define CONFIG_NLS_CODEPAGE_852_MODULE 1
#define CONFIG_NLS_CODEPAGE_855_MODULE 1
#define CONFIG_NLS_CODEPAGE_857_MODULE 1
#define CONFIG_NLS_CODEPAGE_860_MODULE 1
#define CONFIG_NLS_CODEPAGE_861_MODULE 1
#define CONFIG_NLS_CODEPAGE_862_MODULE 1
#define CONFIG_NLS_CODEPAGE_863_MODULE 1
#define CONFIG_NLS_CODEPAGE_864_MODULE 1
#define CONFIG_NLS_CODEPAGE_865_MODULE 1
#define CONFIG_NLS_CODEPAGE_866_MODULE 1
#define CONFIG_NLS_CODEPAGE_869_MODULE 1
#define CONFIG_NLS_CODEPAGE_936_MODULE 1
#define CONFIG_NLS_CODEPAGE_950_MODULE 1
#define CONFIG_NLS_CODEPAGE_932_MODULE 1
#define CONFIG_NLS_CODEPAGE_949_MODULE 1
#define CONFIG_NLS_CODEPAGE_874_MODULE 1
#define CONFIG_NLS_ISO8859_8_MODULE 1
#define CONFIG_NLS_CODEPAGE_1250_MODULE 1
#define CONFIG_NLS_CODEPAGE_1251_MODULE 1
#define CONFIG_NLS_ASCII_MODULE 1
#define CONFIG_NLS_ISO8859_1_MODULE 1
#define CONFIG_NLS_ISO8859_2_MODULE 1
#define CONFIG_NLS_ISO8859_3_MODULE 1
#define CONFIG_NLS_ISO8859_4_MODULE 1
#define CONFIG_NLS_ISO8859_5_MODULE 1
#define CONFIG_NLS_ISO8859_6_MODULE 1
#define CONFIG_NLS_ISO8859_7_MODULE 1
#define CONFIG_NLS_ISO8859_9_MODULE 1
#define CONFIG_NLS_ISO8859_13_MODULE 1
#define CONFIG_NLS_ISO8859_14_MODULE 1
#define CONFIG_NLS_ISO8859_15_MODULE 1
#define CONFIG_NLS_KOI8_R_MODULE 1
#define CONFIG_NLS_KOI8_U_MODULE 1
#define CONFIG_NLS_UTF8_MODULE 1

/*
 * Multimedia devices
 */
#define CONFIG_VIDEO_DEV 1

/*
 * Video For Linux
 */

/*
 * Video Adapters
 */
#define CONFIG_VIDEO_BT848_MODULE 1
#define CONFIG_VIDEO_BWQCAM_MODULE 1
#define CONFIG_VIDEO_CQCAM_MODULE 1
#define CONFIG_VIDEO_W9966_MODULE 1
#define CONFIG_VIDEO_CPIA_MODULE 1
#define CONFIG_VIDEO_CPIA_PP_MODULE 1
#define CONFIG_VIDEO_CPIA_USB_MODULE 1
#define CONFIG_VIDEO_SAA5246A_MODULE 1
#define CONFIG_VIDEO_SAA5249_MODULE 1
#define CONFIG_TUNER_3036_MODULE 1
#undef CONFIG_VIDEO_STRADIS
#undef CONFIG_VIDEO_ZORAN
#undef CONFIG_VIDEO_SAA7134
#define CONFIG_VIDEO_MXB_MODULE 1
#define CONFIG_VIDEO_DPC_MODULE 1
#define CONFIG_VIDEO_HEXIUM_ORION_MODULE 1
#define CONFIG_VIDEO_HEXIUM_GEMINI_MODULE 1
#define CONFIG_VIDEO_CX88_MODULE 1
#undef CONFIG_VIDEO_CX88_DVB
#define CONFIG_VIDEO_OVCAMCHIP_MODULE 1

/*
 * Radio Adapters
 */
#define CONFIG_RADIO_GEMTEK_PCI_MODULE 1
#define CONFIG_RADIO_MAXIRADIO_MODULE 1
#define CONFIG_RADIO_MAESTRO_MODULE 1

/*
 * Digital Video Broadcasting Devices
 */
#define CONFIG_DVB 1
#define CONFIG_DVB_CORE_MODULE 1

/*
 * Supported SAA7146 based PCI Adapters
 */
#define CONFIG_DVB_AV7110_MODULE 1
#undef CONFIG_DVB_AV7110_OSD
#define CONFIG_DVB_BUDGET_MODULE 1
#define CONFIG_DVB_BUDGET_CI_MODULE 1
#define CONFIG_DVB_BUDGET_AV_MODULE 1
#define CONFIG_DVB_BUDGET_PATCH_MODULE 1

/*
 * Supported USB Adapters
 */
#undef CONFIG_DVB_TTUSB_BUDGET
#define CONFIG_DVB_TTUSB_DEC_MODULE 1
#define CONFIG_DVB_DIBUSB_MODULE 1
#undef CONFIG_DVB_DIBUSB_MISDESIGNED_DEVICES
#define CONFIG_DVB_DIBCOM_DEBUG 1
#define CONFIG_DVB_CINERGYT2_MODULE 1
#undef CONFIG_DVB_CINERGYT2_TUNING

/*
 * Supported FlexCopII (B2C2) Adapters
 */
#undef CONFIG_DVB_B2C2_FLEXCOP
#define CONFIG_DVB_B2C2_SKYSTAR_MODULE 1

/*
 * Supported BT878 Adapters
 */
#define CONFIG_DVB_BT8XX_MODULE 1

/*
 * Supported DVB Frontends
 */

/*
 * Customise DVB Frontends
 */

/*
 * DVB-S (satellite) frontends
 */
#define CONFIG_DVB_STV0299_MODULE 1
#define CONFIG_DVB_CX24110_MODULE 1
#define CONFIG_DVB_TDA8083_MODULE 1
#define CONFIG_DVB_TDA80XX_MODULE 1
#define CONFIG_DVB_MT312_MODULE 1
#define CONFIG_DVB_VES1X93_MODULE 1

/*
 * DVB-T (terrestrial) frontends
 */
#define CONFIG_DVB_SP8870_MODULE 1
#define CONFIG_DVB_SP887X_MODULE 1
#define CONFIG_DVB_CX22700_MODULE 1
#define CONFIG_DVB_CX22702_MODULE 1
#define CONFIG_DVB_L64781_MODULE 1
#define CONFIG_DVB_TDA1004X_MODULE 1
#define CONFIG_DVB_NXT6000_MODULE 1
#define CONFIG_DVB_MT352_MODULE 1
#define CONFIG_DVB_DIB3000MB_MODULE 1
#define CONFIG_DVB_DIB3000MC_MODULE 1

/*
 * DVB-C (cable) frontends
 */
#define CONFIG_DVB_ATMEL_AT76C651_MODULE 1
#define CONFIG_DVB_VES1820_MODULE 1
#define CONFIG_DVB_TDA10021_MODULE 1
#define CONFIG_DVB_STV0297_MODULE 1

/*
 * ATSC (North American/Korean Terresterial DTV) frontends
 */
#define CONFIG_DVB_NXT2002_MODULE 1
#define CONFIG_DVB_OR51211_MODULE 1
#undef CONFIG_DVB_OR51132
#define CONFIG_VIDEO_SAA7146_MODULE 1
#define CONFIG_VIDEO_SAA7146_VV_MODULE 1
#define CONFIG_VIDEO_VIDEOBUF_MODULE 1
#define CONFIG_VIDEO_TUNER_MODULE 1
#define CONFIG_VIDEO_BUF_MODULE 1
#define CONFIG_VIDEO_BTCX_MODULE 1
#define CONFIG_VIDEO_IR_MODULE 1
#define CONFIG_VIDEO_TVEEPROM_MODULE 1

/*
 * Sound
 */
#define CONFIG_SOUND_MODULE 1

/*
 * Advanced Linux Sound Architecture
 */
#define CONFIG_SND_MODULE 1
#define CONFIG_SND_TIMER_MODULE 1
#define CONFIG_SND_PCM_MODULE 1
#define CONFIG_SND_HWDEP_MODULE 1
#define CONFIG_SND_RAWMIDI_MODULE 1
#define CONFIG_SND_SEQUENCER_MODULE 1
#define CONFIG_SND_SEQ_DUMMY_MODULE 1
#define CONFIG_SND_OSSEMUL 1
#define CONFIG_SND_MIXER_OSS_MODULE 1
#define CONFIG_SND_PCM_OSS_MODULE 1
#define CONFIG_SND_SEQUENCER_OSS 1
#undef CONFIG_SND_RTCTIMER
#undef CONFIG_SND_VERBOSE_PRINTK
#undef CONFIG_SND_DEBUG

/*
 * Generic devices
 */
#define CONFIG_SND_MPU401_UART_MODULE 1
#define CONFIG_SND_OPL3_LIB_MODULE 1
#define CONFIG_SND_VX_LIB_MODULE 1
#define CONFIG_SND_DUMMY_MODULE 1
#define CONFIG_SND_VIRMIDI_MODULE 1
#undef CONFIG_SND_MTPAV
#undef CONFIG_SND_SERIAL_U16550
#undef CONFIG_SND_MPU401

/*
 * PCI devices
 */
#define CONFIG_SND_AC97_CODEC_MODULE 1
#define CONFIG_SND_ALI5451_MODULE 1
#define CONFIG_SND_ATIIXP_MODULE 1
#define CONFIG_SND_ATIIXP_MODEM_MODULE 1
#define CONFIG_SND_AU8810_MODULE 1
#define CONFIG_SND_AU8820_MODULE 1
#define CONFIG_SND_AU8830_MODULE 1
#define CONFIG_SND_AZT3328_MODULE 1
#define CONFIG_SND_BT87X_MODULE 1
#undef CONFIG_SND_BT87X_OVERCLOCK
#define CONFIG_SND_CS46XX_MODULE 1
#undef CONFIG_SND_CS46XX_NEW_DSP
#define CONFIG_SND_CS4281_MODULE 1
#define CONFIG_SND_EMU10K1_MODULE 1
#define CONFIG_SND_EMU10K1X_MODULE 1
#define CONFIG_SND_CA0106_MODULE 1
#define CONFIG_SND_KORG1212_MODULE 1
#define CONFIG_SND_MIXART_MODULE 1
#define CONFIG_SND_NM256_MODULE 1
#undef CONFIG_SND_RME32
#undef CONFIG_SND_RME96
#undef CONFIG_SND_RME9652
#undef CONFIG_SND_HDSP
#define CONFIG_SND_TRIDENT_MODULE 1
#define CONFIG_SND_YMFPCI_MODULE 1
#define CONFIG_SND_ALS4000_MODULE 1
#define CONFIG_SND_CMIPCI_MODULE 1
#define CONFIG_SND_ENS1370_MODULE 1
#define CONFIG_SND_ENS1371_MODULE 1
#define CONFIG_SND_ES1938_MODULE 1
#define CONFIG_SND_ES1968_MODULE 1
#define CONFIG_SND_MAESTRO3_MODULE 1
#define CONFIG_SND_FM801_MODULE 1
#define CONFIG_SND_FM801_TEA575X_MODULE 1
#define CONFIG_SND_ICE1712_MODULE 1
#undef CONFIG_SND_ICE1724
#define CONFIG_SND_INTEL8X0_MODULE 1
#define CONFIG_SND_INTEL8X0M_MODULE 1
#define CONFIG_SND_SONICVIBES_MODULE 1
#undef CONFIG_SND_VIA82XX
#define CONFIG_SND_VIA82XX_MODEM_MODULE 1
#define CONFIG_SND_VX222_MODULE 1
#undef CONFIG_SND_HDA_INTEL

/*
 * USB devices
 */
#undef CONFIG_SND_USB_AUDIO

/*
 * ALSA Sparc devices
 */
#define CONFIG_SND_SUN_AMD7930_MODULE 1
#define CONFIG_SND_SUN_CS4231_MODULE 1

/*
 * USB support
 */
#define CONFIG_USB_ARCH_HAS_HCD 1
#define CONFIG_USB_ARCH_HAS_OHCI 1
#define CONFIG_USB 1
#undef CONFIG_USB_DEBUG

/*
 * Miscellaneous USB options
 */
#define CONFIG_USB_DEVICEFS 1
#undef CONFIG_USB_BANDWIDTH
#undef CONFIG_USB_DYNAMIC_MINORS
#undef CONFIG_USB_OTG

/*
 * USB Host Controller Drivers
 */
#define CONFIG_USB_EHCI_HCD_MODULE 1
#undef CONFIG_USB_EHCI_SPLIT_ISO
#undef CONFIG_USB_EHCI_ROOT_HUB_TT
#define CONFIG_USB_OHCI_HCD 1
#undef CONFIG_USB_OHCI_BIG_ENDIAN
#define CONFIG_USB_OHCI_LITTLE_ENDIAN 1
#define CONFIG_USB_UHCI_HCD_MODULE 1
#define CONFIG_USB_SL811_HCD_MODULE 1

/*
 * USB Device Class drivers
 */
#undef CONFIG_USB_AUDIO

/*
 * USB Bluetooth TTY can only be used with disabled Bluetooth subsystem
 */
#undef CONFIG_USB_MIDI
#define CONFIG_USB_ACM_MODULE 1
#define CONFIG_USB_PRINTER_MODULE 1

/*
 * NOTE: USB_STORAGE enables SCSI, and 'SCSI disk support' may also be needed; see USB_STORAGE Help for more information
 */
#define CONFIG_USB_STORAGE_MODULE 1
#undef CONFIG_USB_STORAGE_DEBUG
#undef CONFIG_USB_STORAGE_DATAFAB
#define CONFIG_USB_STORAGE_FREECOM 1
#define CONFIG_USB_STORAGE_ISD200 1
#define CONFIG_USB_STORAGE_DPCM 1
#undef CONFIG_USB_STORAGE_USBAT
#define CONFIG_USB_STORAGE_SDDR09 1
#define CONFIG_USB_STORAGE_SDDR55 1
#undef CONFIG_USB_STORAGE_JUMPSHOT

/*
 * USB Input Devices
 */
#define CONFIG_USB_HID 1
#define CONFIG_USB_HIDINPUT 1
#undef CONFIG_HID_FF
#define CONFIG_USB_HIDDEV 1
#undef CONFIG_USB_AIPTEK
#define CONFIG_USB_WACOM_MODULE 1
#define CONFIG_USB_KBTAB_MODULE 1
#undef CONFIG_USB_POWERMATE
#define CONFIG_USB_MTOUCH_MODULE 1
#define CONFIG_USB_EGALAX_MODULE 1
#undef CONFIG_USB_XPAD
#define CONFIG_USB_ATI_REMOTE_MODULE 1

/*
 * USB Imaging devices
 */
#define CONFIG_USB_MDC800_MODULE 1
#define CONFIG_USB_MICROTEK_MODULE 1

/*
 * USB Multimedia devices
 */
#undef CONFIG_USB_DABUSB
#undef CONFIG_USB_VICAM
#undef CONFIG_USB_DSBR
#undef CONFIG_USB_IBMCAM
#undef CONFIG_USB_KONICAWC
#undef CONFIG_USB_OV511
#undef CONFIG_USB_SE401
#define CONFIG_USB_SN9C102_MODULE 1
#undef CONFIG_USB_STV680
#define CONFIG_USB_W9968CF_MODULE 1
#undef CONFIG_USB_PWC

/*
 * USB Network Adapters
 */
#define CONFIG_USB_CATC_MODULE 1
#define CONFIG_USB_KAWETH_MODULE 1
#define CONFIG_USB_PEGASUS_MODULE 1
#define CONFIG_USB_RTL8150_MODULE 1
#define CONFIG_USB_USBNET_MODULE 1

/*
 * USB Host-to-Host Cables
 */
#define CONFIG_USB_ALI_M5632 1
#define CONFIG_USB_AN2720 1
#define CONFIG_USB_BELKIN 1
#define CONFIG_USB_GENESYS 1
#define CONFIG_USB_NET1080 1
#define CONFIG_USB_PL2301 1
#define CONFIG_USB_KC2190 1

/*
 * Intelligent USB Devices/Gadgets
 */
#define CONFIG_USB_ARMLINUX 1
#define CONFIG_USB_EPSON2888 1
#define CONFIG_USB_ZAURUS 1
#define CONFIG_USB_CDCETHER 1

/*
 * USB Network Adapters
 */
#define CONFIG_USB_AX8817X 1
#undef CONFIG_USB_ZD1201
#define CONFIG_USB_MON 1

/*
 * USB port drivers
 */
#define CONFIG_USB_USS720_MODULE 1

/*
 * USB Serial Converter support
 */
#define CONFIG_USB_SERIAL_MODULE 1
#define CONFIG_USB_SERIAL_GENERIC 1
#undef CONFIG_USB_SERIAL_AIRPRIME
#define CONFIG_USB_SERIAL_BELKIN_MODULE 1
#define CONFIG_USB_SERIAL_DIGI_ACCELEPORT_MODULE 1
#undef CONFIG_USB_SERIAL_CP2101
#define CONFIG_USB_SERIAL_CYPRESS_M8_MODULE 1
#define CONFIG_USB_SERIAL_EMPEG_MODULE 1
#define CONFIG_USB_SERIAL_FTDI_SIO_MODULE 1
#undef CONFIG_USB_SERIAL_VISOR
#define CONFIG_USB_SERIAL_IPAQ_MODULE 1
#undef CONFIG_USB_SERIAL_IR
#define CONFIG_USB_SERIAL_EDGEPORT_MODULE 1
#undef CONFIG_USB_SERIAL_EDGEPORT_TI
#define CONFIG_USB_SERIAL_GARMIN_MODULE 1
#define CONFIG_USB_SERIAL_IPW_MODULE 1
#define CONFIG_USB_SERIAL_KEYSPAN_PDA_MODULE 1
#define CONFIG_USB_SERIAL_KEYSPAN_MODULE 1
#undef CONFIG_USB_SERIAL_KEYSPAN_MPR
#undef CONFIG_USB_SERIAL_KEYSPAN_USA28
#undef CONFIG_USB_SERIAL_KEYSPAN_USA28X
#undef CONFIG_USB_SERIAL_KEYSPAN_USA28XA
#undef CONFIG_USB_SERIAL_KEYSPAN_USA28XB
#undef CONFIG_USB_SERIAL_KEYSPAN_USA19
#undef CONFIG_USB_SERIAL_KEYSPAN_USA18X
#undef CONFIG_USB_SERIAL_KEYSPAN_USA19W
#undef CONFIG_USB_SERIAL_KEYSPAN_USA19QW
#undef CONFIG_USB_SERIAL_KEYSPAN_USA19QI
#undef CONFIG_USB_SERIAL_KEYSPAN_USA49W
#undef CONFIG_USB_SERIAL_KEYSPAN_USA49WLC
#define CONFIG_USB_SERIAL_KLSI_MODULE 1
#undef CONFIG_USB_SERIAL_KOBIL_SCT
#define CONFIG_USB_SERIAL_MCT_U232_MODULE 1
#define CONFIG_USB_SERIAL_PL2303_MODULE 1
#undef CONFIG_USB_SERIAL_HP4X
#undef CONFIG_USB_SERIAL_SAFE
#define CONFIG_USB_SERIAL_TI_MODULE 1
#define CONFIG_USB_SERIAL_CYBERJACK_MODULE 1
#define CONFIG_USB_SERIAL_XIRCOM_MODULE 1
#define CONFIG_USB_SERIAL_OMNINET_MODULE 1
#define CONFIG_USB_EZUSB 1

/*
 * USB Miscellaneous drivers
 */
#define CONFIG_USB_EMI62_MODULE 1
#define CONFIG_USB_EMI26_MODULE 1
#define CONFIG_USB_AUERSWALD_MODULE 1
#define CONFIG_USB_RIO500_MODULE 1
#define CONFIG_USB_LEGOTOWER_MODULE 1
#define CONFIG_USB_LCD_MODULE 1
#define CONFIG_USB_LED_MODULE 1
#define CONFIG_USB_CYTHERM_MODULE 1
#define CONFIG_USB_PHIDGETKIT_MODULE 1
#define CONFIG_USB_PHIDGETSERVO_MODULE 1
#define CONFIG_USB_IDMOUSE_MODULE 1
#undef CONFIG_USB_SISUSBVGA
#define CONFIG_USB_TEST_MODULE 1

/*
 * USB ATM/DSL drivers
 */
#define CONFIG_USB_ATM_MODULE 1
#define CONFIG_USB_SPEEDTOUCH_MODULE 1

/*
 * USB Gadget Support
 */
#undef CONFIG_USB_GADGET

/*
 * InfiniBand support
 */
#define CONFIG_INFINIBAND_MODULE 1
#define CONFIG_INFINIBAND_MTHCA_MODULE 1
#undef CONFIG_INFINIBAND_MTHCA_DEBUG
#define CONFIG_INFINIBAND_IPOIB_MODULE 1
#undef CONFIG_INFINIBAND_IPOIB_DEBUG

/*
 * Watchdog Cards
 */
#define CONFIG_WATCHDOG 1
#undef CONFIG_WATCHDOG_NOWAYOUT

/*
 * Watchdog Device Drivers
 */
#define CONFIG_SOFT_WATCHDOG_MODULE 1
#define CONFIG_WATCHDOG_CP1XXX_MODULE 1
#define CONFIG_WATCHDOG_RIO_MODULE 1

/*
 * PCI-based Watchdog Cards
 */
#define CONFIG_PCIPCWATCHDOG_MODULE 1
#define CONFIG_WDTPCI_MODULE 1
#define CONFIG_WDT_501_PCI 1

/*
 * USB-based Watchdog Cards
 */
#define CONFIG_USBPCWATCHDOG_MODULE 1

/*
 * Profiling support
 */
#define CONFIG_PROFILING 1
#define CONFIG_OPROFILE_MODULE 1

/*
 * Kernel hacking
 */
#undef CONFIG_PRINTK_TIME
#define CONFIG_DEBUG_KERNEL 1
#define CONFIG_MAGIC_SYSRQ 1
#define CONFIG_LOG_BUF_SHIFT 15
#define CONFIG_SCHEDSTATS 1
#undef CONFIG_DEBUG_SLAB
#undef CONFIG_DEBUG_SPINLOCK
#undef CONFIG_DEBUG_SPINLOCK_SLEEP
#undef CONFIG_DEBUG_KOBJECT
#define CONFIG_DEBUG_BUGVERBOSE 1
#undef CONFIG_DEBUG_INFO
#define CONFIG_DEBUG_FS 1
#undef CONFIG_DEBUG_STACK_USAGE
#define CONFIG_KPROBES 1
#undef CONFIG_DEBUG_DCFLUSH
#undef CONFIG_STACK_DEBUG
#undef CONFIG_DEBUG_BOOTMEM
#define CONFIG_HAVE_DEC_LOCK 1

/*
 * Security options
 */
#define CONFIG_KEYS 1
#undef CONFIG_KEYS_DEBUG_PROC_KEYS
#undef CONFIG_SECURITY

/*
 * Cryptographic options
 */
#define CONFIG_CRYPTO 1
#define CONFIG_CRYPTO_HMAC 1
#define CONFIG_CRYPTO_NULL_MODULE 1
#define CONFIG_CRYPTO_MD4 1
#define CONFIG_CRYPTO_MD5 1
#define CONFIG_CRYPTO_SHA1 1
#define CONFIG_CRYPTO_SHA256_MODULE 1
#define CONFIG_CRYPTO_SHA512_MODULE 1
#define CONFIG_CRYPTO_WP512_MODULE 1
#define CONFIG_CRYPTO_TGR192_MODULE 1
#define CONFIG_CRYPTO_DES 1
#define CONFIG_CRYPTO_BLOWFISH_MODULE 1
#define CONFIG_CRYPTO_TWOFISH_MODULE 1
#define CONFIG_CRYPTO_SERPENT_MODULE 1
#define CONFIG_CRYPTO_AES_MODULE 1
#define CONFIG_CRYPTO_CAST5_MODULE 1
#define CONFIG_CRYPTO_CAST6_MODULE 1
#define CONFIG_CRYPTO_TEA_MODULE 1
#define CONFIG_CRYPTO_ARC4_MODULE 1
#define CONFIG_CRYPTO_KHAZAD_MODULE 1
#define CONFIG_CRYPTO_ANUBIS_MODULE 1
#define CONFIG_CRYPTO_DEFLATE 1
#define CONFIG_CRYPTO_MICHAEL_MIC_MODULE 1
#define CONFIG_CRYPTO_CRC32C_MODULE 1
#define CONFIG_CRYPTO_TEST_MODULE 1

/*
 * Hardware crypto devices
 */

/*
 * Library routines
 */
#define CONFIG_CRC_CCITT_MODULE 1
#define CONFIG_CRC32 1
#define CONFIG_LIBCRC32C_MODULE 1
#define CONFIG_ZLIB_INFLATE 1
#define CONFIG_ZLIB_DEFLATE 1
