/*
 * Automatically generated C config: don't edit
 * Linux kernel version: 2.6.12
 * Sat Jun 18 16:12:35 2005
 */
#define AUTOCONF_INCLUDED
#define CONFIG_64BIT 1
#define CONFIG_MMU 1
#define CONFIG_RWSEM_XCHGADD_ALGORITHM 1
#define CONFIG_GENERIC_CALIBRATE_DELAY 1
#define CONFIG_GENERIC_ISA_DMA 1
#define CONFIG_HAVE_DEC_LOCK 1
#define CONFIG_EARLY_PRINTK 1
#define CONFIG_COMPAT 1
#define CONFIG_SCHED_NO_NO_OMIT_FRAME_POINTER 1
#define CONFIG_FORCE_MAX_ZONEORDER 13

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1
#define CONFIG_CLEAN_COMPILE 1
#define CONFIG_LOCK_KERNEL 1
#define CONFIG_INIT_ENV_ARG_LIMIT 32

/*
 * General setup
 */
#define CONFIG_LOCALVERSION ""
#define CONFIG_SWAP 1
#define CONFIG_SYSVIPC 1
#define CONFIG_POSIX_MQUEUE 1
#undef CONFIG_BSD_PROCESS_ACCT
#define CONFIG_SYSCTL 1
#undef CONFIG_AUDIT
#define CONFIG_HOTPLUG 1
#define CONFIG_KOBJECT_UEVENT 1
#define CONFIG_IKCONFIG 1
#define CONFIG_IKCONFIG_PROC 1
#define CONFIG_CPUSETS 1
#undef CONFIG_EMBEDDED
#define CONFIG_KALLSYMS 1
#undef CONFIG_KALLSYMS_ALL
#undef CONFIG_KALLSYMS_EXTRA_PASS
#define CONFIG_PRINTK 1
#define CONFIG_BUG 1
#define CONFIG_BASE_FULL 1
#define CONFIG_FUTEX 1
#define CONFIG_EPOLL 1
#define CONFIG_SHMEM 1
#define CONFIG_CC_ALIGN_FUNCTIONS 0
#define CONFIG_CC_ALIGN_LABELS 0
#define CONFIG_CC_ALIGN_LOOPS 0
#define CONFIG_CC_ALIGN_JUMPS 0
#undef CONFIG_TINY_SHMEM
#define CONFIG_BASE_SMALL 0

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#define CONFIG_MODULE_UNLOAD 1
#undef CONFIG_MODULE_FORCE_UNLOAD
#define CONFIG_OBSOLETE_MODPARM 1
#define CONFIG_MODVERSIONS 1
#define CONFIG_MODULE_SRCVERSION_ALL 1
#define CONFIG_KMOD 1
#define CONFIG_STOP_MACHINE 1
#define CONFIG_SYSVIPC_COMPAT 1

/*
 * Platform support
 */
#undef CONFIG_PPC_ISERIES
#define CONFIG_PPC_MULTIPLATFORM 1
#define CONFIG_PPC_PSERIES 1
#define CONFIG_PPC_PMAC 1
#define CONFIG_PPC_MAPLE 1
#define CONFIG_PPC 1
#define CONFIG_PPC64 1
#define CONFIG_PPC_OF 1
#define CONFIG_ALTIVEC 1
#define CONFIG_PPC_SPLPAR 1
#define CONFIG_IBMVIO 1
#define CONFIG_U3_DART 1
#define CONFIG_MPIC_BROKEN_U3 1
#define CONFIG_PPC_PMAC64 1
#define CONFIG_BOOTX_TEXT 1
#undef CONFIG_POWER4_ONLY
#define CONFIG_IOMMU_VMERGE 1
#define CONFIG_SMP 1
#define CONFIG_NR_CPUS 32
#define CONFIG_DISCONTIGMEM 1
#undef CONFIG_NUMA
#undef CONFIG_SCHED_SMT
#undef CONFIG_PREEMPT
#define CONFIG_EEH 1
#define CONFIG_GENERIC_HARDIRQS 1
#define CONFIG_PPC_RTAS 1
#define CONFIG_RTAS_PROC 1
#define CONFIG_RTAS_FLASH_MODULE 1
#define CONFIG_SCANLOG_MODULE 1
#define CONFIG_LPARCFG 1
#define CONFIG_SECCOMP 1
#define CONFIG_ISA_DMA_API 1

/*
 * General setup
 */
#define CONFIG_PCI 1
#define CONFIG_PCI_DOMAINS 1
#define CONFIG_BINFMT_ELF 1
#define CONFIG_BINFMT_MISC_MODULE 1
#undef CONFIG_PCI_LEGACY_PROC
#undef CONFIG_PCI_NAMES
#undef CONFIG_PCI_DEBUG
#define CONFIG_HOTPLUG_CPU 1

/*
 * PCCARD (PCMCIA/CardBus) support
 */
#undef CONFIG_PCCARD

/*
 * PCI Hotplug Support
 */
#define CONFIG_HOTPLUG_PCI_MODULE 1
#undef CONFIG_HOTPLUG_PCI_FAKE
#undef CONFIG_HOTPLUG_PCI_CPCI
#undef CONFIG_HOTPLUG_PCI_SHPC
#define CONFIG_HOTPLUG_PCI_RPA_MODULE 1
#define CONFIG_HOTPLUG_PCI_RPA_DLPAR_MODULE 1
#define CONFIG_PROC_DEVICETREE 1
#undef CONFIG_CMDLINE_BOOL

/*
 * Device Drivers
 */

/*
 * Generic Driver Options
 */
#define CONFIG_STANDALONE 1
#define CONFIG_PREVENT_FIRMWARE_BUILD 1
#define CONFIG_FW_LOADER 1
#undef CONFIG_DEBUG_DRIVER

/*
 * Memory Technology Devices (MTD)
 */
#undef CONFIG_MTD

/*
 * Parallel port support
 */
#define CONFIG_PARPORT_MODULE 1
#define CONFIG_PARPORT_PC_MODULE 1
#undef CONFIG_PARPORT_SERIAL
#undef CONFIG_PARPORT_PC_FIFO
#undef CONFIG_PARPORT_PC_SUPERIO
#undef CONFIG_PARPORT_GSC
#undef CONFIG_PARPORT_1284

/*
 * Plug and Play support
 */

/*
 * Block devices
 */
#define CONFIG_BLK_DEV_FD 1
#undef CONFIG_PARIDE
#undef CONFIG_BLK_CPQ_DA
#undef CONFIG_BLK_CPQ_CISS_DA
#undef CONFIG_BLK_DEV_DAC960
#undef CONFIG_BLK_DEV_UMEM
#undef CONFIG_BLK_DEV_COW_COMMON
#define CONFIG_BLK_DEV_LOOP 1
#undef CONFIG_BLK_DEV_CRYPTOLOOP
#define CONFIG_BLK_DEV_NBD_MODULE 1
#undef CONFIG_BLK_DEV_SX8
#undef CONFIG_BLK_DEV_UB
#define CONFIG_BLK_DEV_RAM 1
#define CONFIG_BLK_DEV_RAM_COUNT 16
#define CONFIG_BLK_DEV_RAM_SIZE 65536
#define CONFIG_BLK_DEV_INITRD 1
#define CONFIG_INITRAMFS_SOURCE ""
#undef CONFIG_CDROM_PKTCDVD

/*
 * IO Schedulers
 */
#define CONFIG_IOSCHED_NOOP 1
#define CONFIG_IOSCHED_AS 1
#define CONFIG_IOSCHED_DEADLINE 1
#define CONFIG_IOSCHED_CFQ 1
#undef CONFIG_ATA_OVER_ETH

/*
 * ATA/ATAPI/MFM/RLL support
 */
#define CONFIG_IDE 1
#define CONFIG_BLK_DEV_IDE 1

/*
 * Please see Documentation/ide.txt for help/info on IDE drives
 */
#undef CONFIG_BLK_DEV_IDE_SATA
#define CONFIG_BLK_DEV_IDEDISK 1
#undef CONFIG_IDEDISK_MULTI_MODE
#define CONFIG_BLK_DEV_IDECD 1
#undef CONFIG_BLK_DEV_IDETAPE
#undef CONFIG_BLK_DEV_IDEFLOPPY
#undef CONFIG_BLK_DEV_IDESCSI
#undef CONFIG_IDE_TASK_IOCTL

/*
 * IDE chipset support/bugfixes
 */
#define CONFIG_IDE_GENERIC 1
#define CONFIG_BLK_DEV_IDEPCI 1
#define CONFIG_IDEPCI_SHARE_IRQ 1
#undef CONFIG_BLK_DEV_OFFBOARD
#define CONFIG_BLK_DEV_GENERIC 1
#undef CONFIG_BLK_DEV_OPTI621
#define CONFIG_BLK_DEV_SL82C105 1
#define CONFIG_BLK_DEV_IDEDMA_PCI 1
#undef CONFIG_BLK_DEV_IDEDMA_FORCED
#define CONFIG_IDEDMA_PCI_AUTO 1
#undef CONFIG_IDEDMA_ONLYDISK
#undef CONFIG_BLK_DEV_AEC62XX
#undef CONFIG_BLK_DEV_ALI15X3
#define CONFIG_BLK_DEV_AMD74XX 1
#undef CONFIG_BLK_DEV_CMD64X
#undef CONFIG_BLK_DEV_TRIFLEX
#undef CONFIG_BLK_DEV_CY82C693
#undef CONFIG_BLK_DEV_CS5520
#undef CONFIG_BLK_DEV_CS5530
#undef CONFIG_BLK_DEV_HPT34X
#undef CONFIG_BLK_DEV_HPT366
#undef CONFIG_BLK_DEV_SC1200
#undef CONFIG_BLK_DEV_PIIX
#undef CONFIG_BLK_DEV_NS87415
#undef CONFIG_BLK_DEV_PDC202XX_OLD
#undef CONFIG_BLK_DEV_PDC202XX_NEW
#undef CONFIG_BLK_DEV_SVWKS
#undef CONFIG_BLK_DEV_SIIMAGE
#undef CONFIG_BLK_DEV_SLC90E66
#undef CONFIG_BLK_DEV_TRM290
#undef CONFIG_BLK_DEV_VIA82CXXX
#define CONFIG_BLK_DEV_IDE_PMAC 1
#define CONFIG_BLK_DEV_IDE_PMAC_ATA100FIRST 1
#define CONFIG_BLK_DEV_IDEDMA_PMAC 1
#undef CONFIG_BLK_DEV_IDE_PMAC_BLINK
#undef CONFIG_IDE_ARM
#define CONFIG_BLK_DEV_IDEDMA 1
#undef CONFIG_IDEDMA_IVB
#define CONFIG_IDEDMA_AUTO 1
#undef CONFIG_BLK_DEV_HD

/*
 * SCSI device support
 */
#define CONFIG_SCSI 1
#define CONFIG_SCSI_PROC_FS 1

/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#define CONFIG_BLK_DEV_SD 1
#define CONFIG_CHR_DEV_ST 1
#undef CONFIG_CHR_DEV_OSST
#define CONFIG_BLK_DEV_SR 1
#define CONFIG_BLK_DEV_SR_VENDOR 1
#define CONFIG_CHR_DEV_SG 1

/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#define CONFIG_SCSI_MULTI_LUN 1
#define CONFIG_SCSI_CONSTANTS 1
#undef CONFIG_SCSI_LOGGING

/*
 * SCSI Transport Attributes
 */
#define CONFIG_SCSI_SPI_ATTRS 1
#define CONFIG_SCSI_FC_ATTRS 1
#define CONFIG_SCSI_ISCSI_ATTRS_MODULE 1

/*
 * SCSI low-level drivers
 */
#undef CONFIG_BLK_DEV_3W_XXXX_RAID
#undef CONFIG_SCSI_3W_9XXX
#undef CONFIG_SCSI_ACARD
#undef CONFIG_SCSI_AACRAID
#undef CONFIG_SCSI_AIC7XXX
#undef CONFIG_SCSI_AIC7XXX_OLD
#undef CONFIG_SCSI_AIC79XX
#undef CONFIG_MEGARAID_NEWGEN
#undef CONFIG_MEGARAID_LEGACY
#define CONFIG_SCSI_SATA 1
#undef CONFIG_SCSI_SATA_AHCI
#define CONFIG_SCSI_SATA_SVW 1
#undef CONFIG_SCSI_ATA_PIIX
#undef CONFIG_SCSI_SATA_NV
#undef CONFIG_SCSI_SATA_PROMISE
#undef CONFIG_SCSI_SATA_QSTOR
#undef CONFIG_SCSI_SATA_SX4
#undef CONFIG_SCSI_SATA_SIL
#undef CONFIG_SCSI_SATA_SIS
#undef CONFIG_SCSI_SATA_ULI
#undef CONFIG_SCSI_SATA_VIA
#undef CONFIG_SCSI_SATA_VITESSE
#undef CONFIG_SCSI_BUSLOGIC
#undef CONFIG_SCSI_DMX3191D
#undef CONFIG_SCSI_EATA
#undef CONFIG_SCSI_FUTURE_DOMAIN
#undef CONFIG_SCSI_GDTH
#undef CONFIG_SCSI_IPS
#define CONFIG_SCSI_IBMVSCSI 1
#undef CONFIG_SCSI_INITIO
#undef CONFIG_SCSI_INIA100
#undef CONFIG_SCSI_PPA
#undef CONFIG_SCSI_IMM
#define CONFIG_SCSI_SYM53C8XX_2 1
#define CONFIG_SCSI_SYM53C8XX_DMA_ADDRESSING_MODE 0
#define CONFIG_SCSI_SYM53C8XX_DEFAULT_TAGS 16
#define CONFIG_SCSI_SYM53C8XX_MAX_TAGS 64
#undef CONFIG_SCSI_SYM53C8XX_IOMAPPED
#define CONFIG_SCSI_IPR 1
#define CONFIG_SCSI_IPR_TRACE 1
#define CONFIG_SCSI_IPR_DUMP 1
#undef CONFIG_SCSI_QLOGIC_FC
#undef CONFIG_SCSI_QLOGIC_1280
#define CONFIG_SCSI_QLA2XXX 1
#define CONFIG_SCSI_QLA21XX_MODULE 1
#define CONFIG_SCSI_QLA22XX_MODULE 1
#define CONFIG_SCSI_QLA2300_MODULE 1
#define CONFIG_SCSI_QLA2322_MODULE 1
#define CONFIG_SCSI_QLA6312_MODULE 1
#define CONFIG_SCSI_LPFC_MODULE 1
#undef CONFIG_SCSI_DC395x
#undef CONFIG_SCSI_DC390T
#define CONFIG_SCSI_DEBUG_MODULE 1

/*
 * Multi-device support (RAID and LVM)
 */
#define CONFIG_MD 1
#define CONFIG_BLK_DEV_MD 1
#define CONFIG_MD_LINEAR 1
#define CONFIG_MD_RAID0 1
#define CONFIG_MD_RAID1 1
#define CONFIG_MD_RAID10 1
#define CONFIG_MD_RAID5 1
#define CONFIG_MD_RAID6_MODULE 1
#define CONFIG_MD_MULTIPATH_MODULE 1
#define CONFIG_MD_FAULTY_MODULE 1
#define CONFIG_BLK_DEV_DM 1
#define CONFIG_DM_CRYPT_MODULE 1
#define CONFIG_DM_SNAPSHOT_MODULE 1
#define CONFIG_DM_MIRROR_MODULE 1
#define CONFIG_DM_ZERO_MODULE 1
#define CONFIG_DM_MULTIPATH_MODULE 1
#define CONFIG_DM_MULTIPATH_EMC_MODULE 1

/*
 * Fusion MPT device support
 */
#undef CONFIG_FUSION

/*
 * IEEE 1394 (FireWire) support
 */
#define CONFIG_IEEE1394 1

/*
 * Subsystem Options
 */
#undef CONFIG_IEEE1394_VERBOSEDEBUG
#undef CONFIG_IEEE1394_OUI_DB
#define CONFIG_IEEE1394_EXTRA_CONFIG_ROMS 1
#define CONFIG_IEEE1394_CONFIG_ROM_IP1394 1

/*
 * Device Drivers
 */
#undef CONFIG_IEEE1394_PCILYNX
#define CONFIG_IEEE1394_OHCI1394 1

/*
 * Protocol Drivers
 */
#define CONFIG_IEEE1394_VIDEO1394_MODULE 1
#define CONFIG_IEEE1394_SBP2_MODULE 1
#undef CONFIG_IEEE1394_SBP2_PHYS_DMA
#define CONFIG_IEEE1394_ETH1394_MODULE 1
#define CONFIG_IEEE1394_DV1394_MODULE 1
#define CONFIG_IEEE1394_RAWIO 1
#define CONFIG_IEEE1394_CMP_MODULE 1
#define CONFIG_IEEE1394_AMDTP_MODULE 1

/*
 * I2O device support
 */
#undef CONFIG_I2O

/*
 * Macintosh device drivers
 */
#define CONFIG_ADB 1
#define CONFIG_ADB_PMU 1
#define CONFIG_PMAC_SMU 1
#undef CONFIG_PMAC_PBOOK
#undef CONFIG_PMAC_BACKLIGHT
#undef CONFIG_INPUT_ADBHID
#define CONFIG_THERM_PM72 1

/*
 * Networking support
 */
#define CONFIG_NET 1

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#undef CONFIG_PACKET_MMAP
#define CONFIG_UNIX 1
#define CONFIG_NET_KEY_MODULE 1
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#undef CONFIG_IP_ADVANCED_ROUTER
#undef CONFIG_IP_PNP
#define CONFIG_NET_IPIP 1
#undef CONFIG_NET_IPGRE
#undef CONFIG_IP_MROUTE
#undef CONFIG_ARPD
#define CONFIG_SYN_COOKIES 1
#define CONFIG_INET_AH_MODULE 1
#define CONFIG_INET_ESP_MODULE 1
#define CONFIG_INET_IPCOMP_MODULE 1
#define CONFIG_INET_TUNNEL 1
#undef CONFIG_IP_TCPDIAG
#undef CONFIG_IP_TCPDIAG_IPV6

/*
 * IP: Virtual Server Configuration
 */
#undef CONFIG_IP_VS
#undef CONFIG_IPV6
#define CONFIG_NETFILTER 1
#undef CONFIG_NETFILTER_DEBUG

/*
 * IP: Netfilter Configuration
 */
#define CONFIG_IP_NF_CONNTRACK_MODULE 1
#define CONFIG_IP_NF_CT_ACCT 1
#define CONFIG_IP_NF_CONNTRACK_MARK 1
#define CONFIG_IP_NF_CT_PROTO_SCTP_MODULE 1
#define CONFIG_IP_NF_FTP_MODULE 1
#define CONFIG_IP_NF_IRC_MODULE 1
#define CONFIG_IP_NF_TFTP_MODULE 1
#define CONFIG_IP_NF_AMANDA_MODULE 1
#define CONFIG_IP_NF_QUEUE_MODULE 1
#define CONFIG_IP_NF_IPTABLES_MODULE 1
#define CONFIG_IP_NF_MATCH_LIMIT_MODULE 1
#define CONFIG_IP_NF_MATCH_IPRANGE_MODULE 1
#define CONFIG_IP_NF_MATCH_MAC_MODULE 1
#define CONFIG_IP_NF_MATCH_PKTTYPE_MODULE 1
#define CONFIG_IP_NF_MATCH_MARK_MODULE 1
#define CONFIG_IP_NF_MATCH_MULTIPORT_MODULE 1
#define CONFIG_IP_NF_MATCH_TOS_MODULE 1
#define CONFIG_IP_NF_MATCH_RECENT_MODULE 1
#define CONFIG_IP_NF_MATCH_ECN_MODULE 1
#define CONFIG_IP_NF_MATCH_DSCP_MODULE 1
#define CONFIG_IP_NF_MATCH_AH_ESP_MODULE 1
#define CONFIG_IP_NF_MATCH_LENGTH_MODULE 1
#define CONFIG_IP_NF_MATCH_TTL_MODULE 1
#define CONFIG_IP_NF_MATCH_TCPMSS_MODULE 1
#define CONFIG_IP_NF_MATCH_HELPER_MODULE 1
#define CONFIG_IP_NF_MATCH_STATE_MODULE 1
#define CONFIG_IP_NF_MATCH_CONNTRACK_MODULE 1
#define CONFIG_IP_NF_MATCH_OWNER_MODULE 1
#define CONFIG_IP_NF_MATCH_ADDRTYPE_MODULE 1
#define CONFIG_IP_NF_MATCH_REALM_MODULE 1
#define CONFIG_IP_NF_MATCH_SCTP_MODULE 1
#define CONFIG_IP_NF_MATCH_COMMENT_MODULE 1
#define CONFIG_IP_NF_MATCH_CONNMARK_MODULE 1
#define CONFIG_IP_NF_MATCH_HASHLIMIT_MODULE 1
#define CONFIG_IP_NF_FILTER_MODULE 1
#define CONFIG_IP_NF_TARGET_REJECT_MODULE 1
#define CONFIG_IP_NF_TARGET_LOG_MODULE 1
#define CONFIG_IP_NF_TARGET_ULOG_MODULE 1
#define CONFIG_IP_NF_TARGET_TCPMSS_MODULE 1
#define CONFIG_IP_NF_NAT_MODULE 1
#define CONFIG_IP_NF_NAT_NEEDED 1
#define CONFIG_IP_NF_TARGET_MASQUERADE_MODULE 1
#define CONFIG_IP_NF_TARGET_REDIRECT_MODULE 1
#define CONFIG_IP_NF_TARGET_NETMAP_MODULE 1
#define CONFIG_IP_NF_TARGET_SAME_MODULE 1
#define CONFIG_IP_NF_NAT_SNMP_BASIC_MODULE 1
#define CONFIG_IP_NF_NAT_IRC_MODULE 1
#define CONFIG_IP_NF_NAT_FTP_MODULE 1
#define CONFIG_IP_NF_NAT_TFTP_MODULE 1
#define CONFIG_IP_NF_NAT_AMANDA_MODULE 1
#define CONFIG_IP_NF_MANGLE_MODULE 1
#define CONFIG_IP_NF_TARGET_TOS_MODULE 1
#define CONFIG_IP_NF_TARGET_ECN_MODULE 1
#define CONFIG_IP_NF_TARGET_DSCP_MODULE 1
#define CONFIG_IP_NF_TARGET_MARK_MODULE 1
#define CONFIG_IP_NF_TARGET_CLASSIFY_MODULE 1
#define CONFIG_IP_NF_TARGET_CONNMARK_MODULE 1
#define CONFIG_IP_NF_TARGET_CLUSTERIP_MODULE 1
#define CONFIG_IP_NF_RAW_MODULE 1
#define CONFIG_IP_NF_TARGET_NOTRACK_MODULE 1
#define CONFIG_IP_NF_ARPTABLES_MODULE 1
#define CONFIG_IP_NF_ARPFILTER_MODULE 1
#define CONFIG_IP_NF_ARP_MANGLE_MODULE 1
#define CONFIG_XFRM 1
#define CONFIG_XFRM_USER_MODULE 1

/*
 * SCTP Configuration (EXPERIMENTAL)
 */
#undef CONFIG_IP_SCTP
#undef CONFIG_ATM
#undef CONFIG_BRIDGE
#undef CONFIG_VLAN_8021Q
#undef CONFIG_DECNET
#define CONFIG_LLC 1
#undef CONFIG_LLC2
#undef CONFIG_IPX
#undef CONFIG_ATALK
#undef CONFIG_X25
#undef CONFIG_LAPB
#undef CONFIG_NET_DIVERT
#undef CONFIG_ECONET
#undef CONFIG_WAN_ROUTER

/*
 * QoS and/or fair queueing
 */
#undef CONFIG_NET_SCHED
#define CONFIG_NET_CLS_ROUTE 1

/*
 * Network testing
 */
#undef CONFIG_NET_PKTGEN
#define CONFIG_NETPOLL 1
#define CONFIG_NETPOLL_RX 1
#define CONFIG_NETPOLL_TRAP 1
#define CONFIG_NET_POLL_CONTROLLER 1
#undef CONFIG_HAMRADIO
#undef CONFIG_IRDA
#undef CONFIG_BT
#define CONFIG_NETDEVICES 1
#define CONFIG_DUMMY_MODULE 1
#define CONFIG_BONDING_MODULE 1
#undef CONFIG_EQUALIZER
#define CONFIG_TUN_MODULE 1

/*
 * ARCnet devices
 */
#undef CONFIG_ARCNET

/*
 * Ethernet (10 or 100Mbit)
 */
#define CONFIG_NET_ETHERNET 1
#define CONFIG_MII 1
#undef CONFIG_HAPPYMEAL
#define CONFIG_SUNGEM 1
#define CONFIG_NET_VENDOR_3COM 1
#define CONFIG_VORTEX 1
#undef CONFIG_TYPHOON

/*
 * Tulip family network device support
 */
#undef CONFIG_NET_TULIP
#undef CONFIG_HP100
#define CONFIG_IBMVETH_MODULE 1
#define CONFIG_NET_PCI 1
#define CONFIG_PCNET32 1
#undef CONFIG_AMD8111_ETH
#undef CONFIG_ADAPTEC_STARFIRE
#undef CONFIG_B44
#undef CONFIG_FORCEDETH
#undef CONFIG_DGRS
#undef CONFIG_EEPRO100
#define CONFIG_E100 1
#undef CONFIG_FEALNX
#undef CONFIG_NATSEMI
#undef CONFIG_NE2K_PCI
#undef CONFIG_8139CP
#undef CONFIG_8139TOO
#undef CONFIG_SIS900
#undef CONFIG_EPIC100
#undef CONFIG_SUNDANCE
#undef CONFIG_VIA_RHINE

/*
 * Ethernet (1000 Mbit)
 */
#define CONFIG_ACENIC 1
#define CONFIG_ACENIC_OMIT_TIGON_I 1
#undef CONFIG_DL2K
#define CONFIG_E1000 1
#undef CONFIG_E1000_NAPI
#undef CONFIG_NS83820
#undef CONFIG_HAMACHI
#undef CONFIG_YELLOWFIN
#undef CONFIG_R8169
#undef CONFIG_SK98LIN
#undef CONFIG_VIA_VELOCITY
#define CONFIG_TIGON3 1
#undef CONFIG_BNX2
#undef CONFIG_MV643XX_ETH

/*
 * Ethernet (10000 Mbit)
 */
#define CONFIG_IXGB_MODULE 1
#undef CONFIG_IXGB_NAPI
#undef CONFIG_S2IO

/*
 * Token Ring devices
 */
#define CONFIG_TR 1
#define CONFIG_IBMOL 1
#undef CONFIG_3C359
#undef CONFIG_TMS380TR

/*
 * Wireless LAN (non-hamradio)
 */
#undef CONFIG_NET_RADIO

/*
 * Wan interfaces
 */
#undef CONFIG_WAN
#undef CONFIG_FDDI
#undef CONFIG_HIPPI
#undef CONFIG_PLIP
#define CONFIG_PPP_MODULE 1
#undef CONFIG_PPP_MULTILINK
#undef CONFIG_PPP_FILTER
#define CONFIG_PPP_ASYNC_MODULE 1
#define CONFIG_PPP_SYNC_TTY_MODULE 1
#define CONFIG_PPP_DEFLATE_MODULE 1
#define CONFIG_PPP_BSDCOMP_MODULE 1
#define CONFIG_PPPOE_MODULE 1
#undef CONFIG_SLIP
#undef CONFIG_NET_FC
#undef CONFIG_SHAPER
#define CONFIG_NETCONSOLE 1

/*
 * ISDN subsystem
 */
#undef CONFIG_ISDN

/*
 * Telephony Support
 */
#undef CONFIG_PHONE

/*
 * Input device support
 */
#define CONFIG_INPUT 1

/*
 * Userland interfaces
 */
#define CONFIG_INPUT_MOUSEDEV 1
#undef CONFIG_INPUT_MOUSEDEV_PSAUX
#define CONFIG_INPUT_MOUSEDEV_SCREEN_X 1024
#define CONFIG_INPUT_MOUSEDEV_SCREEN_Y 768
#undef CONFIG_INPUT_JOYDEV
#undef CONFIG_INPUT_TSDEV
#define CONFIG_INPUT_EVDEV_MODULE 1
#undef CONFIG_INPUT_EVBUG

/*
 * Input Device Drivers
 */
#define CONFIG_INPUT_KEYBOARD 1
#define CONFIG_KEYBOARD_ATKBD 1
#undef CONFIG_KEYBOARD_SUNKBD
#undef CONFIG_KEYBOARD_LKKBD
#undef CONFIG_KEYBOARD_XTKBD
#undef CONFIG_KEYBOARD_NEWTON
#define CONFIG_INPUT_MOUSE 1
#define CONFIG_MOUSE_PS2 1
#undef CONFIG_MOUSE_SERIAL
#undef CONFIG_MOUSE_VSXXXAA
#undef CONFIG_INPUT_JOYSTICK
#undef CONFIG_INPUT_TOUCHSCREEN
#define CONFIG_INPUT_MISC 1
#define CONFIG_INPUT_PCSPKR_MODULE 1
#undef CONFIG_INPUT_UINPUT

/*
 * Hardware I/O ports
 */
#define CONFIG_SERIO 1
#define CONFIG_SERIO_I8042 1
#undef CONFIG_SERIO_SERPORT
#undef CONFIG_SERIO_PARKBD
#undef CONFIG_SERIO_PCIPS2
#define CONFIG_SERIO_LIBPS2 1
#undef CONFIG_SERIO_RAW
#undef CONFIG_GAMEPORT

/*
 * Character devices
 */
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#define CONFIG_HW_CONSOLE 1
#undef CONFIG_SERIAL_NONSTANDARD

/*
 * Serial drivers
 */
#define CONFIG_SERIAL_8250 1
#define CONFIG_SERIAL_8250_CONSOLE 1
#define CONFIG_SERIAL_8250_NR_UARTS 4
#undef CONFIG_SERIAL_8250_EXTENDED

/*
 * Non-8250 serial port support
 */
#define CONFIG_SERIAL_CORE 1
#define CONFIG_SERIAL_CORE_CONSOLE 1
#undef CONFIG_SERIAL_PMACZILOG
#define CONFIG_SERIAL_ICOM_MODULE 1
#define CONFIG_SERIAL_JSM_MODULE 1
#define CONFIG_UNIX98_PTYS 1
#define CONFIG_LEGACY_PTYS 1
#define CONFIG_LEGACY_PTY_COUNT 256
#define CONFIG_PRINTER_MODULE 1
#undef CONFIG_LP_CONSOLE
#undef CONFIG_PPDEV
#undef CONFIG_TIPAR
#define CONFIG_HVC_CONSOLE 1
#define CONFIG_HVCS_MODULE 1

/*
 * IPMI
 */
#undef CONFIG_IPMI_HANDLER

/*
 * Watchdog Cards
 */
#undef CONFIG_WATCHDOG
#undef CONFIG_RTC
#undef CONFIG_GEN_RTC
#undef CONFIG_DTLK
#undef CONFIG_R3964
#undef CONFIG_APPLICOM

/*
 * Ftape, the floppy tape device driver
 */
#undef CONFIG_AGP
#undef CONFIG_DRM
#define CONFIG_RAW_DRIVER 1
#define CONFIG_MAX_RAW_DEVS 256
#undef CONFIG_HANGCHECK_TIMER

/*
 * TPM devices
 */
#undef CONFIG_TCG_TPM

/*
 * I2C support
 */
#define CONFIG_I2C 1
#define CONFIG_I2C_CHARDEV 1

/*
 * I2C Algorithms
 */
#define CONFIG_I2C_ALGOBIT 1
#undef CONFIG_I2C_ALGOPCF
#undef CONFIG_I2C_ALGOPCA

/*
 * I2C Hardware Bus support
 */
#undef CONFIG_I2C_ALI1535
#undef CONFIG_I2C_ALI1563
#undef CONFIG_I2C_ALI15X3
#undef CONFIG_I2C_AMD756
#define CONFIG_I2C_AMD8111 1
#undef CONFIG_I2C_I801
#undef CONFIG_I2C_I810
#undef CONFIG_I2C_PIIX4
#undef CONFIG_I2C_ISA
#define CONFIG_I2C_KEYWEST 1
#undef CONFIG_I2C_NFORCE2
#undef CONFIG_I2C_PARPORT
#undef CONFIG_I2C_PARPORT_LIGHT
#undef CONFIG_I2C_PROSAVAGE
#undef CONFIG_I2C_SAVAGE4
#undef CONFIG_SCx200_ACB
#undef CONFIG_I2C_SIS5595
#undef CONFIG_I2C_SIS630
#undef CONFIG_I2C_SIS96X
#undef CONFIG_I2C_STUB
#undef CONFIG_I2C_VIA
#undef CONFIG_I2C_VIAPRO
#undef CONFIG_I2C_VOODOO3
#undef CONFIG_I2C_PCA_ISA

/*
 * Hardware Sensors Chip support
 */
#undef CONFIG_I2C_SENSOR
#undef CONFIG_SENSORS_ADM1021
#undef CONFIG_SENSORS_ADM1025
#undef CONFIG_SENSORS_ADM1026
#undef CONFIG_SENSORS_ADM1031
#undef CONFIG_SENSORS_ASB100
#undef CONFIG_SENSORS_DS1621
#undef CONFIG_SENSORS_FSCHER
#undef CONFIG_SENSORS_FSCPOS
#undef CONFIG_SENSORS_GL518SM
#undef CONFIG_SENSORS_GL520SM
#undef CONFIG_SENSORS_IT87
#undef CONFIG_SENSORS_LM63
#undef CONFIG_SENSORS_LM75
#undef CONFIG_SENSORS_LM77
#undef CONFIG_SENSORS_LM78
#undef CONFIG_SENSORS_LM80
#undef CONFIG_SENSORS_LM83
#undef CONFIG_SENSORS_LM85
#undef CONFIG_SENSORS_LM87
#undef CONFIG_SENSORS_LM90
#undef CONFIG_SENSORS_LM92
#undef CONFIG_SENSORS_MAX1619
#undef CONFIG_SENSORS_PC87360
#undef CONFIG_SENSORS_SMSC47B397
#undef CONFIG_SENSORS_SIS5595
#undef CONFIG_SENSORS_SMSC47M1
#undef CONFIG_SENSORS_VIA686A
#undef CONFIG_SENSORS_W83781D
#undef CONFIG_SENSORS_W83L785TS
#undef CONFIG_SENSORS_W83627HF

/*
 * Other I2C Chip support
 */
#undef CONFIG_SENSORS_DS1337
#undef CONFIG_SENSORS_EEPROM
#undef CONFIG_SENSORS_PCF8574
#undef CONFIG_SENSORS_PCF8591
#undef CONFIG_SENSORS_RTC8564
#undef CONFIG_I2C_DEBUG_CORE
#undef CONFIG_I2C_DEBUG_ALGO
#undef CONFIG_I2C_DEBUG_BUS
#undef CONFIG_I2C_DEBUG_CHIP

/*
 * Dallas's 1-wire bus
 */
#undef CONFIG_W1

/*
 * Misc devices
 */

/*
 * Multimedia devices
 */
#undef CONFIG_VIDEO_DEV

/*
 * Digital Video Broadcasting Devices
 */
#undef CONFIG_DVB

/*
 * Graphics support
 */
#define CONFIG_FB 1
#define CONFIG_FB_CFB_FILLRECT 1
#define CONFIG_FB_CFB_COPYAREA 1
#define CONFIG_FB_CFB_IMAGEBLIT 1
#define CONFIG_FB_SOFT_CURSOR 1
#define CONFIG_FB_MACMODES 1
#define CONFIG_FB_MODE_HELPERS 1
#define CONFIG_FB_TILEBLITTING 1
#undef CONFIG_FB_CIRRUS
#undef CONFIG_FB_PM2
#undef CONFIG_FB_CYBER2000
#define CONFIG_FB_OF 1
#undef CONFIG_FB_CONTROL
#undef CONFIG_FB_PLATINUM
#undef CONFIG_FB_VALKYRIE
#undef CONFIG_FB_CT65550
#undef CONFIG_FB_ASILIANT
#undef CONFIG_FB_IMSTT
#undef CONFIG_FB_VGA16
#undef CONFIG_FB_NVIDIA
#undef CONFIG_FB_RIVA
#define CONFIG_FB_MATROX 1
#define CONFIG_FB_MATROX_MILLENIUM 1
#define CONFIG_FB_MATROX_MYSTIQUE 1
#define CONFIG_FB_MATROX_G 1
#define CONFIG_FB_MATROX_I2C_MODULE 1
#define CONFIG_FB_MATROX_MAVEN_MODULE 1
#define CONFIG_FB_MATROX_MULTIHEAD 1
#undef CONFIG_FB_RADEON_OLD
#define CONFIG_FB_RADEON 1
#define CONFIG_FB_RADEON_I2C 1
#undef CONFIG_FB_RADEON_DEBUG
#undef CONFIG_FB_ATY128
#undef CONFIG_FB_ATY
#undef CONFIG_FB_SAVAGE
#undef CONFIG_FB_SIS
#undef CONFIG_FB_NEOMAGIC
#undef CONFIG_FB_KYRO
#undef CONFIG_FB_3DFX
#undef CONFIG_FB_VOODOO1
#undef CONFIG_FB_TRIDENT
#undef CONFIG_FB_S1D13XXX
#undef CONFIG_FB_VIRTUAL

/*
 * Console display driver support
 */
#undef CONFIG_VGA_CONSOLE
#define CONFIG_DUMMY_CONSOLE 1
#define CONFIG_FRAMEBUFFER_CONSOLE 1
#undef CONFIG_FONTS
#define CONFIG_FONT_8x8 1
#define CONFIG_FONT_8x16 1

/*
 * Logo configuration
 */
#define CONFIG_LOGO 1
#define CONFIG_LOGO_LINUX_MONO 1
#define CONFIG_LOGO_LINUX_VGA16 1
#define CONFIG_LOGO_LINUX_CLUT224 1
#define CONFIG_BACKLIGHT_LCD_SUPPORT 1
#define CONFIG_BACKLIGHT_CLASS_DEVICE 1
#define CONFIG_BACKLIGHT_DEVICE 1
#define CONFIG_LCD_CLASS_DEVICE 1
#define CONFIG_LCD_DEVICE 1

/*
 * Sound
 */
#undef CONFIG_SOUND

/*
 * USB support
 */
#define CONFIG_USB_ARCH_HAS_HCD 1
#define CONFIG_USB_ARCH_HAS_OHCI 1
#define CONFIG_USB 1
#undef CONFIG_USB_DEBUG

/*
 * Miscellaneous USB options
 */
#define CONFIG_USB_DEVICEFS 1
#undef CONFIG_USB_BANDWIDTH
#undef CONFIG_USB_DYNAMIC_MINORS
#undef CONFIG_USB_OTG

/*
 * USB Host Controller Drivers
 */
#define CONFIG_USB_EHCI_HCD 1
#undef CONFIG_USB_EHCI_SPLIT_ISO
#undef CONFIG_USB_EHCI_ROOT_HUB_TT
#define CONFIG_USB_OHCI_HCD 1
#undef CONFIG_USB_OHCI_BIG_ENDIAN
#define CONFIG_USB_OHCI_LITTLE_ENDIAN 1
#undef CONFIG_USB_UHCI_HCD
#undef CONFIG_USB_SL811_HCD

/*
 * USB Device Class drivers
 */
#undef CONFIG_USB_BLUETOOTH_TTY
#undef CONFIG_USB_ACM
#undef CONFIG_USB_PRINTER

/*
 * NOTE: USB_STORAGE enables SCSI, and 'SCSI disk support' may also be needed; see USB_STORAGE Help for more information
 */
#define CONFIG_USB_STORAGE_MODULE 1
#undef CONFIG_USB_STORAGE_DEBUG
#undef CONFIG_USB_STORAGE_DATAFAB
#undef CONFIG_USB_STORAGE_FREECOM
#undef CONFIG_USB_STORAGE_ISD200
#undef CONFIG_USB_STORAGE_DPCM
#undef CONFIG_USB_STORAGE_USBAT
#undef CONFIG_USB_STORAGE_SDDR09
#undef CONFIG_USB_STORAGE_SDDR55
#undef CONFIG_USB_STORAGE_JUMPSHOT

/*
 * USB Input Devices
 */
#define CONFIG_USB_HID 1
#define CONFIG_USB_HIDINPUT 1
#undef CONFIG_HID_FF
#define CONFIG_USB_HIDDEV 1
#undef CONFIG_USB_AIPTEK
#undef CONFIG_USB_WACOM
#undef CONFIG_USB_KBTAB
#undef CONFIG_USB_POWERMATE
#undef CONFIG_USB_MTOUCH
#undef CONFIG_USB_EGALAX
#undef CONFIG_USB_XPAD
#undef CONFIG_USB_ATI_REMOTE

/*
 * USB Imaging devices
 */
#undef CONFIG_USB_MDC800
#undef CONFIG_USB_MICROTEK

/*
 * USB Multimedia devices
 */
#undef CONFIG_USB_DABUSB

/*
 * Video4Linux support is needed for USB Multimedia device support
 */

/*
 * USB Network Adapters
 */
#undef CONFIG_USB_CATC
#undef CONFIG_USB_KAWETH
#define CONFIG_USB_PEGASUS 1
#undef CONFIG_USB_RTL8150
#undef CONFIG_USB_USBNET
#undef CONFIG_USB_MON

/*
 * USB port drivers
 */
#undef CONFIG_USB_USS720

/*
 * USB Serial Converter support
 */
#undef CONFIG_USB_SERIAL

/*
 * USB Miscellaneous drivers
 */
#undef CONFIG_USB_EMI62
#undef CONFIG_USB_EMI26
#undef CONFIG_USB_AUERSWALD
#undef CONFIG_USB_RIO500
#undef CONFIG_USB_LEGOTOWER
#undef CONFIG_USB_LCD
#undef CONFIG_USB_LED
#undef CONFIG_USB_CYTHERM
#undef CONFIG_USB_PHIDGETKIT
#undef CONFIG_USB_PHIDGETSERVO
#undef CONFIG_USB_IDMOUSE
#undef CONFIG_USB_SISUSBVGA
#undef CONFIG_USB_TEST

/*
 * USB ATM/DSL drivers
 */

/*
 * USB Gadget Support
 */
#undef CONFIG_USB_GADGET

/*
 * MMC/SD Card support
 */
#undef CONFIG_MMC

/*
 * InfiniBand support
 */
#define CONFIG_INFINIBAND_MODULE 1
#define CONFIG_INFINIBAND_MTHCA_MODULE 1
#undef CONFIG_INFINIBAND_MTHCA_DEBUG
#define CONFIG_INFINIBAND_IPOIB_MODULE 1
#undef CONFIG_INFINIBAND_IPOIB_DEBUG

/*
 * File systems
 */
#define CONFIG_EXT2_FS 1
#define CONFIG_EXT2_FS_XATTR 1
#define CONFIG_EXT2_FS_POSIX_ACL 1
#define CONFIG_EXT2_FS_SECURITY 1
#define CONFIG_EXT3_FS 1
#define CONFIG_EXT3_FS_XATTR 1
#define CONFIG_EXT3_FS_POSIX_ACL 1
#define CONFIG_EXT3_FS_SECURITY 1
#define CONFIG_JBD 1
#undef CONFIG_JBD_DEBUG
#define CONFIG_FS_MBCACHE 1
#define CONFIG_REISERFS_FS 1
#undef CONFIG_REISERFS_CHECK
#undef CONFIG_REISERFS_PROC_INFO
#define CONFIG_REISERFS_FS_XATTR 1
#define CONFIG_REISERFS_FS_POSIX_ACL 1
#define CONFIG_REISERFS_FS_SECURITY 1
#define CONFIG_JFS_FS 1
#define CONFIG_JFS_POSIX_ACL 1
#define CONFIG_JFS_SECURITY 1
#undef CONFIG_JFS_DEBUG
#undef CONFIG_JFS_STATISTICS
#define CONFIG_FS_POSIX_ACL 1

/*
 * XFS support
 */
#define CONFIG_XFS_FS_MODULE 1
#define CONFIG_XFS_EXPORT 1
#undef CONFIG_XFS_RT
#undef CONFIG_XFS_QUOTA
#define CONFIG_XFS_SECURITY 1
#define CONFIG_XFS_POSIX_ACL 1
#undef CONFIG_MINIX_FS
#undef CONFIG_ROMFS_FS
#undef CONFIG_QUOTA
#define CONFIG_DNOTIFY 1
#define CONFIG_AUTOFS_FS 1
#undef CONFIG_AUTOFS4_FS

/*
 * CD-ROM/DVD Filesystems
 */
#define CONFIG_ISO9660_FS 1
#undef CONFIG_JOLIET
#undef CONFIG_ZISOFS
#define CONFIG_UDF_FS_MODULE 1
#define CONFIG_UDF_NLS 1

/*
 * DOS/FAT/NT Filesystems
 */
#define CONFIG_FAT_FS 1
#define CONFIG_MSDOS_FS 1
#define CONFIG_VFAT_FS 1
#define CONFIG_FAT_DEFAULT_CODEPAGE 437
#define CONFIG_FAT_DEFAULT_IOCHARSET "iso8859-1"
#undef CONFIG_NTFS_FS

/*
 * Pseudo filesystems
 */
#define CONFIG_PROC_FS 1
#define CONFIG_PROC_KCORE 1
#define CONFIG_SYSFS 1
#undef CONFIG_DEVFS_FS
#define CONFIG_DEVPTS_FS_XATTR 1
#define CONFIG_DEVPTS_FS_SECURITY 1
#define CONFIG_TMPFS 1
#define CONFIG_TMPFS_XATTR 1
#define CONFIG_TMPFS_SECURITY 1
#define CONFIG_HUGETLBFS 1
#define CONFIG_HUGETLB_PAGE 1
#define CONFIG_RAMFS 1

/*
 * Miscellaneous filesystems
 */
#undef CONFIG_ADFS_FS
#undef CONFIG_AFFS_FS
#define CONFIG_HFS_FS_MODULE 1
#define CONFIG_HFSPLUS_FS_MODULE 1
#undef CONFIG_BEFS_FS
#undef CONFIG_BFS_FS
#undef CONFIG_EFS_FS
#define CONFIG_CRAMFS 1
#undef CONFIG_VXFS_FS
#undef CONFIG_HPFS_FS
#undef CONFIG_QNX4FS_FS
#undef CONFIG_SYSV_FS
#undef CONFIG_UFS_FS

/*
 * Network File Systems
 */
#define CONFIG_NFS_FS 1
#define CONFIG_NFS_V3 1
#define CONFIG_NFS_V4 1
#undef CONFIG_NFS_DIRECTIO
#define CONFIG_NFSD_MODULE 1
#define CONFIG_NFSD_V3 1
#define CONFIG_NFSD_V4 1
#define CONFIG_NFSD_TCP 1
#define CONFIG_LOCKD 1
#define CONFIG_LOCKD_V4 1
#define CONFIG_EXPORTFS_MODULE 1
#define CONFIG_SUNRPC 1
#define CONFIG_SUNRPC_GSS 1
#define CONFIG_RPCSEC_GSS_KRB5 1
#define CONFIG_RPCSEC_GSS_SPKM3_MODULE 1
#undef CONFIG_SMB_FS
#define CONFIG_CIFS_MODULE 1
#undef CONFIG_CIFS_STATS
#define CONFIG_CIFS_XATTR 1
#define CONFIG_CIFS_POSIX 1
#undef CONFIG_CIFS_EXPERIMENTAL
#undef CONFIG_NCP_FS
#undef CONFIG_CODA_FS
#undef CONFIG_AFS_FS

/*
 * Partition Types
 */
#define CONFIG_PARTITION_ADVANCED 1
#undef CONFIG_ACORN_PARTITION
#undef CONFIG_OSF_PARTITION
#undef CONFIG_AMIGA_PARTITION
#undef CONFIG_ATARI_PARTITION
#define CONFIG_MAC_PARTITION 1
#define CONFIG_MSDOS_PARTITION 1
#undef CONFIG_BSD_DISKLABEL
#undef CONFIG_MINIX_SUBPARTITION
#undef CONFIG_SOLARIS_X86_PARTITION
#undef CONFIG_UNIXWARE_DISKLABEL
#undef CONFIG_LDM_PARTITION
#undef CONFIG_SGI_PARTITION
#undef CONFIG_ULTRIX_PARTITION
#undef CONFIG_SUN_PARTITION
#undef CONFIG_EFI_PARTITION

/*
 * Native Language Support
 */
#define CONFIG_NLS 1
#define CONFIG_NLS_DEFAULT "iso8859-1"
#define CONFIG_NLS_CODEPAGE_437_MODULE 1
#define CONFIG_NLS_CODEPAGE_737_MODULE 1
#define CONFIG_NLS_CODEPAGE_775_MODULE 1
#define CONFIG_NLS_CODEPAGE_850_MODULE 1
#define CONFIG_NLS_CODEPAGE_852_MODULE 1
#define CONFIG_NLS_CODEPAGE_855_MODULE 1
#define CONFIG_NLS_CODEPAGE_857_MODULE 1
#define CONFIG_NLS_CODEPAGE_860_MODULE 1
#define CONFIG_NLS_CODEPAGE_861_MODULE 1
#define CONFIG_NLS_CODEPAGE_862_MODULE 1
#define CONFIG_NLS_CODEPAGE_863_MODULE 1
#define CONFIG_NLS_CODEPAGE_864_MODULE 1
#define CONFIG_NLS_CODEPAGE_865_MODULE 1
#define CONFIG_NLS_CODEPAGE_866_MODULE 1
#define CONFIG_NLS_CODEPAGE_869_MODULE 1
#define CONFIG_NLS_CODEPAGE_936_MODULE 1
#define CONFIG_NLS_CODEPAGE_950_MODULE 1
#define CONFIG_NLS_CODEPAGE_932_MODULE 1
#define CONFIG_NLS_CODEPAGE_949_MODULE 1
#define CONFIG_NLS_CODEPAGE_874_MODULE 1
#define CONFIG_NLS_ISO8859_8_MODULE 1
#define CONFIG_NLS_CODEPAGE_1250_MODULE 1
#define CONFIG_NLS_CODEPAGE_1251_MODULE 1
#define CONFIG_NLS_ASCII_MODULE 1
#define CONFIG_NLS_ISO8859_1_MODULE 1
#define CONFIG_NLS_ISO8859_2_MODULE 1
#define CONFIG_NLS_ISO8859_3_MODULE 1
#define CONFIG_NLS_ISO8859_4_MODULE 1
#define CONFIG_NLS_ISO8859_5_MODULE 1
#define CONFIG_NLS_ISO8859_6_MODULE 1
#define CONFIG_NLS_ISO8859_7_MODULE 1
#define CONFIG_NLS_ISO8859_9_MODULE 1
#define CONFIG_NLS_ISO8859_13_MODULE 1
#define CONFIG_NLS_ISO8859_14_MODULE 1
#define CONFIG_NLS_ISO8859_15_MODULE 1
#define CONFIG_NLS_KOI8_R_MODULE 1
#define CONFIG_NLS_KOI8_U_MODULE 1
#define CONFIG_NLS_UTF8_MODULE 1

/*
 * Profiling support
 */
#define CONFIG_PROFILING 1
#define CONFIG_OPROFILE 1

/*
 * Kernel hacking
 */
#undef CONFIG_PRINTK_TIME
#define CONFIG_DEBUG_KERNEL 1
#define CONFIG_MAGIC_SYSRQ 1
#define CONFIG_LOG_BUF_SHIFT 17
#undef CONFIG_SCHEDSTATS
#undef CONFIG_DEBUG_SLAB
#undef CONFIG_DEBUG_SPINLOCK
#undef CONFIG_DEBUG_SPINLOCK_SLEEP
#undef CONFIG_DEBUG_KOBJECT
#undef CONFIG_DEBUG_INFO
#define CONFIG_DEBUG_FS 1
#define CONFIG_DEBUG_STACKOVERFLOW 1
#undef CONFIG_KPROBES
#define CONFIG_DEBUG_STACK_USAGE 1
#define CONFIG_DEBUGGER 1
#define CONFIG_XMON 1
#undef CONFIG_XMON_DEFAULT
#undef CONFIG_PPCDBG
#define CONFIG_IRQSTACKS 1

/*
 * Security options
 */
#undef CONFIG_KEYS
#undef CONFIG_SECURITY

/*
 * Cryptographic options
 */
#define CONFIG_CRYPTO 1
#define CONFIG_CRYPTO_HMAC 1
#define CONFIG_CRYPTO_NULL_MODULE 1
#define CONFIG_CRYPTO_MD4_MODULE 1
#define CONFIG_CRYPTO_MD5 1
#define CONFIG_CRYPTO_SHA1_MODULE 1
#define CONFIG_CRYPTO_SHA256_MODULE 1
#define CONFIG_CRYPTO_SHA512_MODULE 1
#define CONFIG_CRYPTO_WP512_MODULE 1
#define CONFIG_CRYPTO_TGR192_MODULE 1
#define CONFIG_CRYPTO_DES 1
#define CONFIG_CRYPTO_BLOWFISH_MODULE 1
#define CONFIG_CRYPTO_TWOFISH_MODULE 1
#define CONFIG_CRYPTO_SERPENT_MODULE 1
#define CONFIG_CRYPTO_AES_MODULE 1
#define CONFIG_CRYPTO_CAST5_MODULE 1
#define CONFIG_CRYPTO_CAST6_MODULE 1
#define CONFIG_CRYPTO_TEA_MODULE 1
#define CONFIG_CRYPTO_ARC4_MODULE 1
#define CONFIG_CRYPTO_KHAZAD_MODULE 1
#define CONFIG_CRYPTO_ANUBIS_MODULE 1
#define CONFIG_CRYPTO_DEFLATE_MODULE 1
#define CONFIG_CRYPTO_MICHAEL_MIC_MODULE 1
#define CONFIG_CRYPTO_CRC32C_MODULE 1
#define CONFIG_CRYPTO_TEST_MODULE 1

/*
 * Hardware crypto devices
 */

/*
 * Library routines
 */
#define CONFIG_CRC_CCITT_MODULE 1
#define CONFIG_CRC32 1
#define CONFIG_LIBCRC32C_MODULE 1
#define CONFIG_ZLIB_INFLATE 1
#define CONFIG_ZLIB_DEFLATE_MODULE 1
