/*
 * Automatically generated C config: don't edit
 * Linux kernel version: 2.6.12
 * Sat Jun 18 16:12:21 2005
 */
#define AUTOCONF_INCLUDED
#define CONFIG_MMU 1
#define CONFIG_GENERIC_HARDIRQS 1
#define CONFIG_RWSEM_XCHGADD_ALGORITHM 1
#define CONFIG_GENERIC_CALIBRATE_DELAY 1
#define CONFIG_HAVE_DEC_LOCK 1
#define CONFIG_PPC 1
#define CONFIG_PPC32 1
#define CONFIG_GENERIC_NVRAM 1
#define CONFIG_SCHED_NO_NO_OMIT_FRAME_POINTER 1

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1
#define CONFIG_CLEAN_COMPILE 1
#define CONFIG_BROKEN_ON_SMP 1
#define CONFIG_INIT_ENV_ARG_LIMIT 32

/*
 * General setup
 */
#define CONFIG_LOCALVERSION ""
#define CONFIG_SWAP 1
#define CONFIG_SYSVIPC 1
#define CONFIG_POSIX_MQUEUE 1
#undef CONFIG_BSD_PROCESS_ACCT
#define CONFIG_SYSCTL 1
#undef CONFIG_AUDIT
#define CONFIG_HOTPLUG 1
#define CONFIG_KOBJECT_UEVENT 1
#define CONFIG_IKCONFIG 1
#define CONFIG_IKCONFIG_PROC 1
#undef CONFIG_EMBEDDED
#define CONFIG_KALLSYMS 1
#undef CONFIG_KALLSYMS_EXTRA_PASS
#define CONFIG_PRINTK 1
#define CONFIG_BUG 1
#define CONFIG_BASE_FULL 1
#define CONFIG_FUTEX 1
#define CONFIG_EPOLL 1
#define CONFIG_SHMEM 1
#define CONFIG_CC_ALIGN_FUNCTIONS 0
#define CONFIG_CC_ALIGN_LABELS 0
#define CONFIG_CC_ALIGN_LOOPS 0
#define CONFIG_CC_ALIGN_JUMPS 0
#undef CONFIG_TINY_SHMEM
#define CONFIG_BASE_SMALL 0

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#define CONFIG_MODULE_UNLOAD 1
#define CONFIG_MODULE_FORCE_UNLOAD 1
#define CONFIG_OBSOLETE_MODPARM 1
#define CONFIG_MODVERSIONS 1
#undef CONFIG_MODULE_SRCVERSION_ALL
#define CONFIG_KMOD 1

/*
 * Processor
 */
#define CONFIG_6xx 1
#undef CONFIG_40x
#undef CONFIG_44x
#undef CONFIG_POWER3
#undef CONFIG_POWER4
#undef CONFIG_8xx
#undef CONFIG_E500
#define CONFIG_PPC_FPU 1
#define CONFIG_ALTIVEC 1
#define CONFIG_TAU 1
#undef CONFIG_TAU_INT
#undef CONFIG_TAU_AVERAGE
#define CONFIG_CPU_FREQ 1
#define CONFIG_CPU_FREQ_TABLE 1
#undef CONFIG_CPU_FREQ_DEBUG
#define CONFIG_CPU_FREQ_STAT 1
#undef CONFIG_CPU_FREQ_STAT_DETAILS
#define CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE 1
#undef CONFIG_CPU_FREQ_DEFAULT_GOV_USERSPACE
#define CONFIG_CPU_FREQ_GOV_PERFORMANCE 1
#undef CONFIG_CPU_FREQ_GOV_POWERSAVE
#undef CONFIG_CPU_FREQ_GOV_USERSPACE
#undef CONFIG_CPU_FREQ_GOV_ONDEMAND
#undef CONFIG_CPU_FREQ_GOV_CONSERVATIVE
#define CONFIG_CPU_FREQ_PMAC 1
#define CONFIG_PPC601_SYNC_FIX 1
#define CONFIG_PM 1
#define CONFIG_PPC_STD_MMU 1

/*
 * Platform options
 */
#define CONFIG_PPC_MULTIPLATFORM 1
#undef CONFIG_APUS
#undef CONFIG_KATANA
#undef CONFIG_WILLOW
#undef CONFIG_CPCI690
#undef CONFIG_PCORE
#undef CONFIG_POWERPMC250
#undef CONFIG_CHESTNUT
#undef CONFIG_SPRUCE
#undef CONFIG_HDPU
#undef CONFIG_EV64260
#undef CONFIG_LOPEC
#undef CONFIG_MCPN765
#undef CONFIG_MVME5100
#undef CONFIG_PPLUS
#undef CONFIG_PRPMC750
#undef CONFIG_PRPMC800
#undef CONFIG_SANDPOINT
#undef CONFIG_RADSTONE_PPC7D
#undef CONFIG_ADIR
#undef CONFIG_K2
#undef CONFIG_PAL4
#undef CONFIG_GEMINI
#undef CONFIG_EST8260
#undef CONFIG_SBC82xx
#undef CONFIG_SBS8260
#undef CONFIG_RPX8260
#undef CONFIG_TQM8260
#undef CONFIG_ADS8272
#undef CONFIG_PQ2FADS
#undef CONFIG_LITE5200
#undef CONFIG_MPC834x_SYS
#define CONFIG_PPC_CHRP 1
#define CONFIG_PPC_PMAC 1
#define CONFIG_PPC_PREP 1
#define CONFIG_PPC_OF 1
#define CONFIG_PPCBUG_NVRAM 1
#undef CONFIG_SMP
#undef CONFIG_PREEMPT
#undef CONFIG_HIGHMEM
#define CONFIG_BINFMT_ELF 1
#define CONFIG_BINFMT_MISC_MODULE 1
#define CONFIG_PROC_DEVICETREE 1
#define CONFIG_PREP_RESIDUAL 1
#define CONFIG_PROC_PREPRESIDUAL 1
#define CONFIG_CMDLINE_BOOL 1
#define CONFIG_CMDLINE "console=ttyS0,9600 console=tty0 root=/dev/sda2"
#undef CONFIG_PM_DEBUG
#undef CONFIG_SOFTWARE_SUSPEND
#define CONFIG_ISA_DMA_API 1

/*
 * Bus options
 */
#define CONFIG_ISA 1
#define CONFIG_GENERIC_ISA_DMA 1
#define CONFIG_PCI 1
#define CONFIG_PCI_DOMAINS 1
#define CONFIG_PCI_LEGACY_PROC 1
#define CONFIG_PCI_NAMES 1

/*
 * PCCARD (PCMCIA/CardBus) support
 */
#undef CONFIG_PCCARD

/*
 * Advanced setup
 */
#undef CONFIG_ADVANCED_OPTIONS

/*
 * Default settings for advanced configuration options are used
 */
#define CONFIG_HIGHMEM_START 0xfe000000
#define CONFIG_LOWMEM_SIZE 0x30000000
#define CONFIG_KERNEL_START 0xc0000000
#define CONFIG_TASK_SIZE 0x80000000
#define CONFIG_BOOT_LOAD 0x00800000

/*
 * Device Drivers
 */

/*
 * Generic Driver Options
 */
#undef CONFIG_STANDALONE
#define CONFIG_PREVENT_FIRMWARE_BUILD 1
#undef CONFIG_FW_LOADER

/*
 * Memory Technology Devices (MTD)
 */
#undef CONFIG_MTD

/*
 * Parallel port support
 */
#undef CONFIG_PARPORT

/*
 * Plug and Play support
 */
#undef CONFIG_PNP

/*
 * Block devices
 */
#define CONFIG_BLK_DEV_FD_MODULE 1
#undef CONFIG_MAC_FLOPPY
#undef CONFIG_BLK_DEV_XD
#undef CONFIG_BLK_CPQ_DA
#undef CONFIG_BLK_CPQ_CISS_DA
#undef CONFIG_BLK_DEV_DAC960
#undef CONFIG_BLK_DEV_UMEM
#undef CONFIG_BLK_DEV_COW_COMMON
#define CONFIG_BLK_DEV_LOOP 1
#undef CONFIG_BLK_DEV_CRYPTOLOOP
#undef CONFIG_BLK_DEV_NBD
#undef CONFIG_BLK_DEV_SX8
#undef CONFIG_BLK_DEV_UB
#define CONFIG_BLK_DEV_RAM 1
#define CONFIG_BLK_DEV_RAM_COUNT 16
#define CONFIG_BLK_DEV_RAM_SIZE 4096
#define CONFIG_BLK_DEV_INITRD 1
#define CONFIG_INITRAMFS_SOURCE ""
#define CONFIG_LBD 1
#undef CONFIG_CDROM_PKTCDVD

/*
 * IO Schedulers
 */
#define CONFIG_IOSCHED_NOOP 1
#define CONFIG_IOSCHED_AS 1
#define CONFIG_IOSCHED_DEADLINE 1
#define CONFIG_IOSCHED_CFQ 1
#undef CONFIG_ATA_OVER_ETH

/*
 * ATA/ATAPI/MFM/RLL support
 */
#define CONFIG_IDE 1
#define CONFIG_BLK_DEV_IDE 1

/*
 * Please see Documentation/ide.txt for help/info on IDE drives
 */
#undef CONFIG_BLK_DEV_IDE_SATA
#define CONFIG_BLK_DEV_IDEDISK 1
#undef CONFIG_IDEDISK_MULTI_MODE
#define CONFIG_BLK_DEV_IDECD 1
#undef CONFIG_BLK_DEV_IDETAPE
#define CONFIG_BLK_DEV_IDEFLOPPY 1
#define CONFIG_BLK_DEV_IDESCSI 1
#undef CONFIG_IDE_TASK_IOCTL

/*
 * IDE chipset support/bugfixes
 */
#define CONFIG_IDE_GENERIC 1
#define CONFIG_BLK_DEV_IDEPCI 1
#define CONFIG_IDEPCI_SHARE_IRQ 1
#undef CONFIG_BLK_DEV_OFFBOARD
#define CONFIG_BLK_DEV_GENERIC 1
#undef CONFIG_BLK_DEV_OPTI621
#define CONFIG_BLK_DEV_SL82C105 1
#define CONFIG_BLK_DEV_IDEDMA_PCI 1
#undef CONFIG_BLK_DEV_IDEDMA_FORCED
#define CONFIG_IDEDMA_PCI_AUTO 1
#undef CONFIG_IDEDMA_ONLYDISK
#undef CONFIG_BLK_DEV_AEC62XX
#undef CONFIG_BLK_DEV_ALI15X3
#undef CONFIG_BLK_DEV_AMD74XX
#define CONFIG_BLK_DEV_CMD64X 1
#undef CONFIG_BLK_DEV_TRIFLEX
#undef CONFIG_BLK_DEV_CY82C693
#undef CONFIG_BLK_DEV_CS5520
#undef CONFIG_BLK_DEV_CS5530
#undef CONFIG_BLK_DEV_HPT34X
#undef CONFIG_BLK_DEV_HPT366
#undef CONFIG_BLK_DEV_SC1200
#undef CONFIG_BLK_DEV_PIIX
#undef CONFIG_BLK_DEV_NS87415
#undef CONFIG_BLK_DEV_PDC202XX_OLD
#define CONFIG_BLK_DEV_PDC202XX_NEW 1
#undef CONFIG_PDC202XX_FORCE
#undef CONFIG_BLK_DEV_SVWKS
#undef CONFIG_BLK_DEV_SIIMAGE
#undef CONFIG_BLK_DEV_SLC90E66
#undef CONFIG_BLK_DEV_TRM290
#undef CONFIG_BLK_DEV_VIA82CXXX
#define CONFIG_BLK_DEV_IDE_PMAC 1
#define CONFIG_BLK_DEV_IDE_PMAC_ATA100FIRST 1
#define CONFIG_BLK_DEV_IDEDMA_PMAC 1
#define CONFIG_BLK_DEV_IDE_PMAC_BLINK 1
#undef CONFIG_IDE_ARM
#undef CONFIG_IDE_CHIPSETS
#define CONFIG_BLK_DEV_IDEDMA 1
#undef CONFIG_IDEDMA_IVB
#define CONFIG_IDEDMA_AUTO 1
#undef CONFIG_BLK_DEV_HD

/*
 * SCSI device support
 */
#define CONFIG_SCSI 1
#define CONFIG_SCSI_PROC_FS 1

/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#define CONFIG_BLK_DEV_SD 1
#define CONFIG_CHR_DEV_ST 1
#undef CONFIG_CHR_DEV_OSST
#define CONFIG_BLK_DEV_SR 1
#define CONFIG_BLK_DEV_SR_VENDOR 1
#define CONFIG_CHR_DEV_SG 1

/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#undef CONFIG_SCSI_MULTI_LUN
#define CONFIG_SCSI_CONSTANTS 1
#undef CONFIG_SCSI_LOGGING

/*
 * SCSI Transport Attributes
 */
#define CONFIG_SCSI_SPI_ATTRS 1
#undef CONFIG_SCSI_FC_ATTRS
#undef CONFIG_SCSI_ISCSI_ATTRS

/*
 * SCSI low-level drivers
 */
#undef CONFIG_BLK_DEV_3W_XXXX_RAID
#undef CONFIG_SCSI_3W_9XXX
#undef CONFIG_SCSI_7000FASST
#undef CONFIG_SCSI_ACARD
#undef CONFIG_SCSI_AHA152X
#undef CONFIG_SCSI_AHA1542
#undef CONFIG_SCSI_AACRAID
#define CONFIG_SCSI_AIC7XXX_MODULE 1
#define CONFIG_AIC7XXX_CMDS_PER_DEVICE 253
#define CONFIG_AIC7XXX_RESET_DELAY_MS 15000
#define CONFIG_AIC7XXX_DEBUG_ENABLE 1
#define CONFIG_AIC7XXX_DEBUG_MASK 0
#define CONFIG_AIC7XXX_REG_PRETTY_PRINT 1
#define CONFIG_SCSI_AIC7XXX_OLD_MODULE 1
#undef CONFIG_SCSI_AIC79XX
#undef CONFIG_SCSI_DPT_I2O
#undef CONFIG_SCSI_IN2000
#undef CONFIG_MEGARAID_NEWGEN
#undef CONFIG_MEGARAID_LEGACY
#undef CONFIG_SCSI_SATA
#undef CONFIG_SCSI_BUSLOGIC
#undef CONFIG_SCSI_DMX3191D
#undef CONFIG_SCSI_DTC3280
#undef CONFIG_SCSI_EATA
#undef CONFIG_SCSI_FUTURE_DOMAIN
#undef CONFIG_SCSI_GDTH
#undef CONFIG_SCSI_GENERIC_NCR5380
#undef CONFIG_SCSI_GENERIC_NCR5380_MMIO
#undef CONFIG_SCSI_IPS
#undef CONFIG_SCSI_INITIO
#undef CONFIG_SCSI_INIA100
#undef CONFIG_SCSI_NCR53C406A
#define CONFIG_SCSI_SYM53C8XX_2 1
#define CONFIG_SCSI_SYM53C8XX_DMA_ADDRESSING_MODE 0
#define CONFIG_SCSI_SYM53C8XX_DEFAULT_TAGS 16
#define CONFIG_SCSI_SYM53C8XX_MAX_TAGS 64
#undef CONFIG_SCSI_SYM53C8XX_IOMAPPED
#undef CONFIG_SCSI_IPR
#undef CONFIG_SCSI_PAS16
#undef CONFIG_SCSI_PSI240I
#undef CONFIG_SCSI_QLOGIC_FAS
#undef CONFIG_SCSI_QLOGIC_FC
#undef CONFIG_SCSI_QLOGIC_1280
#define CONFIG_SCSI_QLA2XXX 1
#undef CONFIG_SCSI_QLA21XX
#undef CONFIG_SCSI_QLA22XX
#undef CONFIG_SCSI_QLA2300
#undef CONFIG_SCSI_QLA2322
#undef CONFIG_SCSI_QLA6312
#undef CONFIG_SCSI_LPFC
#undef CONFIG_SCSI_SYM53C416
#undef CONFIG_SCSI_DC395x
#undef CONFIG_SCSI_DC390T
#undef CONFIG_SCSI_T128
#undef CONFIG_SCSI_U14_34F
#undef CONFIG_SCSI_NSP32
#undef CONFIG_SCSI_DEBUG
#define CONFIG_SCSI_MESH 1
#define CONFIG_SCSI_MESH_SYNC_RATE 5
#define CONFIG_SCSI_MESH_RESET_DELAY_MS 4000
#define CONFIG_SCSI_MAC53C94 1

/*
 * Old CD-ROM drivers (not SCSI, not IDE)
 */
#undef CONFIG_CD_NO_IDESCSI

/*
 * Multi-device support (RAID and LVM)
 */
#undef CONFIG_MD

/*
 * Fusion MPT device support
 */
#undef CONFIG_FUSION

/*
 * IEEE 1394 (FireWire) support
 */
#undef CONFIG_IEEE1394

/*
 * I2O device support
 */
#undef CONFIG_I2O

/*
 * Macintosh device drivers
 */
#define CONFIG_ADB 1
#define CONFIG_ADB_CUDA 1
#define CONFIG_ADB_PMU 1
#define CONFIG_PMAC_PBOOK 1
#define CONFIG_PMAC_APM_EMU 1
#define CONFIG_PMAC_BACKLIGHT 1
#define CONFIG_ADB_MACIO 1
#define CONFIG_INPUT_ADBHID 1
#define CONFIG_MAC_EMUMOUSEBTN 1
#define CONFIG_THERM_WINDTUNNEL_MODULE 1
#define CONFIG_THERM_ADT746X_MODULE 1
#undef CONFIG_ANSLCD

/*
 * Networking support
 */
#define CONFIG_NET 1

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#undef CONFIG_PACKET_MMAP
#define CONFIG_UNIX 1
#undef CONFIG_NET_KEY
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#undef CONFIG_IP_ADVANCED_ROUTER
#undef CONFIG_IP_PNP
#undef CONFIG_NET_IPIP
#undef CONFIG_NET_IPGRE
#undef CONFIG_IP_MROUTE
#undef CONFIG_ARPD
#define CONFIG_SYN_COOKIES 1
#undef CONFIG_INET_AH
#undef CONFIG_INET_ESP
#undef CONFIG_INET_IPCOMP
#undef CONFIG_INET_TUNNEL
#define CONFIG_IP_TCPDIAG 1
#undef CONFIG_IP_TCPDIAG_IPV6

/*
 * IP: Virtual Server Configuration
 */
#undef CONFIG_IP_VS
#undef CONFIG_IPV6
#define CONFIG_NETFILTER 1
#undef CONFIG_NETFILTER_DEBUG

/*
 * IP: Netfilter Configuration
 */
#define CONFIG_IP_NF_CONNTRACK_MODULE 1
#undef CONFIG_IP_NF_CT_ACCT
#undef CONFIG_IP_NF_CONNTRACK_MARK
#undef CONFIG_IP_NF_CT_PROTO_SCTP
#define CONFIG_IP_NF_FTP_MODULE 1
#define CONFIG_IP_NF_IRC_MODULE 1
#define CONFIG_IP_NF_TFTP_MODULE 1
#define CONFIG_IP_NF_AMANDA_MODULE 1
#undef CONFIG_IP_NF_QUEUE
#define CONFIG_IP_NF_IPTABLES_MODULE 1
#define CONFIG_IP_NF_MATCH_LIMIT_MODULE 1
#define CONFIG_IP_NF_MATCH_IPRANGE_MODULE 1
#define CONFIG_IP_NF_MATCH_MAC_MODULE 1
#define CONFIG_IP_NF_MATCH_PKTTYPE_MODULE 1
#define CONFIG_IP_NF_MATCH_MARK_MODULE 1
#define CONFIG_IP_NF_MATCH_MULTIPORT_MODULE 1
#define CONFIG_IP_NF_MATCH_TOS_MODULE 1
#define CONFIG_IP_NF_MATCH_RECENT_MODULE 1
#define CONFIG_IP_NF_MATCH_ECN_MODULE 1
#define CONFIG_IP_NF_MATCH_DSCP_MODULE 1
#define CONFIG_IP_NF_MATCH_AH_ESP_MODULE 1
#define CONFIG_IP_NF_MATCH_LENGTH_MODULE 1
#define CONFIG_IP_NF_MATCH_TTL_MODULE 1
#define CONFIG_IP_NF_MATCH_TCPMSS_MODULE 1
#define CONFIG_IP_NF_MATCH_HELPER_MODULE 1
#define CONFIG_IP_NF_MATCH_STATE_MODULE 1
#define CONFIG_IP_NF_MATCH_CONNTRACK_MODULE 1
#define CONFIG_IP_NF_MATCH_OWNER_MODULE 1
#undef CONFIG_IP_NF_MATCH_ADDRTYPE
#undef CONFIG_IP_NF_MATCH_REALM
#undef CONFIG_IP_NF_MATCH_SCTP
#undef CONFIG_IP_NF_MATCH_COMMENT
#undef CONFIG_IP_NF_MATCH_HASHLIMIT
#define CONFIG_IP_NF_FILTER_MODULE 1
#define CONFIG_IP_NF_TARGET_REJECT_MODULE 1
#undef CONFIG_IP_NF_TARGET_LOG
#define CONFIG_IP_NF_TARGET_ULOG_MODULE 1
#define CONFIG_IP_NF_TARGET_TCPMSS_MODULE 1
#define CONFIG_IP_NF_NAT_MODULE 1
#define CONFIG_IP_NF_NAT_NEEDED 1
#define CONFIG_IP_NF_TARGET_MASQUERADE_MODULE 1
#define CONFIG_IP_NF_TARGET_REDIRECT_MODULE 1
#define CONFIG_IP_NF_TARGET_NETMAP_MODULE 1
#define CONFIG_IP_NF_TARGET_SAME_MODULE 1
#define CONFIG_IP_NF_NAT_SNMP_BASIC_MODULE 1
#define CONFIG_IP_NF_NAT_IRC_MODULE 1
#define CONFIG_IP_NF_NAT_FTP_MODULE 1
#define CONFIG_IP_NF_NAT_TFTP_MODULE 1
#define CONFIG_IP_NF_NAT_AMANDA_MODULE 1
#undef CONFIG_IP_NF_MANGLE
#define CONFIG_IP_NF_RAW_MODULE 1
#define CONFIG_IP_NF_TARGET_NOTRACK_MODULE 1
#undef CONFIG_IP_NF_ARPTABLES

/*
 * SCTP Configuration (EXPERIMENTAL)
 */
#undef CONFIG_IP_SCTP
#undef CONFIG_ATM
#undef CONFIG_BRIDGE
#undef CONFIG_VLAN_8021Q
#undef CONFIG_DECNET
#undef CONFIG_LLC2
#undef CONFIG_IPX
#undef CONFIG_ATALK
#undef CONFIG_X25
#undef CONFIG_LAPB
#undef CONFIG_NET_DIVERT
#undef CONFIG_ECONET
#undef CONFIG_WAN_ROUTER

/*
 * QoS and/or fair queueing
 */
#undef CONFIG_NET_SCHED
#undef CONFIG_NET_CLS_ROUTE

/*
 * Network testing
 */
#undef CONFIG_NET_PKTGEN
#undef CONFIG_NETPOLL
#undef CONFIG_NET_POLL_CONTROLLER
#undef CONFIG_HAMRADIO
#undef CONFIG_IRDA
#undef CONFIG_BT
#define CONFIG_NETDEVICES 1
#undef CONFIG_DUMMY
#undef CONFIG_BONDING
#undef CONFIG_EQUALIZER
#undef CONFIG_TUN

/*
 * ARCnet devices
 */
#undef CONFIG_ARCNET

/*
 * Ethernet (10 or 100Mbit)
 */
#define CONFIG_NET_ETHERNET 1
#define CONFIG_MII 1
#define CONFIG_MACE 1
#undef CONFIG_MACE_AAUI_PORT
#define CONFIG_BMAC 1
#undef CONFIG_HAPPYMEAL
#define CONFIG_SUNGEM 1
#undef CONFIG_NET_VENDOR_3COM
#undef CONFIG_LANCE
#undef CONFIG_NET_VENDOR_SMC
#undef CONFIG_NET_VENDOR_RACAL

/*
 * Tulip family network device support
 */
#define CONFIG_NET_TULIP 1
#define CONFIG_DE2104X 1
#define CONFIG_TULIP 1
#undef CONFIG_TULIP_MWI
#define CONFIG_TULIP_MMIO 1
#undef CONFIG_TULIP_NAPI
#define CONFIG_DE4X5_MODULE 1
#undef CONFIG_WINBOND_840
#undef CONFIG_DM9102
#undef CONFIG_AT1700
#undef CONFIG_DEPCA
#undef CONFIG_HP100
#undef CONFIG_NET_ISA
#define CONFIG_NET_PCI 1
#define CONFIG_PCNET32 1
#undef CONFIG_AMD8111_ETH
#undef CONFIG_ADAPTEC_STARFIRE
#undef CONFIG_AC3200
#undef CONFIG_APRICOT
#undef CONFIG_B44
#undef CONFIG_FORCEDETH
#undef CONFIG_CS89x0
#undef CONFIG_DGRS
#undef CONFIG_EEPRO100
#undef CONFIG_E100
#undef CONFIG_FEALNX
#undef CONFIG_NATSEMI
#undef CONFIG_NE2K_PCI
#undef CONFIG_8139CP
#undef CONFIG_8139TOO
#undef CONFIG_SIS900
#undef CONFIG_EPIC100
#undef CONFIG_SUNDANCE
#undef CONFIG_TLAN
#undef CONFIG_VIA_RHINE
#undef CONFIG_NET_POCKET

/*
 * Ethernet (1000 Mbit)
 */
#undef CONFIG_ACENIC
#undef CONFIG_DL2K
#undef CONFIG_E1000
#undef CONFIG_NS83820
#undef CONFIG_HAMACHI
#undef CONFIG_YELLOWFIN
#undef CONFIG_R8169
#undef CONFIG_SK98LIN
#undef CONFIG_VIA_VELOCITY
#undef CONFIG_TIGON3
#undef CONFIG_BNX2
#undef CONFIG_MV643XX_ETH

/*
 * Ethernet (10000 Mbit)
 */
#undef CONFIG_IXGB
#undef CONFIG_S2IO

/*
 * Token Ring devices
 */
#undef CONFIG_TR

/*
 * Wireless LAN (non-hamradio)
 */
#define CONFIG_NET_RADIO 1

/*
 * Obsolete Wireless cards support (pre-802.11)
 */
#undef CONFIG_STRIP
#undef CONFIG_ARLAN
#undef CONFIG_WAVELAN

/*
 * Wireless 802.11b ISA/PCI cards support
 */
#undef CONFIG_AIRO
#define CONFIG_HERMES_MODULE 1
#define CONFIG_APPLE_AIRPORT_MODULE 1
#undef CONFIG_PLX_HERMES
#undef CONFIG_TMD_HERMES
#undef CONFIG_PCI_HERMES
#undef CONFIG_ATMEL

/*
 * Prism GT/Duette 802.11(a/b/g) PCI/Cardbus support
 */
#undef CONFIG_PRISM54
#define CONFIG_NET_WIRELESS 1

/*
 * Wan interfaces
 */
#undef CONFIG_WAN
#undef CONFIG_FDDI
#undef CONFIG_HIPPI
#define CONFIG_PPP 1
#define CONFIG_PPP_MULTILINK 1
#define CONFIG_PPP_FILTER 1
#define CONFIG_PPP_ASYNC 1
#undef CONFIG_PPP_SYNC_TTY
#define CONFIG_PPP_DEFLATE 1
#undef CONFIG_PPP_BSDCOMP
#undef CONFIG_PPPOE
#undef CONFIG_SLIP
#undef CONFIG_NET_FC
#undef CONFIG_SHAPER
#undef CONFIG_NETCONSOLE

/*
 * ISDN subsystem
 */
#undef CONFIG_ISDN

/*
 * Telephony Support
 */
#undef CONFIG_PHONE

/*
 * Input device support
 */
#define CONFIG_INPUT 1

/*
 * Userland interfaces
 */
#define CONFIG_INPUT_MOUSEDEV 1
#define CONFIG_INPUT_MOUSEDEV_PSAUX 1
#define CONFIG_INPUT_MOUSEDEV_SCREEN_X 1024
#define CONFIG_INPUT_MOUSEDEV_SCREEN_Y 768
#undef CONFIG_INPUT_JOYDEV
#undef CONFIG_INPUT_TSDEV
#define CONFIG_INPUT_EVDEV 1
#define CONFIG_INPUT_EVBUG_MODULE 1

/*
 * Input Device Drivers
 */
#define CONFIG_INPUT_KEYBOARD 1
#define CONFIG_KEYBOARD_ATKBD 1
#undef CONFIG_KEYBOARD_SUNKBD
#undef CONFIG_KEYBOARD_LKKBD
#undef CONFIG_KEYBOARD_XTKBD
#undef CONFIG_KEYBOARD_NEWTON
#define CONFIG_INPUT_MOUSE 1
#define CONFIG_MOUSE_PS2 1
#undef CONFIG_MOUSE_SERIAL
#undef CONFIG_MOUSE_INPORT
#undef CONFIG_MOUSE_LOGIBM
#undef CONFIG_MOUSE_PC110PAD
#undef CONFIG_MOUSE_VSXXXAA
#undef CONFIG_INPUT_JOYSTICK
#undef CONFIG_INPUT_TOUCHSCREEN
#define CONFIG_INPUT_MISC 1
#undef CONFIG_INPUT_PCSPKR
#define CONFIG_INPUT_UINPUT_MODULE 1

/*
 * Hardware I/O ports
 */
#define CONFIG_SERIO 1
#define CONFIG_SERIO_I8042 1
#undef CONFIG_SERIO_SERPORT
#undef CONFIG_SERIO_PCIPS2
#define CONFIG_SERIO_LIBPS2 1
#undef CONFIG_SERIO_RAW
#undef CONFIG_GAMEPORT

/*
 * Character devices
 */
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#define CONFIG_HW_CONSOLE 1
#undef CONFIG_SERIAL_NONSTANDARD

/*
 * Serial drivers
 */
#define CONFIG_SERIAL_8250_MODULE 1
#define CONFIG_SERIAL_8250_NR_UARTS 4
#undef CONFIG_SERIAL_8250_EXTENDED

/*
 * Non-8250 serial port support
 */
#define CONFIG_SERIAL_CORE 1
#define CONFIG_SERIAL_PMACZILOG 1
#undef CONFIG_SERIAL_PMACZILOG_CONSOLE
#undef CONFIG_SERIAL_JSM
#define CONFIG_UNIX98_PTYS 1
#define CONFIG_LEGACY_PTYS 1
#define CONFIG_LEGACY_PTY_COUNT 256

/*
 * IPMI
 */
#undef CONFIG_IPMI_HANDLER

/*
 * Watchdog Cards
 */
#undef CONFIG_WATCHDOG
#define CONFIG_NVRAM 1
#define CONFIG_GEN_RTC 1
#undef CONFIG_GEN_RTC_X
#undef CONFIG_DTLK
#undef CONFIG_R3964
#undef CONFIG_APPLICOM

/*
 * Ftape, the floppy tape device driver
 */
#undef CONFIG_AGP
#undef CONFIG_DRM
#undef CONFIG_RAW_DRIVER

/*
 * TPM devices
 */
#undef CONFIG_TCG_TPM

/*
 * I2C support
 */
#define CONFIG_I2C 1
#define CONFIG_I2C_CHARDEV_MODULE 1

/*
 * I2C Algorithms
 */
#define CONFIG_I2C_ALGOBIT 1
#undef CONFIG_I2C_ALGOPCF
#undef CONFIG_I2C_ALGOPCA

/*
 * I2C Hardware Bus support
 */
#undef CONFIG_I2C_ALI1535
#undef CONFIG_I2C_ALI1563
#undef CONFIG_I2C_ALI15X3
#undef CONFIG_I2C_AMD756
#undef CONFIG_I2C_AMD8111
#undef CONFIG_I2C_ELEKTOR
#define CONFIG_I2C_HYDRA 1
#undef CONFIG_I2C_I801
#undef CONFIG_I2C_I810
#undef CONFIG_I2C_PIIX4
#undef CONFIG_I2C_ISA
#define CONFIG_I2C_KEYWEST_MODULE 1
#undef CONFIG_I2C_MPC
#undef CONFIG_I2C_NFORCE2
#undef CONFIG_I2C_PARPORT_LIGHT
#undef CONFIG_I2C_PROSAVAGE
#undef CONFIG_I2C_SAVAGE4
#undef CONFIG_SCx200_ACB
#undef CONFIG_I2C_SIS5595
#undef CONFIG_I2C_SIS630
#undef CONFIG_I2C_SIS96X
#undef CONFIG_I2C_STUB
#undef CONFIG_I2C_VIA
#undef CONFIG_I2C_VIAPRO
#undef CONFIG_I2C_VOODOO3
#undef CONFIG_I2C_PCA_ISA

/*
 * Hardware Sensors Chip support
 */
#undef CONFIG_I2C_SENSOR
#undef CONFIG_SENSORS_ADM1021
#undef CONFIG_SENSORS_ADM1025
#undef CONFIG_SENSORS_ADM1026
#undef CONFIG_SENSORS_ADM1031
#undef CONFIG_SENSORS_ASB100
#undef CONFIG_SENSORS_DS1621
#undef CONFIG_SENSORS_FSCHER
#undef CONFIG_SENSORS_FSCPOS
#undef CONFIG_SENSORS_GL518SM
#undef CONFIG_SENSORS_GL520SM
#undef CONFIG_SENSORS_IT87
#undef CONFIG_SENSORS_LM63
#undef CONFIG_SENSORS_LM75
#undef CONFIG_SENSORS_LM77
#undef CONFIG_SENSORS_LM78
#undef CONFIG_SENSORS_LM80
#undef CONFIG_SENSORS_LM83
#undef CONFIG_SENSORS_LM85
#undef CONFIG_SENSORS_LM87
#undef CONFIG_SENSORS_LM90
#undef CONFIG_SENSORS_LM92
#undef CONFIG_SENSORS_MAX1619
#undef CONFIG_SENSORS_PC87360
#undef CONFIG_SENSORS_SMSC47B397
#undef CONFIG_SENSORS_SIS5595
#undef CONFIG_SENSORS_SMSC47M1
#undef CONFIG_SENSORS_VIA686A
#undef CONFIG_SENSORS_W83781D
#undef CONFIG_SENSORS_W83L785TS
#undef CONFIG_SENSORS_W83627HF

/*
 * Other I2C Chip support
 */
#undef CONFIG_SENSORS_DS1337
#undef CONFIG_SENSORS_EEPROM
#undef CONFIG_SENSORS_PCF8574
#undef CONFIG_SENSORS_PCF8591
#undef CONFIG_SENSORS_RTC8564
#undef CONFIG_SENSORS_M41T00
#undef CONFIG_I2C_DEBUG_CORE
#undef CONFIG_I2C_DEBUG_ALGO
#undef CONFIG_I2C_DEBUG_BUS
#undef CONFIG_I2C_DEBUG_CHIP

/*
 * Dallas's 1-wire bus
 */
#undef CONFIG_W1

/*
 * Misc devices
 */

/*
 * Multimedia devices
 */
#undef CONFIG_VIDEO_DEV

/*
 * Digital Video Broadcasting Devices
 */
#undef CONFIG_DVB

/*
 * Graphics support
 */
#define CONFIG_FB 1
#define CONFIG_FB_CFB_FILLRECT 1
#define CONFIG_FB_CFB_COPYAREA 1
#define CONFIG_FB_CFB_IMAGEBLIT 1
#define CONFIG_FB_SOFT_CURSOR 1
#define CONFIG_FB_MACMODES 1
#define CONFIG_FB_MODE_HELPERS 1
#define CONFIG_FB_TILEBLITTING 1
#undef CONFIG_FB_CIRRUS
#undef CONFIG_FB_PM2
#undef CONFIG_FB_CYBER2000
#define CONFIG_FB_OF 1
#define CONFIG_FB_CONTROL 1
#define CONFIG_FB_PLATINUM 1
#define CONFIG_FB_VALKYRIE 1
#define CONFIG_FB_CT65550 1
#undef CONFIG_FB_ASILIANT
#define CONFIG_FB_IMSTT 1
#undef CONFIG_FB_VGA16
#undef CONFIG_FB_NVIDIA
#undef CONFIG_FB_RIVA
#define CONFIG_FB_MATROX 1
#define CONFIG_FB_MATROX_MILLENIUM 1
#define CONFIG_FB_MATROX_MYSTIQUE 1
#undef CONFIG_FB_MATROX_G
#define CONFIG_FB_MATROX_I2C 1
#undef CONFIG_FB_MATROX_MULTIHEAD
#undef CONFIG_FB_RADEON_OLD
#define CONFIG_FB_RADEON 1
#define CONFIG_FB_RADEON_I2C 1
#undef CONFIG_FB_RADEON_DEBUG
#define CONFIG_FB_ATY128 1
#define CONFIG_FB_ATY 1
#define CONFIG_FB_ATY_CT 1
#undef CONFIG_FB_ATY_GENERIC_LCD
#undef CONFIG_FB_ATY_XL_INIT
#define CONFIG_FB_ATY_GX 1
#undef CONFIG_FB_SAVAGE
#undef CONFIG_FB_SIS
#undef CONFIG_FB_NEOMAGIC
#undef CONFIG_FB_KYRO
#define CONFIG_FB_3DFX 1
#undef CONFIG_FB_3DFX_ACCEL
#undef CONFIG_FB_VOODOO1
#undef CONFIG_FB_TRIDENT
#undef CONFIG_FB_S1D13XXX
#undef CONFIG_FB_VIRTUAL

/*
 * Console display driver support
 */
#define CONFIG_VGA_CONSOLE 1
#undef CONFIG_MDA_CONSOLE
#define CONFIG_DUMMY_CONSOLE 1
#define CONFIG_FRAMEBUFFER_CONSOLE 1
#undef CONFIG_FONTS
#define CONFIG_FONT_8x8 1
#define CONFIG_FONT_8x16 1

/*
 * Logo configuration
 */
#define CONFIG_LOGO 1
#define CONFIG_LOGO_LINUX_MONO 1
#define CONFIG_LOGO_LINUX_VGA16 1
#define CONFIG_LOGO_LINUX_CLUT224 1
#undef CONFIG_BACKLIGHT_LCD_SUPPORT

/*
 * Sound
 */
#define CONFIG_SOUND_MODULE 1
#define CONFIG_DMASOUND_PMAC_MODULE 1
#define CONFIG_DMASOUND_MODULE 1

/*
 * Advanced Linux Sound Architecture
 */
#define CONFIG_SND_MODULE 1
#define CONFIG_SND_TIMER_MODULE 1
#define CONFIG_SND_PCM_MODULE 1
#define CONFIG_SND_HWDEP_MODULE 1
#define CONFIG_SND_RAWMIDI_MODULE 1
#define CONFIG_SND_SEQUENCER_MODULE 1
#undef CONFIG_SND_SEQ_DUMMY
#define CONFIG_SND_OSSEMUL 1
#define CONFIG_SND_MIXER_OSS_MODULE 1
#define CONFIG_SND_PCM_OSS_MODULE 1
#define CONFIG_SND_SEQUENCER_OSS 1
#undef CONFIG_SND_VERBOSE_PRINTK
#undef CONFIG_SND_DEBUG
#define CONFIG_SND_GENERIC_PM 1

/*
 * Generic devices
 */
#define CONFIG_SND_MPU401_UART_MODULE 1
#define CONFIG_SND_OPL3_LIB_MODULE 1
#undef CONFIG_SND_DUMMY
#undef CONFIG_SND_VIRMIDI
#undef CONFIG_SND_MTPAV
#undef CONFIG_SND_SERIAL_U16550
#undef CONFIG_SND_MPU401

/*
 * ISA devices
 */
#define CONFIG_SND_CS4231_LIB_MODULE 1
#undef CONFIG_SND_AD1848
#undef CONFIG_SND_CS4231
#define CONFIG_SND_CS4232_MODULE 1
#undef CONFIG_SND_CS4236
#undef CONFIG_SND_ES1688
#undef CONFIG_SND_ES18XX
#undef CONFIG_SND_GUSCLASSIC
#undef CONFIG_SND_GUSEXTREME
#undef CONFIG_SND_GUSMAX
#undef CONFIG_SND_INTERWAVE
#undef CONFIG_SND_INTERWAVE_STB
#undef CONFIG_SND_OPTI92X_AD1848
#undef CONFIG_SND_OPTI92X_CS4231
#undef CONFIG_SND_OPTI93X
#undef CONFIG_SND_SB8
#undef CONFIG_SND_SB16
#undef CONFIG_SND_SBAWE
#undef CONFIG_SND_WAVEFRONT
#undef CONFIG_SND_CMI8330
#undef CONFIG_SND_OPL3SA2
#undef CONFIG_SND_SGALAXY
#undef CONFIG_SND_SSCAPE

/*
 * PCI devices
 */
#undef CONFIG_SND_ALI5451
#undef CONFIG_SND_ATIIXP
#undef CONFIG_SND_ATIIXP_MODEM
#undef CONFIG_SND_AU8810
#undef CONFIG_SND_AU8820
#undef CONFIG_SND_AU8830
#undef CONFIG_SND_AZT3328
#undef CONFIG_SND_BT87X
#undef CONFIG_SND_CS46XX
#undef CONFIG_SND_CS4281
#undef CONFIG_SND_EMU10K1
#undef CONFIG_SND_EMU10K1X
#undef CONFIG_SND_CA0106
#undef CONFIG_SND_KORG1212
#undef CONFIG_SND_MIXART
#undef CONFIG_SND_NM256
#undef CONFIG_SND_RME32
#undef CONFIG_SND_RME96
#undef CONFIG_SND_RME9652
#undef CONFIG_SND_HDSP
#undef CONFIG_SND_TRIDENT
#undef CONFIG_SND_YMFPCI
#undef CONFIG_SND_ALS4000
#undef CONFIG_SND_CMIPCI
#undef CONFIG_SND_ENS1370
#undef CONFIG_SND_ENS1371
#undef CONFIG_SND_ES1938
#undef CONFIG_SND_ES1968
#undef CONFIG_SND_MAESTRO3
#undef CONFIG_SND_FM801
#undef CONFIG_SND_ICE1712
#undef CONFIG_SND_ICE1724
#undef CONFIG_SND_INTEL8X0
#undef CONFIG_SND_INTEL8X0M
#undef CONFIG_SND_SONICVIBES
#undef CONFIG_SND_VIA82XX
#undef CONFIG_SND_VIA82XX_MODEM
#undef CONFIG_SND_VX222
#undef CONFIG_SND_HDA_INTEL

/*
 * ALSA PowerMac devices
 */
#define CONFIG_SND_POWERMAC_MODULE 1

/*
 * USB devices
 */
#define CONFIG_SND_USB_AUDIO_MODULE 1
#undef CONFIG_SND_USB_USX2Y

/*
 * Open Sound System
 */
#undef CONFIG_SOUND_PRIME

/*
 * USB support
 */
#define CONFIG_USB_ARCH_HAS_HCD 1
#define CONFIG_USB_ARCH_HAS_OHCI 1
#define CONFIG_USB 1
#undef CONFIG_USB_DEBUG

/*
 * Miscellaneous USB options
 */
#define CONFIG_USB_DEVICEFS 1
#undef CONFIG_USB_BANDWIDTH
#undef CONFIG_USB_DYNAMIC_MINORS
#undef CONFIG_USB_SUSPEND
#undef CONFIG_USB_OTG

/*
 * USB Host Controller Drivers
 */
#undef CONFIG_USB_EHCI_HCD
#define CONFIG_USB_OHCI_HCD 1
#undef CONFIG_USB_OHCI_BIG_ENDIAN
#define CONFIG_USB_OHCI_LITTLE_ENDIAN 1
#undef CONFIG_USB_UHCI_HCD
#undef CONFIG_USB_SL811_HCD

/*
 * USB Device Class drivers
 */
#undef CONFIG_USB_AUDIO
#undef CONFIG_USB_BLUETOOTH_TTY
#undef CONFIG_USB_MIDI
#define CONFIG_USB_ACM_MODULE 1
#define CONFIG_USB_PRINTER_MODULE 1

/*
 * NOTE: USB_STORAGE enables SCSI, and 'SCSI disk support' may also be needed; see USB_STORAGE Help for more information
 */
#define CONFIG_USB_STORAGE_MODULE 1
#undef CONFIG_USB_STORAGE_DEBUG
#undef CONFIG_USB_STORAGE_DATAFAB
#define CONFIG_USB_STORAGE_FREECOM 1
#undef CONFIG_USB_STORAGE_ISD200
#define CONFIG_USB_STORAGE_DPCM 1
#undef CONFIG_USB_STORAGE_USBAT
#undef CONFIG_USB_STORAGE_SDDR09
#undef CONFIG_USB_STORAGE_SDDR55
#undef CONFIG_USB_STORAGE_JUMPSHOT

/*
 * USB Input Devices
 */
#define CONFIG_USB_HID 1
#define CONFIG_USB_HIDINPUT 1
#undef CONFIG_HID_FF
#undef CONFIG_USB_HIDDEV
#undef CONFIG_USB_AIPTEK
#undef CONFIG_USB_WACOM
#undef CONFIG_USB_KBTAB
#undef CONFIG_USB_POWERMATE
#undef CONFIG_USB_MTOUCH
#undef CONFIG_USB_EGALAX
#undef CONFIG_USB_XPAD
#undef CONFIG_USB_ATI_REMOTE

/*
 * USB Imaging devices
 */
#undef CONFIG_USB_MDC800
#undef CONFIG_USB_MICROTEK

/*
 * USB Multimedia devices
 */
#undef CONFIG_USB_DABUSB

/*
 * Video4Linux support is needed for USB Multimedia device support
 */

/*
 * USB Network Adapters
 */
#undef CONFIG_USB_CATC
#undef CONFIG_USB_KAWETH
#undef CONFIG_USB_PEGASUS
#undef CONFIG_USB_RTL8150
#undef CONFIG_USB_USBNET
#undef CONFIG_USB_ZD1201
#define CONFIG_USB_MON 1

/*
 * USB port drivers
 */

/*
 * USB Serial Converter support
 */
#define CONFIG_USB_SERIAL_MODULE 1
#undef CONFIG_USB_SERIAL_GENERIC
#undef CONFIG_USB_SERIAL_AIRPRIME
#undef CONFIG_USB_SERIAL_BELKIN
#undef CONFIG_USB_SERIAL_WHITEHEAT
#undef CONFIG_USB_SERIAL_DIGI_ACCELEPORT
#undef CONFIG_USB_SERIAL_CP2101
#undef CONFIG_USB_SERIAL_CYPRESS_M8
#undef CONFIG_USB_SERIAL_EMPEG
#undef CONFIG_USB_SERIAL_FTDI_SIO
#define CONFIG_USB_SERIAL_VISOR_MODULE 1
#undef CONFIG_USB_SERIAL_IPAQ
#undef CONFIG_USB_SERIAL_IR
#undef CONFIG_USB_SERIAL_EDGEPORT
#undef CONFIG_USB_SERIAL_EDGEPORT_TI
#undef CONFIG_USB_SERIAL_GARMIN
#undef CONFIG_USB_SERIAL_IPW
#undef CONFIG_USB_SERIAL_KEYSPAN_PDA
#define CONFIG_USB_SERIAL_KEYSPAN_MODULE 1
#undef CONFIG_USB_SERIAL_KEYSPAN_MPR
#define CONFIG_USB_SERIAL_KEYSPAN_USA28 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA28X 1
#undef CONFIG_USB_SERIAL_KEYSPAN_USA28XA
#undef CONFIG_USB_SERIAL_KEYSPAN_USA28XB
#define CONFIG_USB_SERIAL_KEYSPAN_USA19 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA18X 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19W 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19QW 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19QI 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA49W 1
#undef CONFIG_USB_SERIAL_KEYSPAN_USA49WLC
#undef CONFIG_USB_SERIAL_KLSI
#undef CONFIG_USB_SERIAL_KOBIL_SCT
#undef CONFIG_USB_SERIAL_MCT_U232
#undef CONFIG_USB_SERIAL_PL2303
#undef CONFIG_USB_SERIAL_HP4X
#undef CONFIG_USB_SERIAL_SAFE
#undef CONFIG_USB_SERIAL_TI
#undef CONFIG_USB_SERIAL_CYBERJACK
#undef CONFIG_USB_SERIAL_XIRCOM
#undef CONFIG_USB_SERIAL_OMNINET
#define CONFIG_USB_EZUSB 1

/*
 * USB Miscellaneous drivers
 */
#undef CONFIG_USB_EMI62
#undef CONFIG_USB_EMI26
#undef CONFIG_USB_AUERSWALD
#undef CONFIG_USB_RIO500
#undef CONFIG_USB_LEGOTOWER
#undef CONFIG_USB_LCD
#undef CONFIG_USB_LED
#undef CONFIG_USB_CYTHERM
#undef CONFIG_USB_PHIDGETKIT
#undef CONFIG_USB_PHIDGETSERVO
#undef CONFIG_USB_IDMOUSE
#undef CONFIG_USB_TEST

/*
 * USB ATM/DSL drivers
 */

/*
 * USB Gadget Support
 */
#undef CONFIG_USB_GADGET

/*
 * MMC/SD Card support
 */
#undef CONFIG_MMC

/*
 * InfiniBand support
 */
#undef CONFIG_INFINIBAND

/*
 * File systems
 */
#define CONFIG_EXT2_FS 1
#undef CONFIG_EXT2_FS_XATTR
#undef CONFIG_EXT3_FS
#undef CONFIG_JBD
#undef CONFIG_REISERFS_FS
#undef CONFIG_JFS_FS

/*
 * XFS support
 */
#undef CONFIG_XFS_FS
#undef CONFIG_MINIX_FS
#undef CONFIG_ROMFS_FS
#undef CONFIG_QUOTA
#define CONFIG_DNOTIFY 1
#undef CONFIG_AUTOFS_FS
#undef CONFIG_AUTOFS4_FS

/*
 * CD-ROM/DVD Filesystems
 */
#define CONFIG_ISO9660_FS 1
#undef CONFIG_JOLIET
#undef CONFIG_ZISOFS
#undef CONFIG_UDF_FS

/*
 * DOS/FAT/NT Filesystems
 */
#define CONFIG_FAT_FS_MODULE 1
#define CONFIG_MSDOS_FS_MODULE 1
#define CONFIG_VFAT_FS_MODULE 1
#define CONFIG_FAT_DEFAULT_CODEPAGE 437
#define CONFIG_FAT_DEFAULT_IOCHARSET "iso8859-1"
#undef CONFIG_NTFS_FS

/*
 * Pseudo filesystems
 */
#define CONFIG_PROC_FS 1
#define CONFIG_PROC_KCORE 1
#define CONFIG_SYSFS 1
#define CONFIG_DEVFS_FS 1
#undef CONFIG_DEVFS_MOUNT
#undef CONFIG_DEVFS_DEBUG
#undef CONFIG_DEVPTS_FS_XATTR
#define CONFIG_TMPFS 1
#undef CONFIG_TMPFS_XATTR
#undef CONFIG_HUGETLB_PAGE
#define CONFIG_RAMFS 1

/*
 * Miscellaneous filesystems
 */
#undef CONFIG_ADFS_FS
#undef CONFIG_AFFS_FS
#define CONFIG_HFS_FS_MODULE 1
#define CONFIG_HFSPLUS_FS_MODULE 1
#undef CONFIG_BEFS_FS
#undef CONFIG_BFS_FS
#undef CONFIG_EFS_FS
#undef CONFIG_CRAMFS
#undef CONFIG_VXFS_FS
#undef CONFIG_HPFS_FS
#undef CONFIG_QNX4FS_FS
#undef CONFIG_SYSV_FS
#undef CONFIG_UFS_FS

/*
 * Network File Systems
 */
#define CONFIG_NFS_FS 1
#define CONFIG_NFS_V3 1
#undef CONFIG_NFS_V4
#undef CONFIG_NFS_DIRECTIO
#define CONFIG_NFSD 1
#define CONFIG_NFSD_V3 1
#undef CONFIG_NFSD_V4
#define CONFIG_NFSD_TCP 1
#define CONFIG_LOCKD 1
#define CONFIG_LOCKD_V4 1
#define CONFIG_EXPORTFS 1
#define CONFIG_SUNRPC 1
#undef CONFIG_RPCSEC_GSS_KRB5
#undef CONFIG_RPCSEC_GSS_SPKM3
#undef CONFIG_SMB_FS
#undef CONFIG_CIFS
#undef CONFIG_NCP_FS
#undef CONFIG_CODA_FS
#undef CONFIG_AFS_FS

/*
 * Partition Types
 */
#define CONFIG_PARTITION_ADVANCED 1
#undef CONFIG_ACORN_PARTITION
#undef CONFIG_OSF_PARTITION
#undef CONFIG_AMIGA_PARTITION
#undef CONFIG_ATARI_PARTITION
#define CONFIG_MAC_PARTITION 1
#define CONFIG_MSDOS_PARTITION 1
#undef CONFIG_BSD_DISKLABEL
#undef CONFIG_MINIX_SUBPARTITION
#undef CONFIG_SOLARIS_X86_PARTITION
#undef CONFIG_UNIXWARE_DISKLABEL
#undef CONFIG_LDM_PARTITION
#undef CONFIG_SGI_PARTITION
#undef CONFIG_ULTRIX_PARTITION
#undef CONFIG_SUN_PARTITION
#undef CONFIG_EFI_PARTITION

/*
 * Native Language Support
 */
#define CONFIG_NLS 1
#define CONFIG_NLS_DEFAULT "iso8859-1"
#undef CONFIG_NLS_CODEPAGE_437
#undef CONFIG_NLS_CODEPAGE_737
#undef CONFIG_NLS_CODEPAGE_775
#undef CONFIG_NLS_CODEPAGE_850
#undef CONFIG_NLS_CODEPAGE_852
#undef CONFIG_NLS_CODEPAGE_855
#undef CONFIG_NLS_CODEPAGE_857
#undef CONFIG_NLS_CODEPAGE_860
#undef CONFIG_NLS_CODEPAGE_861
#undef CONFIG_NLS_CODEPAGE_862
#undef CONFIG_NLS_CODEPAGE_863
#undef CONFIG_NLS_CODEPAGE_864
#undef CONFIG_NLS_CODEPAGE_865
#undef CONFIG_NLS_CODEPAGE_866
#undef CONFIG_NLS_CODEPAGE_869
#undef CONFIG_NLS_CODEPAGE_936
#undef CONFIG_NLS_CODEPAGE_950
#undef CONFIG_NLS_CODEPAGE_932
#undef CONFIG_NLS_CODEPAGE_949
#undef CONFIG_NLS_CODEPAGE_874
#undef CONFIG_NLS_ISO8859_8
#undef CONFIG_NLS_CODEPAGE_1250
#undef CONFIG_NLS_CODEPAGE_1251
#undef CONFIG_NLS_ASCII
#define CONFIG_NLS_ISO8859_1_MODULE 1
#undef CONFIG_NLS_ISO8859_2
#undef CONFIG_NLS_ISO8859_3
#undef CONFIG_NLS_ISO8859_4
#undef CONFIG_NLS_ISO8859_5
#undef CONFIG_NLS_ISO8859_6
#undef CONFIG_NLS_ISO8859_7
#undef CONFIG_NLS_ISO8859_9
#undef CONFIG_NLS_ISO8859_13
#undef CONFIG_NLS_ISO8859_14
#undef CONFIG_NLS_ISO8859_15
#undef CONFIG_NLS_KOI8_R
#undef CONFIG_NLS_KOI8_U
#define CONFIG_NLS_UTF8_MODULE 1

/*
 * Library routines
 */
#define CONFIG_CRC_CCITT 1
#define CONFIG_CRC32 1
#undef CONFIG_LIBCRC32C
#define CONFIG_ZLIB_INFLATE 1
#define CONFIG_ZLIB_DEFLATE 1

/*
 * Profiling support
 */
#undef CONFIG_PROFILING

/*
 * Kernel hacking
 */
#undef CONFIG_PRINTK_TIME
#undef CONFIG_DEBUG_KERNEL
#define CONFIG_LOG_BUF_SHIFT 14
#define CONFIG_BOOTX_TEXT 1

/*
 * Security options
 */
#undef CONFIG_KEYS
#undef CONFIG_SECURITY

/*
 * Cryptographic options
 */
#undef CONFIG_CRYPTO

/*
 * Hardware crypto devices
 */
