/*
 * Automatically generated C config: don't edit
 * Linux kernel version: 2.6.12
 * Sat Jun 18 16:11:40 2005
 */
#define AUTOCONF_INCLUDED
#define CONFIG_MIPS 1
#undef CONFIG_MIPS64
#undef CONFIG_64BIT
#define CONFIG_MIPS32 1

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1
#define CONFIG_CLEAN_COMPILE 1
#define CONFIG_BROKEN_ON_SMP 1
#define CONFIG_INIT_ENV_ARG_LIMIT 32

/*
 * General setup
 */
#define CONFIG_LOCALVERSION ""
#define CONFIG_SWAP 1
#define CONFIG_SYSVIPC 1
#undef CONFIG_POSIX_MQUEUE
#undef CONFIG_BSD_PROCESS_ACCT
#define CONFIG_SYSCTL 1
#undef CONFIG_AUDIT
#undef CONFIG_HOTPLUG
#define CONFIG_KOBJECT_UEVENT 1
#define CONFIG_IKCONFIG 1
#define CONFIG_IKCONFIG_PROC 1
#define CONFIG_EMBEDDED 1
#define CONFIG_KALLSYMS 1
#undef CONFIG_KALLSYMS_EXTRA_PASS
#define CONFIG_PRINTK 1
#define CONFIG_BUG 1
#define CONFIG_BASE_FULL 1
#define CONFIG_FUTEX 1
#define CONFIG_EPOLL 1
#undef CONFIG_CC_OPTIMIZE_FOR_SIZE
#define CONFIG_SHMEM 1
#define CONFIG_CC_ALIGN_FUNCTIONS 0
#define CONFIG_CC_ALIGN_LABELS 0
#define CONFIG_CC_ALIGN_LOOPS 0
#define CONFIG_CC_ALIGN_JUMPS 0
#undef CONFIG_TINY_SHMEM
#define CONFIG_BASE_SMALL 0

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#define CONFIG_MODULE_UNLOAD 1
#undef CONFIG_MODULE_FORCE_UNLOAD
#define CONFIG_OBSOLETE_MODPARM 1
#define CONFIG_MODVERSIONS 1
#define CONFIG_MODULE_SRCVERSION_ALL 1
#define CONFIG_KMOD 1

/*
 * Machine selection
 */
#undef CONFIG_MACH_JAZZ
#undef CONFIG_MACH_VR41XX
#undef CONFIG_TOSHIBA_JMR3927
#undef CONFIG_MIPS_COBALT
#undef CONFIG_MACH_DECSTATION
#undef CONFIG_MIPS_EV64120
#undef CONFIG_MIPS_EV96100
#undef CONFIG_MIPS_IVR
#undef CONFIG_LASAT
#undef CONFIG_MIPS_ITE8172
#undef CONFIG_MIPS_ATLAS
#undef CONFIG_MIPS_MALTA
#undef CONFIG_MIPS_SEAD
#undef CONFIG_MOMENCO_OCELOT
#undef CONFIG_MOMENCO_OCELOT_G
#undef CONFIG_MOMENCO_OCELOT_C
#undef CONFIG_MOMENCO_OCELOT_3
#undef CONFIG_MOMENCO_JAGUAR_ATX
#undef CONFIG_PMC_YOSEMITE
#undef CONFIG_DDB5074
#undef CONFIG_DDB5476
#undef CONFIG_DDB5477
#undef CONFIG_NEC_OSPREY
#define CONFIG_SGI_IP22 1
#undef CONFIG_SOC_AU1X00
#undef CONFIG_SIBYTE_SB1xxx_SOC
#undef CONFIG_SNI_RM200_PCI
#undef CONFIG_TOSHIBA_RBTX4927
#define CONFIG_RWSEM_GENERIC_SPINLOCK 1
#define CONFIG_GENERIC_CALIBRATE_DELAY 1
#define CONFIG_HAVE_DEC_LOCK 1
#define CONFIG_ARC 1
#define CONFIG_DMA_NONCOHERENT 1
#undef CONFIG_CPU_LITTLE_ENDIAN
#define CONFIG_IRQ_CPU 1
#define CONFIG_SWAP_IO_SPACE 1
#define CONFIG_BOOT_ELF32 1
#define CONFIG_MIPS_L1_CACHE_SHIFT 5
#define CONFIG_ARC32 1
#undef CONFIG_FB
#define CONFIG_ARC_CONSOLE 1
#define CONFIG_ARC_PROMLIB 1

/*
 * CPU selection
 */
#undef CONFIG_CPU_MIPS32
#undef CONFIG_CPU_MIPS64
#undef CONFIG_CPU_R3000
#undef CONFIG_CPU_TX39XX
#undef CONFIG_CPU_VR41XX
#undef CONFIG_CPU_R4300
#undef CONFIG_CPU_R4X00
#undef CONFIG_CPU_TX49XX
#define CONFIG_CPU_R5000 1
#undef CONFIG_CPU_R5432
#undef CONFIG_CPU_R6000
#undef CONFIG_CPU_NEVADA
#undef CONFIG_CPU_R8000
#undef CONFIG_CPU_R10000
#undef CONFIG_CPU_RM7000
#undef CONFIG_CPU_RM9000
#undef CONFIG_CPU_SB1
#define CONFIG_PAGE_SIZE_4KB 1
#undef CONFIG_PAGE_SIZE_8KB
#undef CONFIG_PAGE_SIZE_16KB
#undef CONFIG_PAGE_SIZE_64KB
#define CONFIG_BOARD_SCACHE 1
#define CONFIG_IP22_CPU_SCACHE 1
#undef CONFIG_64BIT_PHYS_ADDR
#undef CONFIG_CPU_ADVANCED
#define CONFIG_CPU_HAS_LLSC 1
#define CONFIG_CPU_HAS_LLDSCD 1
#define CONFIG_CPU_HAS_SYNC 1
#undef CONFIG_PREEMPT

/*
 * Bus options (PCI, PCMCIA, EISA, ISA, TC)
 */
#undef CONFIG_EISA
#define CONFIG_MMU 1

/*
 * PCCARD (PCMCIA/CardBus) support
 */
#undef CONFIG_PCCARD

/*
 * PCI Hotplug Support
 */

/*
 * Executable file formats
 */
#define CONFIG_BINFMT_ELF 1
#define CONFIG_BINFMT_MISC_MODULE 1
#define CONFIG_TRAD_SIGNALS 1

/*
 * Device Drivers
 */

/*
 * Generic Driver Options
 */
#define CONFIG_STANDALONE 1
#define CONFIG_PREVENT_FIRMWARE_BUILD 1
#undef CONFIG_FW_LOADER

/*
 * Memory Technology Devices (MTD)
 */
#undef CONFIG_MTD

/*
 * Parallel port support
 */
#undef CONFIG_PARPORT

/*
 * Plug and Play support
 */

/*
 * Block devices
 */
#undef CONFIG_BLK_DEV_FD
#undef CONFIG_BLK_DEV_COW_COMMON
#undef CONFIG_BLK_DEV_LOOP
#undef CONFIG_BLK_DEV_NBD
#undef CONFIG_BLK_DEV_RAM
#define CONFIG_BLK_DEV_RAM_COUNT 16
#define CONFIG_INITRAMFS_SOURCE ""
#undef CONFIG_LBD
#define CONFIG_CDROM_PKTCDVD_MODULE 1
#define CONFIG_CDROM_PKTCDVD_BUFFERS 8
#undef CONFIG_CDROM_PKTCDVD_WCACHE

/*
 * IO Schedulers
 */
#define CONFIG_IOSCHED_NOOP 1
#define CONFIG_IOSCHED_AS 1
#define CONFIG_IOSCHED_DEADLINE 1
#define CONFIG_IOSCHED_CFQ 1
#define CONFIG_ATA_OVER_ETH_MODULE 1

/*
 * ATA/ATAPI/MFM/RLL support
 */
#undef CONFIG_IDE

/*
 * SCSI device support
 */
#define CONFIG_SCSI 1
#define CONFIG_SCSI_PROC_FS 1

/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#define CONFIG_BLK_DEV_SD 1
#define CONFIG_CHR_DEV_ST 1
#undef CONFIG_CHR_DEV_OSST
#define CONFIG_BLK_DEV_SR 1
#undef CONFIG_BLK_DEV_SR_VENDOR
#undef CONFIG_CHR_DEV_SG

/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#undef CONFIG_SCSI_MULTI_LUN
#define CONFIG_SCSI_CONSTANTS 1
#undef CONFIG_SCSI_LOGGING

/*
 * SCSI Transport Attributes
 */
#define CONFIG_SCSI_SPI_ATTRS_MODULE 1
#undef CONFIG_SCSI_FC_ATTRS
#define CONFIG_SCSI_ISCSI_ATTRS_MODULE 1

/*
 * SCSI low-level drivers
 */
#define CONFIG_SGIWD93_SCSI 1
#undef CONFIG_SCSI_SATA
#undef CONFIG_SCSI_DEBUG

/*
 * Multi-device support (RAID and LVM)
 */
#undef CONFIG_MD

/*
 * Fusion MPT device support
 */

/*
 * IEEE 1394 (FireWire) support
 */

/*
 * I2O device support
 */

/*
 * Networking support
 */
#define CONFIG_NET 1

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#define CONFIG_PACKET_MMAP 1
#define CONFIG_UNIX 1
#define CONFIG_NET_KEY 1
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#undef CONFIG_IP_ADVANCED_ROUTER
#define CONFIG_IP_PNP 1
#undef CONFIG_IP_PNP_DHCP
#define CONFIG_IP_PNP_BOOTP 1
#undef CONFIG_IP_PNP_RARP
#undef CONFIG_NET_IPIP
#undef CONFIG_NET_IPGRE
#undef CONFIG_IP_MROUTE
#undef CONFIG_ARPD
#undef CONFIG_SYN_COOKIES
#define CONFIG_INET_AH_MODULE 1
#define CONFIG_INET_ESP_MODULE 1
#define CONFIG_INET_IPCOMP_MODULE 1
#define CONFIG_INET_TUNNEL_MODULE 1
#define CONFIG_IP_TCPDIAG_MODULE 1
#define CONFIG_IP_TCPDIAG_IPV6 1

/*
 * IP: Virtual Server Configuration
 */
#define CONFIG_IP_VS_MODULE 1
#undef CONFIG_IP_VS_DEBUG
#define CONFIG_IP_VS_TAB_BITS 12

/*
 * IPVS transport protocol load balancing support
 */
#define CONFIG_IP_VS_PROTO_TCP 1
#define CONFIG_IP_VS_PROTO_UDP 1
#define CONFIG_IP_VS_PROTO_ESP 1
#define CONFIG_IP_VS_PROTO_AH 1

/*
 * IPVS scheduler
 */
#define CONFIG_IP_VS_RR_MODULE 1
#define CONFIG_IP_VS_WRR_MODULE 1
#define CONFIG_IP_VS_LC_MODULE 1
#define CONFIG_IP_VS_WLC_MODULE 1
#define CONFIG_IP_VS_LBLC_MODULE 1
#define CONFIG_IP_VS_LBLCR_MODULE 1
#define CONFIG_IP_VS_DH_MODULE 1
#define CONFIG_IP_VS_SH_MODULE 1
#define CONFIG_IP_VS_SED_MODULE 1
#define CONFIG_IP_VS_NQ_MODULE 1

/*
 * IPVS application helper
 */
#define CONFIG_IP_VS_FTP_MODULE 1
#define CONFIG_IPV6_MODULE 1
#define CONFIG_IPV6_PRIVACY 1
#define CONFIG_INET6_AH_MODULE 1
#define CONFIG_INET6_ESP_MODULE 1
#define CONFIG_INET6_IPCOMP_MODULE 1
#define CONFIG_INET6_TUNNEL_MODULE 1
#define CONFIG_IPV6_TUNNEL_MODULE 1
#define CONFIG_NETFILTER 1
#undef CONFIG_NETFILTER_DEBUG

/*
 * IP: Netfilter Configuration
 */
#define CONFIG_IP_NF_CONNTRACK_MODULE 1
#define CONFIG_IP_NF_CT_ACCT 1
#define CONFIG_IP_NF_CONNTRACK_MARK 1
#undef CONFIG_IP_NF_CT_PROTO_SCTP
#define CONFIG_IP_NF_FTP_MODULE 1
#define CONFIG_IP_NF_IRC_MODULE 1
#define CONFIG_IP_NF_TFTP_MODULE 1
#define CONFIG_IP_NF_AMANDA_MODULE 1
#define CONFIG_IP_NF_QUEUE_MODULE 1
#define CONFIG_IP_NF_IPTABLES_MODULE 1
#define CONFIG_IP_NF_MATCH_LIMIT_MODULE 1
#define CONFIG_IP_NF_MATCH_IPRANGE_MODULE 1
#define CONFIG_IP_NF_MATCH_MAC_MODULE 1
#define CONFIG_IP_NF_MATCH_PKTTYPE_MODULE 1
#define CONFIG_IP_NF_MATCH_MARK_MODULE 1
#define CONFIG_IP_NF_MATCH_MULTIPORT_MODULE 1
#define CONFIG_IP_NF_MATCH_TOS_MODULE 1
#define CONFIG_IP_NF_MATCH_RECENT_MODULE 1
#define CONFIG_IP_NF_MATCH_ECN_MODULE 1
#define CONFIG_IP_NF_MATCH_DSCP_MODULE 1
#define CONFIG_IP_NF_MATCH_AH_ESP_MODULE 1
#define CONFIG_IP_NF_MATCH_LENGTH_MODULE 1
#define CONFIG_IP_NF_MATCH_TTL_MODULE 1
#define CONFIG_IP_NF_MATCH_TCPMSS_MODULE 1
#define CONFIG_IP_NF_MATCH_HELPER_MODULE 1
#define CONFIG_IP_NF_MATCH_STATE_MODULE 1
#define CONFIG_IP_NF_MATCH_CONNTRACK_MODULE 1
#define CONFIG_IP_NF_MATCH_OWNER_MODULE 1
#define CONFIG_IP_NF_MATCH_ADDRTYPE_MODULE 1
#define CONFIG_IP_NF_MATCH_REALM_MODULE 1
#define CONFIG_IP_NF_MATCH_SCTP_MODULE 1
#define CONFIG_IP_NF_MATCH_COMMENT_MODULE 1
#define CONFIG_IP_NF_MATCH_CONNMARK_MODULE 1
#define CONFIG_IP_NF_MATCH_HASHLIMIT_MODULE 1
#define CONFIG_IP_NF_FILTER_MODULE 1
#define CONFIG_IP_NF_TARGET_REJECT_MODULE 1
#define CONFIG_IP_NF_TARGET_LOG_MODULE 1
#define CONFIG_IP_NF_TARGET_ULOG_MODULE 1
#define CONFIG_IP_NF_TARGET_TCPMSS_MODULE 1
#define CONFIG_IP_NF_NAT_MODULE 1
#define CONFIG_IP_NF_NAT_NEEDED 1
#define CONFIG_IP_NF_TARGET_MASQUERADE_MODULE 1
#define CONFIG_IP_NF_TARGET_REDIRECT_MODULE 1
#define CONFIG_IP_NF_TARGET_NETMAP_MODULE 1
#define CONFIG_IP_NF_TARGET_SAME_MODULE 1
#define CONFIG_IP_NF_NAT_SNMP_BASIC_MODULE 1
#define CONFIG_IP_NF_NAT_IRC_MODULE 1
#define CONFIG_IP_NF_NAT_FTP_MODULE 1
#define CONFIG_IP_NF_NAT_TFTP_MODULE 1
#define CONFIG_IP_NF_NAT_AMANDA_MODULE 1
#define CONFIG_IP_NF_MANGLE_MODULE 1
#define CONFIG_IP_NF_TARGET_TOS_MODULE 1
#define CONFIG_IP_NF_TARGET_ECN_MODULE 1
#define CONFIG_IP_NF_TARGET_DSCP_MODULE 1
#define CONFIG_IP_NF_TARGET_MARK_MODULE 1
#define CONFIG_IP_NF_TARGET_CLASSIFY_MODULE 1
#define CONFIG_IP_NF_TARGET_CONNMARK_MODULE 1
#define CONFIG_IP_NF_TARGET_CLUSTERIP_MODULE 1
#define CONFIG_IP_NF_RAW_MODULE 1
#define CONFIG_IP_NF_TARGET_NOTRACK_MODULE 1
#define CONFIG_IP_NF_ARPTABLES_MODULE 1
#define CONFIG_IP_NF_ARPFILTER_MODULE 1
#define CONFIG_IP_NF_ARP_MANGLE_MODULE 1

/*
 * IPv6: Netfilter Configuration (EXPERIMENTAL)
 */
#define CONFIG_IP6_NF_QUEUE_MODULE 1
#define CONFIG_IP6_NF_IPTABLES_MODULE 1
#define CONFIG_IP6_NF_MATCH_LIMIT_MODULE 1
#define CONFIG_IP6_NF_MATCH_MAC_MODULE 1
#define CONFIG_IP6_NF_MATCH_RT_MODULE 1
#define CONFIG_IP6_NF_MATCH_OPTS_MODULE 1
#define CONFIG_IP6_NF_MATCH_FRAG_MODULE 1
#define CONFIG_IP6_NF_MATCH_HL_MODULE 1
#define CONFIG_IP6_NF_MATCH_MULTIPORT_MODULE 1
#define CONFIG_IP6_NF_MATCH_OWNER_MODULE 1
#define CONFIG_IP6_NF_MATCH_MARK_MODULE 1
#define CONFIG_IP6_NF_MATCH_IPV6HEADER_MODULE 1
#define CONFIG_IP6_NF_MATCH_AHESP_MODULE 1
#define CONFIG_IP6_NF_MATCH_LENGTH_MODULE 1
#define CONFIG_IP6_NF_MATCH_EUI64_MODULE 1
#define CONFIG_IP6_NF_FILTER_MODULE 1
#define CONFIG_IP6_NF_TARGET_LOG_MODULE 1
#define CONFIG_IP6_NF_MANGLE_MODULE 1
#define CONFIG_IP6_NF_TARGET_MARK_MODULE 1
#define CONFIG_IP6_NF_RAW_MODULE 1
#define CONFIG_XFRM 1
#define CONFIG_XFRM_USER_MODULE 1

/*
 * SCTP Configuration (EXPERIMENTAL)
 */
#define CONFIG_IP_SCTP_MODULE 1
#undef CONFIG_SCTP_DBG_MSG
#undef CONFIG_SCTP_DBG_OBJCNT
#undef CONFIG_SCTP_HMAC_NONE
#undef CONFIG_SCTP_HMAC_SHA1
#define CONFIG_SCTP_HMAC_MD5 1
#undef CONFIG_ATM
#undef CONFIG_BRIDGE
#undef CONFIG_VLAN_8021Q
#undef CONFIG_DECNET
#undef CONFIG_LLC2
#undef CONFIG_IPX
#undef CONFIG_ATALK
#undef CONFIG_X25
#undef CONFIG_LAPB
#define CONFIG_NET_DIVERT 1
#undef CONFIG_ECONET
#undef CONFIG_WAN_ROUTER

/*
 * QoS and/or fair queueing
 */
#define CONFIG_NET_SCHED 1
#undef CONFIG_NET_SCH_CLK_JIFFIES
#define CONFIG_NET_SCH_CLK_GETTIMEOFDAY 1
#undef CONFIG_NET_SCH_CLK_CPU
#define CONFIG_NET_SCH_CBQ_MODULE 1
#define CONFIG_NET_SCH_HTB_MODULE 1
#define CONFIG_NET_SCH_HFSC_MODULE 1
#define CONFIG_NET_SCH_PRIO_MODULE 1
#define CONFIG_NET_SCH_RED_MODULE 1
#define CONFIG_NET_SCH_SFQ_MODULE 1
#define CONFIG_NET_SCH_TEQL_MODULE 1
#define CONFIG_NET_SCH_TBF_MODULE 1
#define CONFIG_NET_SCH_GRED_MODULE 1
#define CONFIG_NET_SCH_DSMARK_MODULE 1
#define CONFIG_NET_SCH_NETEM_MODULE 1
#define CONFIG_NET_SCH_INGRESS_MODULE 1
#define CONFIG_NET_QOS 1
#define CONFIG_NET_ESTIMATOR 1
#define CONFIG_NET_CLS 1
#undef CONFIG_NET_CLS_BASIC
#define CONFIG_NET_CLS_TCINDEX_MODULE 1
#define CONFIG_NET_CLS_ROUTE4_MODULE 1
#define CONFIG_NET_CLS_ROUTE 1
#define CONFIG_NET_CLS_FW_MODULE 1
#define CONFIG_NET_CLS_U32_MODULE 1
#undef CONFIG_CLS_U32_PERF
#undef CONFIG_NET_CLS_IND
#undef CONFIG_CLS_U32_MARK
#define CONFIG_NET_CLS_RSVP_MODULE 1
#define CONFIG_NET_CLS_RSVP6_MODULE 1
#undef CONFIG_NET_EMATCH
#undef CONFIG_NET_CLS_ACT
#define CONFIG_NET_CLS_POLICE 1

/*
 * Network testing
 */
#undef CONFIG_NET_PKTGEN
#undef CONFIG_NETPOLL
#undef CONFIG_NET_POLL_CONTROLLER
#undef CONFIG_HAMRADIO
#undef CONFIG_IRDA
#undef CONFIG_BT
#define CONFIG_NETDEVICES 1
#define CONFIG_DUMMY_MODULE 1
#define CONFIG_BONDING_MODULE 1
#define CONFIG_EQUALIZER_MODULE 1
#define CONFIG_TUN_MODULE 1

/*
 * Ethernet (10 or 100Mbit)
 */
#define CONFIG_NET_ETHERNET 1
#undef CONFIG_MII
#define CONFIG_SGISEEQ 1

/*
 * Ethernet (1000 Mbit)
 */

/*
 * Ethernet (10000 Mbit)
 */

/*
 * Token Ring devices
 */

/*
 * Wireless LAN (non-hamradio)
 */
#undef CONFIG_NET_RADIO

/*
 * Wan interfaces
 */
#undef CONFIG_WAN
#undef CONFIG_PPP
#undef CONFIG_SLIP
#undef CONFIG_SHAPER
#undef CONFIG_NETCONSOLE

/*
 * ISDN subsystem
 */
#undef CONFIG_ISDN

/*
 * Telephony Support
 */
#undef CONFIG_PHONE

/*
 * Input device support
 */
#define CONFIG_INPUT 1

/*
 * Userland interfaces
 */
#define CONFIG_INPUT_MOUSEDEV_MODULE 1
#define CONFIG_INPUT_MOUSEDEV_PSAUX 1
#define CONFIG_INPUT_MOUSEDEV_SCREEN_X 1024
#define CONFIG_INPUT_MOUSEDEV_SCREEN_Y 768
#undef CONFIG_INPUT_JOYDEV
#undef CONFIG_INPUT_TSDEV
#undef CONFIG_INPUT_EVDEV
#undef CONFIG_INPUT_EVBUG

/*
 * Input Device Drivers
 */
#define CONFIG_INPUT_KEYBOARD 1
#define CONFIG_KEYBOARD_ATKBD 1
#undef CONFIG_KEYBOARD_SUNKBD
#undef CONFIG_KEYBOARD_LKKBD
#undef CONFIG_KEYBOARD_XTKBD
#undef CONFIG_KEYBOARD_NEWTON
#define CONFIG_INPUT_MOUSE 1
#define CONFIG_MOUSE_PS2_MODULE 1
#define CONFIG_MOUSE_SERIAL_MODULE 1
#undef CONFIG_MOUSE_VSXXXAA
#undef CONFIG_INPUT_JOYSTICK
#undef CONFIG_INPUT_TOUCHSCREEN
#undef CONFIG_INPUT_MISC

/*
 * Hardware I/O ports
 */
#define CONFIG_SERIO 1
#define CONFIG_SERIO_I8042 1
#define CONFIG_SERIO_SERPORT 1
#define CONFIG_SERIO_LIBPS2 1
#define CONFIG_SERIO_RAW_MODULE 1
#undef CONFIG_GAMEPORT

/*
 * Character devices
 */
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#define CONFIG_HW_CONSOLE 1
#undef CONFIG_SERIAL_NONSTANDARD

/*
 * Serial drivers
 */
#undef CONFIG_SERIAL_8250

/*
 * Non-8250 serial port support
 */
#define CONFIG_SERIAL_IP22_ZILOG_MODULE 1
#define CONFIG_SERIAL_CORE_MODULE 1
#define CONFIG_UNIX98_PTYS 1
#define CONFIG_LEGACY_PTYS 1
#define CONFIG_LEGACY_PTY_COUNT 256

/*
 * IPMI
 */
#undef CONFIG_IPMI_HANDLER

/*
 * Watchdog Cards
 */
#define CONFIG_WATCHDOG 1
#undef CONFIG_WATCHDOG_NOWAYOUT

/*
 * Watchdog Device Drivers
 */
#undef CONFIG_SOFT_WATCHDOG
#define CONFIG_INDYDOG_MODULE 1
#undef CONFIG_RTC
#define CONFIG_SGI_DS1286_MODULE 1
#undef CONFIG_GEN_RTC
#undef CONFIG_DTLK
#undef CONFIG_R3964

/*
 * Ftape, the floppy tape device driver
 */
#undef CONFIG_DRM
#define CONFIG_RAW_DRIVER_MODULE 1
#define CONFIG_MAX_RAW_DEVS 256

/*
 * TPM devices
 */

/*
 * I2C support
 */
#undef CONFIG_I2C

/*
 * Dallas's 1-wire bus
 */
#undef CONFIG_W1

/*
 * Misc devices
 */

/*
 * Multimedia devices
 */
#undef CONFIG_VIDEO_DEV

/*
 * Digital Video Broadcasting Devices
 */
#undef CONFIG_DVB

/*
 * Graphics support
 */

/*
 * Console display driver support
 */
#undef CONFIG_VGA_CONSOLE
#define CONFIG_SGI_NEWPORT_CONSOLE 1
#define CONFIG_DUMMY_CONSOLE 1
#define CONFIG_FONT_8x16 1

/*
 * Logo configuration
 */
#define CONFIG_LOGO 1
#undef CONFIG_LOGO_LINUX_MONO
#undef CONFIG_LOGO_LINUX_VGA16
#undef CONFIG_LOGO_LINUX_CLUT224
#define CONFIG_LOGO_SGI_CLUT224 1

/*
 * Sound
 */
#undef CONFIG_SOUND

/*
 * USB support
 */
#undef CONFIG_USB_ARCH_HAS_HCD
#undef CONFIG_USB_ARCH_HAS_OHCI

/*
 * USB Gadget Support
 */
#undef CONFIG_USB_GADGET

/*
 * MMC/SD Card support
 */
#undef CONFIG_MMC

/*
 * InfiniBand support
 */
#undef CONFIG_INFINIBAND

/*
 * File systems
 */
#define CONFIG_EXT2_FS_MODULE 1
#undef CONFIG_EXT2_FS_XATTR
#define CONFIG_EXT3_FS 1
#define CONFIG_EXT3_FS_XATTR 1
#define CONFIG_EXT3_FS_POSIX_ACL 1
#define CONFIG_EXT3_FS_SECURITY 1
#define CONFIG_JBD 1
#undef CONFIG_JBD_DEBUG
#define CONFIG_FS_MBCACHE 1
#undef CONFIG_REISERFS_FS
#undef CONFIG_JFS_FS
#define CONFIG_FS_POSIX_ACL 1

/*
 * XFS support
 */
#define CONFIG_XFS_FS_MODULE 1
#define CONFIG_XFS_EXPORT 1
#undef CONFIG_XFS_RT
#define CONFIG_XFS_QUOTA 1
#define CONFIG_XFS_SECURITY 1
#undef CONFIG_XFS_POSIX_ACL
#define CONFIG_MINIX_FS_MODULE 1
#undef CONFIG_ROMFS_FS
#define CONFIG_QUOTA 1
#undef CONFIG_QFMT_V1
#define CONFIG_QFMT_V2_MODULE 1
#define CONFIG_QUOTACTL 1
#define CONFIG_DNOTIFY 1
#define CONFIG_AUTOFS_FS_MODULE 1
#define CONFIG_AUTOFS4_FS_MODULE 1

/*
 * CD-ROM/DVD Filesystems
 */
#define CONFIG_ISO9660_FS_MODULE 1
#define CONFIG_JOLIET 1
#define CONFIG_ZISOFS 1
#define CONFIG_ZISOFS_FS_MODULE 1
#define CONFIG_UDF_FS_MODULE 1
#define CONFIG_UDF_NLS 1

/*
 * DOS/FAT/NT Filesystems
 */
#define CONFIG_FAT_FS_MODULE 1
#define CONFIG_MSDOS_FS_MODULE 1
#define CONFIG_VFAT_FS_MODULE 1
#define CONFIG_FAT_DEFAULT_CODEPAGE 437
#define CONFIG_FAT_DEFAULT_IOCHARSET "iso8859-1"
#undef CONFIG_NTFS_FS

/*
 * Pseudo filesystems
 */
#define CONFIG_PROC_FS 1
#define CONFIG_PROC_KCORE 1
#define CONFIG_SYSFS 1
#undef CONFIG_DEVFS_FS
#define CONFIG_DEVPTS_FS_XATTR 1
#define CONFIG_DEVPTS_FS_SECURITY 1
#undef CONFIG_TMPFS
#undef CONFIG_HUGETLB_PAGE
#define CONFIG_RAMFS 1

/*
 * Miscellaneous filesystems
 */
#undef CONFIG_ADFS_FS
#undef CONFIG_AFFS_FS
#undef CONFIG_HFS_FS
#undef CONFIG_HFSPLUS_FS
#undef CONFIG_BEFS_FS
#undef CONFIG_BFS_FS
#define CONFIG_EFS_FS_MODULE 1
#undef CONFIG_CRAMFS
#undef CONFIG_VXFS_FS
#undef CONFIG_HPFS_FS
#undef CONFIG_QNX4FS_FS
#undef CONFIG_SYSV_FS
#define CONFIG_UFS_FS_MODULE 1
#undef CONFIG_UFS_FS_WRITE

/*
 * Network File Systems
 */
#define CONFIG_NFS_FS_MODULE 1
#define CONFIG_NFS_V3 1
#undef CONFIG_NFS_V4
#undef CONFIG_NFS_DIRECTIO
#define CONFIG_NFSD_MODULE 1
#define CONFIG_NFSD_V3 1
#undef CONFIG_NFSD_V4
#define CONFIG_NFSD_TCP 1
#define CONFIG_LOCKD_MODULE 1
#define CONFIG_LOCKD_V4 1
#define CONFIG_EXPORTFS_MODULE 1
#define CONFIG_SUNRPC_MODULE 1
#define CONFIG_SUNRPC_GSS_MODULE 1
#define CONFIG_RPCSEC_GSS_KRB5_MODULE 1
#undef CONFIG_RPCSEC_GSS_SPKM3
#define CONFIG_SMB_FS_MODULE 1
#define CONFIG_SMB_NLS_DEFAULT 1
#define CONFIG_SMB_NLS_REMOTE "cp437"
#define CONFIG_CIFS_MODULE 1
#undef CONFIG_CIFS_STATS
#undef CONFIG_CIFS_XATTR
#undef CONFIG_CIFS_EXPERIMENTAL
#undef CONFIG_NCP_FS
#define CONFIG_CODA_FS_MODULE 1
#undef CONFIG_CODA_FS_OLD_API
#undef CONFIG_AFS_FS

/*
 * Partition Types
 */
#define CONFIG_PARTITION_ADVANCED 1
#undef CONFIG_ACORN_PARTITION
#undef CONFIG_OSF_PARTITION
#undef CONFIG_AMIGA_PARTITION
#undef CONFIG_ATARI_PARTITION
#undef CONFIG_MAC_PARTITION
#define CONFIG_MSDOS_PARTITION 1
#undef CONFIG_BSD_DISKLABEL
#undef CONFIG_MINIX_SUBPARTITION
#undef CONFIG_SOLARIS_X86_PARTITION
#undef CONFIG_UNIXWARE_DISKLABEL
#undef CONFIG_LDM_PARTITION
#define CONFIG_SGI_PARTITION 1
#undef CONFIG_ULTRIX_PARTITION
#undef CONFIG_SUN_PARTITION
#undef CONFIG_EFI_PARTITION

/*
 * Native Language Support
 */
#define CONFIG_NLS_MODULE 1
#define CONFIG_NLS_DEFAULT "iso8859-1"
#define CONFIG_NLS_CODEPAGE_437_MODULE 1
#define CONFIG_NLS_CODEPAGE_737_MODULE 1
#define CONFIG_NLS_CODEPAGE_775_MODULE 1
#define CONFIG_NLS_CODEPAGE_850_MODULE 1
#define CONFIG_NLS_CODEPAGE_852_MODULE 1
#define CONFIG_NLS_CODEPAGE_855_MODULE 1
#define CONFIG_NLS_CODEPAGE_857_MODULE 1
#define CONFIG_NLS_CODEPAGE_860_MODULE 1
#define CONFIG_NLS_CODEPAGE_861_MODULE 1
#define CONFIG_NLS_CODEPAGE_862_MODULE 1
#define CONFIG_NLS_CODEPAGE_863_MODULE 1
#define CONFIG_NLS_CODEPAGE_864_MODULE 1
#define CONFIG_NLS_CODEPAGE_865_MODULE 1
#define CONFIG_NLS_CODEPAGE_866_MODULE 1
#define CONFIG_NLS_CODEPAGE_869_MODULE 1
#define CONFIG_NLS_CODEPAGE_936_MODULE 1
#define CONFIG_NLS_CODEPAGE_950_MODULE 1
#define CONFIG_NLS_CODEPAGE_932_MODULE 1
#define CONFIG_NLS_CODEPAGE_949_MODULE 1
#define CONFIG_NLS_CODEPAGE_874_MODULE 1
#define CONFIG_NLS_ISO8859_8_MODULE 1
#define CONFIG_NLS_CODEPAGE_1250_MODULE 1
#define CONFIG_NLS_CODEPAGE_1251_MODULE 1
#define CONFIG_NLS_ASCII_MODULE 1
#define CONFIG_NLS_ISO8859_1_MODULE 1
#define CONFIG_NLS_ISO8859_2_MODULE 1
#define CONFIG_NLS_ISO8859_3_MODULE 1
#define CONFIG_NLS_ISO8859_4_MODULE 1
#define CONFIG_NLS_ISO8859_5_MODULE 1
#define CONFIG_NLS_ISO8859_6_MODULE 1
#define CONFIG_NLS_ISO8859_7_MODULE 1
#define CONFIG_NLS_ISO8859_9_MODULE 1
#define CONFIG_NLS_ISO8859_13_MODULE 1
#define CONFIG_NLS_ISO8859_14_MODULE 1
#define CONFIG_NLS_ISO8859_15_MODULE 1
#define CONFIG_NLS_KOI8_R_MODULE 1
#define CONFIG_NLS_KOI8_U_MODULE 1
#define CONFIG_NLS_UTF8_MODULE 1

/*
 * Kernel hacking
 */
#undef CONFIG_PRINTK_TIME
#undef CONFIG_DEBUG_KERNEL
#define CONFIG_LOG_BUF_SHIFT 14
#define CONFIG_CROSSCOMPILE 1
#define CONFIG_CMDLINE ""

/*
 * Security options
 */
#define CONFIG_KEYS 1
#define CONFIG_KEYS_DEBUG_PROC_KEYS 1
#undef CONFIG_SECURITY

/*
 * Cryptographic options
 */
#define CONFIG_CRYPTO 1
#define CONFIG_CRYPTO_HMAC 1
#define CONFIG_CRYPTO_NULL_MODULE 1
#define CONFIG_CRYPTO_MD4_MODULE 1
#define CONFIG_CRYPTO_MD5_MODULE 1
#define CONFIG_CRYPTO_SHA1_MODULE 1
#define CONFIG_CRYPTO_SHA256_MODULE 1
#define CONFIG_CRYPTO_SHA512_MODULE 1
#define CONFIG_CRYPTO_WP512_MODULE 1
#undef CONFIG_CRYPTO_TGR192
#define CONFIG_CRYPTO_DES_MODULE 1
#define CONFIG_CRYPTO_BLOWFISH_MODULE 1
#define CONFIG_CRYPTO_TWOFISH_MODULE 1
#define CONFIG_CRYPTO_SERPENT_MODULE 1
#define CONFIG_CRYPTO_AES_MODULE 1
#define CONFIG_CRYPTO_CAST5_MODULE 1
#define CONFIG_CRYPTO_CAST6_MODULE 1
#define CONFIG_CRYPTO_TEA_MODULE 1
#define CONFIG_CRYPTO_ARC4_MODULE 1
#define CONFIG_CRYPTO_KHAZAD_MODULE 1
#define CONFIG_CRYPTO_ANUBIS_MODULE 1
#define CONFIG_CRYPTO_DEFLATE 1
#define CONFIG_CRYPTO_MICHAEL_MIC_MODULE 1
#define CONFIG_CRYPTO_CRC32C_MODULE 1
#define CONFIG_CRYPTO_TEST_MODULE 1

/*
 * Hardware crypto devices
 */

/*
 * Library routines
 */
#undef CONFIG_CRC_CCITT
#define CONFIG_CRC32_MODULE 1
#define CONFIG_LIBCRC32C_MODULE 1
#define CONFIG_ZLIB_INFLATE 1
#define CONFIG_ZLIB_DEFLATE 1
#define CONFIG_GENERIC_HARDIRQS 1
#define CONFIG_GENERIC_IRQ_PROBE 1
#define CONFIG_ISA_DMA_API 1
