#!/bin/sh
set -e

# Old versions of glibc installed these symlinks.  Remove them
# if they exist.
if [ -L /usr/include/asm ] ; then rm -f /usr/include/asm ; fi
if [ -L /usr/include/linux ] ; then rm -f /usr/include/linux ; fi
if [ -L /usr/include/scsi ] ; then rm -f /usr/include/scsi ; fi

# Another potential symlink which should not exist.  Just in case.
if [ -L /usr/include/asm-generic ] ; then rm -f /usr/include/asm-generic ; fi

#DEBHELPER#
